### ISSUE TITLE
cmake build not building all binaries

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1052]
List of all binaries produced by msbuild build that are missing from cmake build.
- [ ] bindmonitor.sys
- [ ] bindmonitor_ringbuf.sys
- [ ] bindmonitor_ringbuf_um.dll
- [ ] bindmonitor_tailcall.sys
- [ ] bindmonitor_tailcall_um.dll
- [ ] bindmonitor_um.dll
- [ ] bpf.sys
- [ ] bpf_call.sys
- [ ] bpf_call_um.dll
- [ ] bpf_um.dll
- [ ] bpftool_tests.exe
- [ ] cgroup_sock_addr.sys
- [ ] cgroup_sock_addr_um.dll
- [ ] cilium_tests.exe
- [ ] concrt140d.dll
- [ ] decap_permit_packet.sys
- [ ] decap_permit_packet_um.dll
- [ ] divide_by_zero.sys
- [ ] divide_by_zero_um.dll
- [ ] droppacket.sys
- [ ] droppacket_um.dll
- [ ] droppacket_unsafe.sys
- [ ] droppacket_unsafe_um.dll
- [ ] encap_reflect_packet.sys
- [ ] encap_reflect_packet_um.dll
- [ ] fuzz.exe
- [ ] invalid_helpers.sys
- [ ] invalid_helpers_um.dll
- [ ] invalid_maps1.sys
- [ ] invalid_maps1_um.dll
- [ ] invalid_maps2.sys
- [ ] invalid_maps2_um.dll
- [ ] map.sys
- [ ] map_in_map.sys
- [ ] map_in_map_um.dll
- [ ] map_in_map_v2.sys
- [ ] map_in_map_v2_um.dll
- [ ] map_reuse.sys
- [ ] map_reuse_2.sys
- [ ] map_reuse_2_um.dll
- [ ] map_reuse_um.dll
- [ ] map_um.dll
- [ ] msvcp140_1d.dll
- [ ] msvcp140_2d.dll
- [ ] msvcp140d.dll
- [ ] msvcp140d_atomic_wait.dll
- [ ] msvcp140d_codecvt_ids.dll
- [ ] printk.sys
- [ ] printk_legacy.sys
- [ ] printk_legacy_um.dll
- [ ] printk_um.dll
- [ ] printk_unsafe.sys
- [ ] printk_unsafe_um.dll
- [ ] reflect_packet.sys
- [ ] reflect_packet_um.dll
- [ ] sample_ebpf_ext.sys
- [ ] sample_ext_app.exe
- [ ] socket_tests.exe
- [ ] sockops.sys
- [ ] sockops_um.dll
- [ ] tail_call.sys
- [ ] tail_call_bad.sys
- [ ] tail_call_bad_um.dll
- [ ] tail_call_map.sys
- [ ] tail_call_map_um.dll
- [ ] tail_call_multiple.sys
- [ ] tail_call_multiple_um.dll
- [ ] tail_call_um.dll
- [ ] test_sample_ebpf.sys
- [ ] test_sample_ebpf_um.dll
- [ ] test_utility_helpers.sys
- [ ] test_utility_helpers_um.dll
- [ ] ucrtbased.dll
- [ ] vccorlib140d.dll
- [ ] vcruntime140_1d.dll
- [ ] vcruntime140d.dll

**Comment by Alan-Jowett** [comment]
Possible sample for how to build BPF ELF files from cmake:
https://github.com/libbpf/libbpf-bootstrap/blob/master/examples/c/CMakeLists.txt

**Comment by shankarseal** [comment]
@alessandrogario  - I have created a cmakefiles.txt under tests\sample and in that I have a custom_target. I want to take a dependency on the executable "bpf2c" in cmakefiles.txt under tools\bpf2c. How do I do that?
