### ISSUE TITLE
[codecov][ebpf_platform_user.cpp] Code coverage < 80%

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1076]
ebpf_platform_user.cpp has less than 80% code coverage. There should be more test cases to increase coverage.

https://app.codecov.io/gh/microsoft/ebpf-for-windows/blob/main/libs/platform/user/ebpf_platform_user.cpp

**Comment by dthaler** [comment]
This now shows as 83.14% coverage, so closing since the title is now met.
Feel free to reopen if title is changed.
