### ISSUE TITLE
Kernel CI/CD should run with driver verifier enabled

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1090]
These issues should have been caught in Kernel CI/CD by the driver verifier but weren't caught.
https://github.com/microsoft/ebpf-for-windows/issues/1087
https://github.com/microsoft/ebpf-for-windows/issues/1085
https://github.com/microsoft/ebpf-for-windows/pull/1084

Need to investigate why.

**Comment by dthaler** [comment]
@Alan-Jowett @shankarseal wasn't this fixed by PR #1375 ?
If not, what is remaining?

**Comment by shankarseal** [comment]
This bug is outdated and be closed. DV is indeed enabled on all test VMs. I logged into each of the test VMs in all the selfhost runner machines and ensured that DV is enabled for ebpfcore and netebpfext drivers.
 
 #1375 was about KMDF and this bug is asking for driver verifier to be enabled.
