### ISSUE TITLE
IPv6 address in bpf_sock_addr_t is missing scope id field

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1129]
https://github.com/microsoft/ebpf-for-windows/blob/ec26f5d273146c9c1c66b491f00e3b972cc10914/include/ebpf_nethooks.h#L133

IPv6 address is missing the scope id field.

**Comment by dthaler** [comment]
@teknoraver @qmonnet Can you verify whether Linux has a bug here too?
