### ISSUE TITLE
Add negative test cases for native module loading IOCTL interface.

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1139]
The IOCTL interface for native modules should have negative test.

Assignees: 
Labels:

**Comment by saxena-anurag** [comment]
PR #1039 already added negative IOCTL tests for native module load.

**Comment by Alan-Jowett** [comment]
https://app.codecov.io/gh/microsoft/ebpf-for-windows/compare/1132/tree/libs/execution_context/ebpf_native.c

**Comment by Alan-Jowett** [comment]
Quite a few error paths related to invalid parameters paths aren't covered.
