### ISSUE TITLE
port_quota is unable to load successfully

### ISSUE THREAD

**Issue by t-cindywan** [microsoft/ebpf-for-windows#1165]
### Describe the bug

PS C:\ebpf> .\port_quota.exe load
Failed to load port quota eBPF program
(null)

### Steps taken to reproduce bug

1. Ran Powershell
2. Changed directory to ebpf
3. Installed ebpf.bat
4. Ran port_quota load command

### Expected behavior

Expected port_quota eBPF program to load successfully

### Actual outcome

Failed to load, as shown above.

**Comment by shankarseal** [comment]
A test should be added in the driver test in the CI pipeline to at least load the bindmonitor program (both interpreter and native cases).
