### ISSUE TITLE
Getting Started guide's script fails to install wdk.vsix and spectre libraries

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1196]
https://github.com/microsoft/ebpf-for-windows/blob/main/docs/GettingStarted.md#prerequisites

The getting started script that installs all the tools should also install the WDK.vsix component from:
"c:\Program Files (x86)\Windows Kits\10\Vsix\VS2019\WDK.vsix"

And also install the "Spectre Latest" libraries.

**Comment by dthaler** [comment]
@Alan-Jowett on the "Spectre Latest" topic, https://github.com/microsoft/ebpf-for-windows/blob/main/docs/GettingStarted.md#prerequisites already says:

> [Visual Studio 2019 version 16.11.7 or later](https://www.techspot.com/downloads/downloadnow/7241/?evp=70f51271955e6392571f575e301cd9a3&file=9642), **including** the "Desktop development with C++" workload, and **the "MSVC v142 - VS 2019 C++ x64/x86 Spectre-mitigated libs (latest)"** which must be selected as an Individual component in the VS installer

Is that not sufficient?
