### ISSUE TITLE
Fix code scanning alert - Pinned-Dependencies

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#1227]
Tracking issue for:
- [ ] https://github.com/microsoft/ebpf-for-windows/security/code-scanning/404

@song-jiang can you look at this one?

**Comment by song-jiang** [comment]
@dthaler I've got `no page` error trying accessing the tracking issue URL. Do you think I don't have the permission or the page is removed somehow? Could you help to paste the error message here so I can see how to fix it?

**Comment by song-jiang** [comment]
I'm not sure if we need to fix this. There's pros & cons for pinning the image with tag or hash. I can think of two reasons that we should continue using tag.
1. The project is still in Dev mode. Tagging the image is more dev friendly. 
2. Other open source projects are using tag than hash. For example https://github.com/kubernetes/autoscaler/blob/master/builder/Dockerfile#L15

**Comment by dthaler** [comment]
@song-jiang Any thoughts on the next steps here?

**Comment by song-jiang** [comment]
@dthaler I've seen we've got a release. I'll raise PR to pin the image with hash this week.
