### ISSUE TITLE
Use HKEY_CURRENT_USER instead of HKEY_LOCAL_MACHINE for eBPF store.

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#1231]
### Describe the feature you'd like supported

eBPF store currently uses both HKEY_CURRENT_USER and HKEY_LOCAL_MACHINE. This registry hive can be accessed by non-admin users. 
Change eBPF store to use HKEY_CURRENT_USER instead which requires admin privileges for edit.

### Proposed solution

Use HKEY_CURRENT_USER instead of HKEY_LOCAL_MACHINE 

```[tasklist]
### Tasks
```

**Comment by dthaler** [comment]
Based on discussion in triage 12/4/2023 we should be able to just use HKCU now that we have a hash over program info.
And ebpf store km can then be removed.

**Comment by saxena-anurag** [comment]
KM store APIs have now been removed completely, and user mode APIs use HKCU. Per discussion in triage meeting, using HKCU is fine as it is only used for offline verification, and it should not be a security concern.
