### ISSUE TITLE
Epoch cleanup sometimes does not execute

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#1244]
### Describe the bug

Sometimes, epoch cleanup does not happen. This causes the native module to not be unloaded. The same module can then not be loaded again.

### Steps taken to reproduce bug

1. Run "api_test.exe" in a loop (with a sleep of few seconds between each iteration to allow the native drivers to be unloaded from previous test execution).
2. The tests will fail after a few (around 25) iterations.

### Expected behavior

The tests should succeed.

### Actual outcome

The tests fail.

**Comment by Alan-Jowett** [comment]
epoch_test_stale_items in libs\platform\unit\platform_unit_test.cpp repro's this bug every ~50 invocations.

**Comment by saxena-anurag** [comment]
Maybe related failure:

https://github.com/microsoft/ebpf-for-windows/runs/7103842515?check_suite_focus=true

`epoch_test_stale_items` test is failing.

**Comment by Alan-Jowett** [comment]
@saxena-anurag I think I have a fix for this.
