### ISSUE TITLE
Failed to attach program with bpftool.exe

### ISSUE THREAD

**Issue by song-jiang** [microsoft/ebpf-for-windows#1246]
### Describe the bug

I used `bpftool.exe` to load the program successfully but failed to attach it to the interface.

### OS information

Windows 2019

### Steps taken to reproduce bug

```
PS C:\src\calico\felix\bpf-gpl> Get-NetAdapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
vEthernet (nat)           Hyper-V Virtual Ethernet Adapter #2          21 Up           00-15-5D-97-0B-52        10 Gbps
vEthernet (external)      Hyper-V Virtual Ethernet Adapter             18 Up           00-22-48-42-A4-27        50 Gbps
Ethernet                  Microsoft Hyper-V Network Adapter            15 Up           00-22-48-42-A4-27        50 Gbps
Ethernet 2                Mellanox ConnectX-4 Lx Virtual Ether...      14 Up           00-22-48-42-A4-27        50 Gbps


PS C:\src\calico\felix\bpf-gpl> bpftool.exe net attach xdp id 786440 dev 'Ethernet 2'
Error: invalid devname Ethernet 2
```

I tried different name format.
```
PS C:\src\calico\felix\bpf-gpl> bpftool.exe net attach xdp id 786440 dev '\Device\Tcpip_{FF5CD92C-7262-4289-A766-C82ECE527460}'
Error: invalid devname \Device\Tcpip_{FF5CD92C-7262-4289-A766-C82ECE527460}
```

### Expected behavior

Attach the program successfully.

### Actual outcome

Failed to attach the program.

### Additional details

If I use `netsh` to load the program, it failed.
```
PS C:\src\calico\felix\bpf-gpl> netsh ebpf add prog xdp.o xdp
error 6: could not attach program
```

**Comment by dthaler** [comment]
For bpftool, it looks like the code currently only accepts an ifName like "ethernet_32781" and not other forms (yes this should be fixed).  You can see the legal string with say
`netsh interface ipv4 show interface level=verbose" and at the top of each interface section you'll see a line like
> IfLuid                             : ethernet_32781
with the usable value.

For netsh, you need to use an interface parameter, and netsh accepts multiple forms including an ifindex, the aforementioned ifname, and the "Ethernet 2" form you tried:
> netsh ebpf add prog xdp.o xdp interface="Ethernet 2"

**Comment by song-jiang** [comment]
Thanks @dthaler . I've attached the program successfully with `ethernet_xxxx` format.
