### ISSUE TITLE
CI/CD should file an issue when scheduled or push run fails

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1273]
When either a CI/CD run fails that was triggered by push or schedule (but not pull request), the CI/CD workflow should:
- [ ] File an issue
- [ ] Attach a link to the failing workflow
- [ ] Attach the logs, dump, or artifact that triggered the failure

**Comment by dthaler** [comment]
@Alan-Jowett is this issue fixed by #1385?  Can this be closed now?
