### ISSUE TITLE
Modifying an existing install via MSI doesn't install/uninstall any changed drivers

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#1276]
### Describe the bug

Modifying an existing install via MSI doesn't install/uninstall any changed drivers

### Steps taken to reproduce bug

* Install from MSI, leaving only the default (runtime) selected
* Run the MSI again, selecting Change, and add the "testing" component

### Expected behavior

* "sc query sampleebpfext" should show the driver running

### Actual outcome

* "sc query sampleebpfext" does not find the service
* "sc qc sampleebpfext" does not show the driver as installed

### Additional details

It is correctly installed if "testing" component was added at initial install time, but "Change" does not trigger install/uninstall of drivers.

**Comment by gtrevi** [comment]
@dthaler fyi
The actual outcome of replicating the "*Steps taken to reproduce bug*", seems actually more severe: 

### Steps taken to reproduce bug

* Install from MSI, leaving only the default `Runtime components` selected: the `eBPFCore` & `NetEbpfExt` drivers *and* the 
`eBPFSvc` service get correctly installed:
 
```cmd
c:\_ebpf>sc.exe qc eBPFSvc
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: eBPFSvc
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : C:\Program Files\ebpf-for-windows\ebpfsvc.exe
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : eBPFSvc
        DEPENDENCIES       : EbpfCore
        SERVICE_START_NAME : NT AUTHORITY\LocalService

c:\_ebpf>sc.exe qc eBPFCore
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: eBPFCore
        TYPE               : 1  KERNEL_DRIVER
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : \??\C:\Windows\system32\drivers\ebpfcore.sys
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : EbpfCore
        DEPENDENCIES       :
        SERVICE_START_NAME :

c:\_ebpf>sc.exe qc NetEbpfExt
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: NetEbpfExt
        TYPE               : 1  KERNEL_DRIVER
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : \??\C:\Windows\system32\drivers\netebpfext.sys
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : NetEbpfExt
        DEPENDENCIES       :
        SERVICE_START_NAME :
```
* Run the MSI again, selecting `Change`, and add the `Testing components`: besides the `SampleEbpfExt` driver not getting installed, both the `eBPFCore` & `NetEbpfExt` drivers *and* the `eBPFSvc` service are uninstalled:

```cmd
c:\_ebpf>sc qc eBPFSvc
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.


c:\_ebpf>sc qc eBPFCore
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.


c:\_ebpf>sc qc NetEbpfExt
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

c:\_ebpf>sc qc SampleEbpfExt
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.
```
