### ISSUE TITLE
MSI file should be tested in CI/CD

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#1279]
### Describe the feature you'd like supported

Currently the driver tests invoke the powershell script directly.
We should consider having them invoke the msi instead:
`msiexec.exe /i ebpf-for-windows.msi`

### Proposed solution

Invoke the MSI instead of the powershell script:

- [ ] rewrite Export-BuildArtifactsToVMs to copy MSI to VM
- [ ] rewrite Install-eBPFComponentsOnVM to install MSI

**Comment by dthaler** [comment]
Current status: PR #1284 tries to address this but is incomplete.   The msiexec command does the right thing when run manually in a VM but the same doesn't succeed when run in the script even though it's executed as admin, not sure why.

Also the PR does msiexec /i to install but doesn't yet do msiexec /x to uninstall, which needs to be added to cleanup_ebpf_cicd_tests.ps1.

**Comment by gtrevi** [comment]
Blocked on #3313
