### ISSUE TITLE
Enumerate maps associated with a program

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#1339]
### Describe the feature you'd like supported

Each program has a set of associated maps, and we report the number now via `bpf_obj_get_info_by_fd()` and display it in netsh etc.

However, on Linux you can also get the list of actual map ids via `bpf_obj_get_info_by_fd()` as well, and they are shown by bpftool.  We don't currently support that.  You just see that a program has 3 maps but you cannot tell which of all the maps are associated with that program.

On Linux, `bpf_obj_get_info_by_fd()` can get the actual map ids associated with a given program in `bpf_prof_info`.
The caller can specify the maximum number to get in the `nr_map_ids` field, and a pointer to an array in the `map_ids` field, and then call `bpf_obj_get_info_by_fd()`, whereupon they are filled in.

```
struct bpf_prog_info info = {0};
__u32 len = sizeof(info);
__u32 map_ids[num_maps];

info.nr_map_ids = num_maps;
info.map_ids = ptr_to_u64(map_ids);

int err = bpf_obj_get_info_by_fd(fd, &info, &len);
```
This is used by bpftool.

As near as I can tell from docs and libbpf code, `bpf_obj_get_info_by_fd()` is relying on undocumented (in any man page or bpf.h) Linux kernel behavior in the following respect.  Here's what seems to be the case:

•	The info buffer is [in] for some types of fds, and [in,out] for other ones.

•	It’s [in,out] for map ids.

•	For a `bpf_prog_info`, if `map_ids` is non-0 on input, then it contains a pointer to user application memory that ought to hold enough space to write `nr_map_ids` into it, and it’s the kernel’s job to check whether writing into that space is indeed safe before doing so.

•	If the kernel decides that it’s safe to write into the space, it will attempt to do so.  Not sure which of the following is true without looking at the code if `nr_map_ids` isn’t enough to hold all the current map ids… does the ebpf runtime fail the call, or write only a subset up to nr_map_ids? And on return, is nr_map_ids the total number of map ids, or only the number that was actually written into the caller provided space?

The fact that ebpf_object_get_info_by_fd() is designed this way makes it very difficult to implement the ability to query map_ids cross-platform, since it presumes that the runtime can simply write into arbitrary caller-provided memory which is not a very safe assumption in general. A better API for libbpf 1.0 would not rely on the caller passing an embedded pointer in a buffer passed to a generic API, but for example an API to query the maps for a given prog id.  I don’t think there is already another API to do so

### Proposed solution

If a UM app takes a pointer to its own stack variable, and writes that into the contents of a buffer that goes down to ebpfcore.sys via ioctl, is there any convenient way for the driver to read and/or write to that variable?
Or is it only if the ioctl buffer pointer is the pointer to the stack variable?

Option 1:
Make UM api look inside the fd to determine what object type it is,
and if it's a prog fd, then make a special ioctl query to get the maps if requested.

Option 2:
Figure out how to let the KM api check for pointer safety, and write into the UM process buffer if it's safe.

**Comment by Alan-Jowett** [comment]
It is possible to read and write user mode memory outside of the bounds of an IOCTL. See [ProbeForWrite](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-probeforwrite). Just make sure to wrap all access to user mode memory in a [structured exception handler block](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/handling-exceptions).
