### ISSUE TITLE
eBPF-For-Windows tutorial should point to InstallEbpf.md

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1405]
https://github.com/microsoft/ebpf-for-windows/blob/main/docs/tutorial.md 

This doc should point to the InstallEbpf.md doc instead of instructing to build eBPF for Windows.

**Comment by dthaler** [comment]
@jsturtevant Was this addressed in PR #1414?  If so can this be closed now?

**Comment by dthaler** [comment]
Clearing triaged tag since this didn't mark "help wanted" or get assigned to anyone, but might be fixed in 1414 so good to review/update in triage meeting.

**Comment by jsturtevant** [comment]
yes, can close
