### ISSUE TITLE
eBPF tutorial is out of date - Hooks and arguments

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1408]
The [Hooks and arguments section](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/tutorial.md#61-hooks-and-arguments) is out of date. It still says the context data is in https://github.com/microsoft/ebpf-for-windows/blob/main/libs/api_common/windows_platform_common.cpp which is no longer true.

**Comment by dthaler** [comment]
@jsturtevant was this addressed in PR #1414?  If so, can this be closed now?

**Comment by dthaler** [comment]
Clearing triaged tag since this didn't mark "help wanted" or get assigned to anyone, but might be fixed in 1414 so good to review/update in triage meeting.
