### ISSUE TITLE
CI/CD pipeline should load ebpfcore.sys and netebpext.sys, jit and execute an eBPF program

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#141]
CI/CD pipeline should load ebpfcore.sys and netebpext.sys, jit and execute an eBPF program

In addition, this should be with driver verifier enabled.

Proposed sequence of operations:
1) Start ebpfcore.sys
2) Start netebpfext.sys
3) Run "port_quota load"
4) Run "port_quota limit 1000"
5) Start "port_leak"
6) Wait 5 seconds.
7) Run "port_quota stats"
8) Run "port_quota unload"
9) Stop "port_leak"
10) Stop netebpfext.sys
11) Stop netebpfext.sys

Verification:
Port_quota stats should show at least 1 entry with 1000 ports.
No bugcheck on driver stop.

**Comment by Alan-Jowett** [comment]
Posted: [Loading unsigned driver in GitHub CI/CD pipeline](https://stackoverflow.microsoft.com/questions/260441) on stack-overflow to see if I can get an answer.

**Comment by dthaler** [comment]
Now using discussion #448 to track this.

**Comment by dthaler** [comment]
Blocked on #495
