### ISSUE TITLE
MSI installer should install services with AutoStart instead of on OnDemand 

### ISSUE THREAD

**Issue by jsturtevant** [microsoft/ebpf-for-windows#1412]
### Describe the feature you'd like supported

The ebpf services are installed with `start=demand` which means if the machine reboots it they don't start back up. I encountered this after installing and rebooting due to a needed update (https://github.com/microsoft/ebpf-for-windows-demo/issues/22#issuecomment-1254266031)

### Proposed solution

Switch services to `start=auto` which mean if machine reboots ebpf starts up. I believe this would be expected behavior in most scenarios.

### Additional context

change would be

https://github.com/microsoft/ebpf-for-windows/blob/ecd08ecbb992be596090a473970afcc1eb815576/scripts/install_ebpf.psm1#L63

and maybe modify the install extension in https://github.com/microsoft/ebpf-for-windows/blob/ecd08ecbb992be596090a473970afcc1eb815576/scripts/install_ebpf.psm1#L73

**Comment by shankarseal** [comment]
Proposed fix: eBPFSvc takes dependency on eBPFCore. eBPFSvc is marked as trigger start on RPC call. Also the extension drivers should be loaded with an eBPF program is attached with program type implemented by the extension driver. Maybe the registry store can be used for this purpose.
