### ISSUE TITLE
ebpf_get_current_cpu and ebpf_get_cpu_count return wrong value

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1424]
### Describe the bug

When running on a system with multiple CPU groups, these APIs return the wrong values. 

ebpf_get_cpu_count uses [KeQueryMaximumProcessorCount ](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kequerymaximumprocessorcount) which returns the maximum number of CPUs in group 0.

Likewise ebpf_get_current_cpu uses [KeGetCurrentProcessorNumber](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-kegetcurrentprocessornumber) which maps all only works correctly for CPUs in group 0.

### Steps taken to reproduce bug

Run on a system with multiple processor groups.
Use per-CPU structures.

### Expected behavior

Each CPU gets its own unique storage.

### Actual outcome

CPU's from group != 0 share storage with CPU's in group 0.

**Comment by dthaler** [comment]
@Alan-Jowett is this issue fixed in PR #1423?

**Comment by Alan-Jowett** [comment]
Yes, linked to the PR.
