### ISSUE TITLE
Add support for .maps section

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#1439]
### Describe the feature you'd like supported

Regarding the doc in progress at https://github.com/ebpffoundation/ebpf-docs/pull/4, Quentin wrote:
> libbpf v1.0 (see dropping support for maps section in favour of .maps ([Andrii's blog](https://nakryiko.com/posts/libbpf-v1/#other-api-clean-ups-renames-removals-etc))

### Proposed solution

Match libbpf 1.0

### Additional context

cilium/ebpf seems to read both types (and also data sections), which seems reasonable behavior:
https://github.com/cilium/ebpf/blob/master/elf_reader.go#L125

Aya also seems to read both types:
https://github.com/aya-rs/aya/blob/main/aya/src/obj/mod.rs#L1024

redbpf (which unlike Aya is listed as Major) only supports "maps":
https://github.com/foniod/redbpf/blob/main/redbpf/src/lib.rs#L1544

**Comment by dthaler** [comment]
@dthaler todo: file equivalent issues in ubpf and prevail repositories

**Comment by dthaler** [comment]
Blocked on https://github.com/ebpffoundation/ebpf-docs/pull/4 documentation for .maps

**Comment by dthaler** [comment]
Related to issue #900

**Comment by dthaler** [comment]
Blocked on:

- https://github.com/iovisor/ubpf/issues/130
- https://github.com/vbpf/ebpf-verifier/issues/394

**Comment by dthaler** [comment]
@Alan-Jowett assigning to you for now since it sounded like you were looking at this

**Comment by Alan-Jowett** [comment]
@dthaler I believe this is complete now? There is no reason to block on ubpf supporting this as ubpf doesn't have map support in general.
