### ISSUE TITLE
Support multiple eBPF programs in the same section

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#1440]
### Describe the feature you'd like supported

Quentin pointed out that libbpf v1.0 switched to fixed section names for program types instead of longest prefix match ([Andrii's blog again](https://nakryiko.com/posts/libbpf-v1/#bpf-program-sec-annotation-streamlining))).

### Proposed solution

Match libbpf

**Comment by dthaler** [comment]
@dthaler TODO: also file equivalent issues against ubpf and prevail

**Comment by dthaler** [comment]
@qmonnet can you check if there is another repo that has a sample ebpf program that does this?

**Comment by dthaler** [comment]
Blocked on updating prevail first

**Comment by qmonnet** [comment]
> another repo that has a sample ebpf program that does this?

I found nothing recent. Kernel samples seem to be up-to-date. But I found that the [xdp-tutorial](https://github.com/xdp-project/xdp-tutorial/blob/master/packet-solutions/xdp_prog_kern_02.c) uses several variants of `SEC("xdp_...")` to hold several XDP programs in object files. They would probably fail to load with a recent libbpf.

**Comment by dthaler** [comment]
Blocked on:

- https://github.com/iovisor/ubpf/issues/129
- https://github.com/vbpf/ebpf-verifier/issues/393

**Comment by dthaler** [comment]
moving since still blocked

**Comment by saxena-anurag** [comment]
Blocked on PREVAIL issue, moving to 2403.

**Comment by dthaler** [comment]
The [prog_array.c sample](https://github.com/vbpf/ebpf-samples/blob/master/src/prog_array.c) in the ebpf-samples repository does this. (Other existing samples might too.)


Using a section name is not sufficient. Instead use the C function name.

bpf2c support is covered by issue https://github.com/microsoft/ebpf-for-windows/issues/1460
This issue covers ebpfapi.dll and ebpfsvc.exe support.
