### ISSUE TITLE
Dockerfile questions

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#1448]
### Describe the bug

1. https://github.com/microsoft/ebpf-for-windows/blob/main/images/install-ebpf-for-windows.ps1#L24 references a script called install-ebpf.bat but I cannot find it in the repo, where is it?   This should probably now use the MSI to install instead of a .bat file.

2. Should a docker image be part of the build artifacts?

3.   Should a docker image be part of the release artifacts?

### Steps taken to reproduce bug

N/A

### Expected behavior

N/A

### Actual outcome

N/A

**Comment by dthaler** [comment]
@song-jiang can you weigh in on these?

**Comment by song-jiang** [comment]
> references a script called install-ebpf.bat but I cannot find it in the repo, where is it?
Oh.. I see. My code was based on `install-ebpf.bat` file but it seems it has been removed from the repo. I would need to replace it with MSI install.

> Should a docker image be part of the build artifacts?

**Comment by song-jiang** [comment]
Sorry I haven't done much recently on this. But somehow I could not download MSI package after build CI via `action` tab. Is it a permission issue? cc @Alan-Jowett

**Comment by song-jiang** [comment]
I'll miss community meeting today. For step 1, I should be able to raise PR this week.
