### ISSUE TITLE
Verify that prevail is consistent with bpf2c and ubpf behavior

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#1451]
### Describe the feature you'd like supported

https://github.com/Alan-Jowett/bpf_conformance has a runtime-agnostic conformance suite.
Prevail computes invariants when verifying a program, and so should be able to compute the results expected by the suite.

### Proposed solution

This can be done in the prevail repository but since ebpf-for-windows depends on having ubpf and bpf2c compute the same answers as the verifier expects, we should use a common test suite to ensure consistency independent of ebpf-for-windows.
This issue thus tracks the dependency, but the only work in ebpf-for-windows for this issue should be to update to a future version of dependencies once the work is done in the dependency.

**Comment by dthaler** [comment]
https://github.com/vbpf/ebpf-verifier/pull/400 adds tests to do this

**Comment by Alan-Jowett** [comment]
@dthaler Can we go ahead and close this now?

**Comment by dthaler** [comment]
> @dthaler Can we go ahead and close this now?

No, this is not done yet.  There are a series of PRs in the verifier repo, some merged, some not yet merged, some to be posted still.

**Comment by dthaler** [comment]
This is blocked on two issues:
* Fixed in https://github.com/vbpf/ebpf-verifier/pull/415
* Also the remaining issue https://github.com/vbpf/ebpf-verifier/issues/416

**Comment by dthaler** [comment]
https://github.com/microsoft/ebpf-for-windows/pull/1665 documents the findings.

**Comment by dthaler** [comment]
This is now blocked on https://github.com/vbpf/ebpf-verifier/issues/441
