### ISSUE TITLE
Add / improve tracing for ebpf-for-windows

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#1465]
### Describe the feature you'd like supported

This issue to track tracing changes which are needed for better debuggability. This includes 2 parts:

1. Identify areas / flows where any tracing is missing and add required traces.
2. Improve / enrich any existing traces if needed.

### Proposed solution

1. Identify areas / flows where any tracing is missing and add required traces.
2. Improve / enrich any existing traces if needed.

**Comment by dthaler** [comment]
- [ ] netebpfext (shankar)
- [ ] ebpfcore (dhiren)
- [ ] ebpfapi (anurag)

**Comment by dv-msft** [comment]
Created https://github.com/microsoft/ebpf-for-windows/issues/1565 to track tracing enhancements to 'ebpfcore' from the items listed above.
