### ISSUE TITLE
Broken link in DevelopmentGuide.md

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1476]
This link is broken:
https://github.com/microsoft/ebpf-for-windows/blob/0543c810a7a98699a6b6e1e30250facad96dc371/docs/DevelopmentGuide.md?plain=1#L20

**Comment by Alan-Jowett** [comment]
@dthaler  do you know what this is supposed to point to?

**Comment by dthaler** [comment]
https://github.com/openenclave/openenclave/blob/master/docs/Community/DevelopmentGuide.md has the same broken link.  I think for now we should just delete this bullet?
