### ISSUE TITLE
MSI fails to install

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1478]
### Describe the bug

Attempt to install the MSI

### Steps taken to reproduce bug

Start MSI to install. Leave default options.

### Expected behavior

Install succeeds.

### Actual outcome

Install fails. 

[install.log](https://github.com/microsoft/ebpf-for-windows/files/9824750/install.log)

```
WixQuietExec64:  WorkingDirectory is C:\Program Files\ebpf-for-windows\scripts\..
WixQuietExec64:  LogFileName is TestLog.log
WixQuietExec64:  Installing eBPF...
WixQuietExec64:   ::  OpenService FAILED 1060:
WixQuietExec64:   :: The specified service does not exist as an installed service.
WixQuietExec64:   ::  OpenService FAILED 1060:
WixQuietExec64:   :: The specified service does not exist as an installed service.
WixQuietExec64:   ::  OpenService FAILED 1060:
WixQuietExec64:   :: The specified service does not exist as an installed service.
WixQuietExec64:   ::  OpenService FAILED 1060:
WixQuietExec64:   :: The specified service does not exist as an installed service.
WixQuietExec64:   :: Element not found.
WixQuietExec64:   :: Installing NetEbpfExt...
WixQuietExec64:   ::  CreateService SUCCESS
WixQuietExec64:   :: NetEbpfExt driver created.
WixQuietExec64:   :: Installing EbpfCore...
WixQuietExec64:   ::  CreateService SUCCESS
WixQuietExec64:   :: EbpfCore driver created.
WixQuietExec64:  Failed to create eBPF user mode service.
WixQuietExec64:  At C:\Program Files\ebpf-for-windows\scripts\install_ebpf.psm1:75 char:9
WixQuietExec64:  +         throw ("Failed to create eBPF user mode service.")
WixQuietExec64:  +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec64:      + CategoryInfo          : OperationStopped: (Failed to create eBPF user mode service.:String) , RuntimeException
WixQuietExec64:      + FullyQualifiedErrorId : Failed to create eBPF user mode service.
WixQuietExec64:   
WixQuietExec64:  Error 0x80070001: Command line returned an error.
WixQuietExec64:  Error 0x80070001: QuietExec64 Failed
WixQuietExec64:  Error 0x80070001: Failed in ExecCommon method
CustomAction Install_Script returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

**Comment by saxena-anurag** [comment]
MSI installation fails only when VC redist package is not installed. Once redist package is installed, ebpf-for-windows MSI installation succeeds. 

We should probably update the documentation here ([ebpf-for-windows/InstallEbpf.md at main · microsoft/ebpf-for-windows (github.com)](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/InstallEbpf.md) to mention that VC Redist package also needs to be installed before installing ebpf MSI

**Comment by dthaler** [comment]
> We should probably update the documentation here ([ebpf-for-windows/InstallEbpf.md at main · microsoft/ebpf-for-windows (github.com)](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/InstallEbpf.md) to mention that VC Redist package also needs to be installed before installing ebpf MSI

Or update the MSI to install the redist

**Comment by dthaler** [comment]
[How to redistribute the Visual C++ Libraries with your application - C++ Team Blog (microsoft.com)](https://devblogs.microsoft.com/cppblog/how-to-redistribute-the-visual-c-libraries-with-your-application/)
	• We could create a setup.exe using instructions above
	• Do not use vcredist*.exe
[Deploy a Visual C++ application by using a setup project | Microsoft Learn](https://learn.microsoft.com/en-us/cpp/windows/walkthrough-deploying-a-visual-cpp-application-by-using-a-setup-project?view=msvc-170&viewFallbackFrom=vs-2019)
