### ISSUE TITLE
dependabot's tracking for '.gitmodules' is failing

### ISSUE THREAD

**Issue by dv-msft** [microsoft/ebpf-for-windows#1490]
### Describe the bug

```dependabot``` tracking for the ```.gitmodules``` package-ecosystem is failing as it is unable to locate branch/ref for the ```external/ubpf``` component.

I've seen this on Alan's fork as well, so this does not seem to be fork specific.  Is this a known issue or something we need take up with the ```dependabot``` folks?

### Steps taken to reproduce bug

1. Enable ```dependabot``` for the forked repo via 'github->Security->Dependabot'.  (This option is available only on forked repos).
2. Select the 'Dependabot' tab @ 'github->Insights->Dependency Graph'.
3. (OPTIONAL) - Trigger a fresh ```dependabot``` scan for ```.gitsubmodules``` (by clicking 'last checked xxx -> 'Check for updates' link)

### Expected behavior

1. No errors should be reported (No error 'red triangle' preceding the 'last checked xxx...' message-link for the ```.gitmodules``` package-ecosystem).

### Actual outcome

1. Notice the error 'red triangle' preceding the 'last checked xxx...' message-link.
2. Click the 'last checked xxx' message-link to see the message re. failure while fetching branch/ref for ```external/ubpf```.

### Additional details

Error message:

Dependabot couldn't fetch the branch/reference for external/ubpf
Your dependency file specified a branch or reference for external/ubpf, but Dependabot couldn't find it at the project's source. Has it been removed?

**Comment by dahavey** [comment]
@Alan-Jowett, please add details.
