### ISSUE TITLE
dependabot's tracking for 'pip' is failing

### ISSUE THREAD

**Issue by dv-msft** [microsoft/ebpf-for-windows#1492]
### Describe the bug

dependabot's tracking for the ```pip``` package-ecosystem is unable to locate a ```requirements.txt``` file.

I've seen this on Alan's fork as well, so this does not seem to be fork specific.  Is this a known issue or something we need take up with the ```dependabot``` folks, if we really need this?

### Steps taken to reproduce bug

1. Enable ```dependabot``` for the forked repo via 'github->Security->Dependabot'.  (This option is available only on forked repos).
2. Select the 'Dependabot' tab @ 'github->Insights->Dependency Graph'.
3. (OPTIONAL) - Trigger a ```dependabot``` scan for ```pip``` (by clicking 'last checked xxx -> 'Check for updates' link)

### Expected behavior

1. No errors should be reported (No 'red triangle' preceding the 'last checked xxx...' message-link for the ```pip``` package-ecosystem entry).

### Actual outcome

Notice the error 'red triangle' preceding the 'last checked xxx...' message-link for the ```pip``` package-ecosystem entry.
Click the 'last checked xxx' message-link to see the message re. a missing ```requirements.txt``` file.

### Additional details

NOTE: I did a quick test by specifying the path to an existing ```requirements.txt``` file which then showed a similar error for a missing ```Pipfile```.

Error message:

Dependabot couldn't find a requirements.txt
Dependabot couldn't find a requirements.txt.

Dependabot requires a requirements.txt to evaluate your Python dependencies. It had expected to find one at the path: /requirements.txt.

If this isn't a Python project, you may wish to disable updates for it in the .github/dependabot.yml config file in this repo.

**Comment by Alan-Jowett** [comment]
Fixed
