### ISSUE TITLE
Wrong switch for AddressSanitizer in cicd.yml

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1513]
https://github.com/microsoft/ebpf-for-windows/blob/6182bbb2a2e6bcc10209d2dec2a1cfbf3d0cec95/.github/workflows/cicd.yml#L171

Passing the wrong flag results in not enabling address sanitizer.

**Comment by Alan-Jowett** [comment]
Flags should be: "AddressSanitizer"

**Comment by dahavey** [comment]
@Alan-Jowett, please add more details
