### ISSUE TITLE
'port_leak.exe' demo application not being built by 'ebpf-for-windows.sln'

### ISSUE THREAD

**Issue by dv-msft** [microsoft/ebpf-for-windows#1519]
### Describe the bug

A full build/rebuild of the 'ebpf-for-windows' binaries set does not build the ```port_leak.exe``` application.

### Steps taken to reproduce bug

1. Open ```ebpf-for-windows\ebpf-for-windows.sln``` in VS19
2. Trigger a full rebuild (Ctrl+Alt+F7) and wait for it to complete.
3. Navigate to the ```ebpf-for-windows\x64\Debug``` directory and search for ```port_leak.*``` files.

### Expected behavior

The files ```port_leak.exe``` and ```port_leak.pdb``` should be listed.

### Actual outcome

Neither ```port_leak.exe``` nor ```port_leak.pdb``` are found in the ```ebpf-for-windows\x64\Debug``` directory.

### Additional details

1. Selectively building the ```port_leak``` demo application by itself builds w/o any errors.
2. This error may be present for other build flavors ('ARM64') as well but could not be verified due to a top-level 'ARM64 misconfiguration' error flagged by VS19.

**Comment by delaramamiri** [comment]
The bug is not producible. 
Using the latest windows SDK X.22000.X will use port_leak.cpp to produce the port_leak.* files.
```
4>-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
19>api_service.cpp
16>Building 'execution_context_kernel' with toolset 'WindowsKernelModeDriver10.0' and the 'Universal' target platform.
13>port_leak.cpp
```
