### ISSUE TITLE
Fix code scanning alert - Comparison of narrow type with wide type in loop condition

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1529]
Tracking issue for:
- [ ] https://github.com/microsoft/ebpf-for-windows/security/code-scanning/436

Not a threat, but should be fixed for code sanitation.

**Comment by Alan-Jowett** [comment]
https://github.com/microsoft/ebpf-for-windows/blob/3978ce4780788a7237ddc9379d34b156e113126c/libs/platform/user/ebpf_platform_user.cpp#L230-L230

**Comment by Keerthivardhan1** [comment]
what I have understood is that in loop condition 
 for (uint16_t i = 0; i < _ebpf_platform_group_to_index_map.size(); i++)
                                               i     ------>                  is narrow type 
 _ebpf_platform_group_to_index_map.size()   --->   is wide type 
is it right

**Comment by Keerthivardhan1** [comment]
I am a beginner .I would like to get involve the Microsoft Opensource

**Comment by Keerthivardhan1** [comment]
if yes hear is my idea 
I will create a variable of type    ---uint16_t
I will assign the value returned from _ebpf_platform_group_to_index_map.size() function to that  new variable.
and modify loop condition to for (uint16_t i = 0; i < new_variable; i++)
I am I correct?
sorry if I am  wrong. sir

**Comment by shankarseal** [comment]
@Keerthivardhan1 - Can you please change the index variable type from  `uint16_t i`  or `uint32_t` to `size_t`  for the following?

1. https://github.com/microsoft/ebpf-for-windows/blob/3978ce4780788a7237ddc9379d34b156e113126c/libs/platform/user/ebpf_platform_user.cpp#L230-L230 
2. https://github.com/microsoft/ebpf-for-windows/blob/b371d24603c32bef45ae7d8441a11fadf8ce83db/libs/api_common/windows_platform_common.cpp#L255
3.  https://github.com/microsoft/ebpf-for-windows/blob/b371d24603c32bef45ae7d8441a11fadf8ce83db/libs/service/api_service.cpp#L314

And for this one:
https://github.com/microsoft/ebpf-for-windows/blob/ac28f74a820bd05e9a3acaab146e7ac102566d97/tests/sample/ext/app/sample_ext_app.cpp#L102
Please make the following changes:
**sample_ext_app.cpp**
```diff
@@  -88,2  +88,2  @@
-    const char* strings[2] = {"rainy", "sunny"};
+    const char* strings[] = {"rainy", "sunny"};
-    std::vector<std::vector<char>> map_entry_buffers(2, std::vector<char>(32));
+    std::vector<std::vector<char>> map_entry_buffers(EBPF_COUNT_OF(strings), std::vector<char>(32));
@@  -102,1  +102,1  @@
-    for (uint32_t key = 0; key < map_entry_buffers.size(); key++) {
+    for (uint32_t key = 0; key < EBPF_COUNT_OF(strings); key++) {
```

I am assigning this to you.

**Comment by Keerthivardhan1** [comment]
Done sir , 
please review my PR 
When I submmited PR following was displayed 
<img width="649" alt="gti" src="https://user-images.githubusercontent.com/110013820/200561178-37601276-a556-42f2-a7ef-81d62c05571b.png">
I am a student so I replied 
@microsoft-github-policy-service agree
and It is displaying 
license/cla Queued — Contributor License Agreement is not agreed yet.

**Comment by Keerthivardhan1** [comment]
sir ..the changes that I made(with your  guidance ) are correct ?? are ok ?

**Comment by dthaler** [comment]
> sir ..the changes that I made(with your guidance ) are correct ?? are ok ?

It is correct I think but there is extra stuff in the pull request causing the tests to fail which prevent it from being merged.  See comments in PR #1594 which are waiting for you.  Can you try the actions there?

Thanks again for your help!
