### ISSUE TITLE
Merge eBPF program information types with the types in ebpf-verifer

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#153]
Merge eBPF program information types with the types in ebpf-verifer.

Currently ebpf-verifier uses C++ types that the MIDL marshaller can't handle. If we get the ebpf-verifier folks to switch to using C style types, switch to using them.

**Comment by dthaler** [comment]
Requires changes in the PREVAIL verifier project.

**Comment by dthaler** [comment]
Need to file an issue in the vbpf/ebpf-verifier project

**Comment by dthaler** [comment]
ebpf_program_types.h duplicates types in PREVAIL's helpers.hpp header for example
