### ISSUE TITLE
ebpf traces cannot be viewed in real time.

### ISSUE THREAD

**Issue by dv-msft** [microsoft/ebpf-for-windows#1537]
### Describe the bug

The [Viewing traces in real time](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/GettingStarted.md#viewing-traces-in-real-time) section of the [Getting Started](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/GettingStarted.md) document lists commands to enable and view traces in real time.

Point 2 of this section provides a command line invocation of the ```tracefmt.exe``` command to view traces in real time.
This command invocation fails as it cannot locate a ```default.tmf``` file in the current directory (if file name and location not specified on the command line). 

The 'ebpf-for-windows' distribution currently does not provide a ```.tmf``` file nor is one generated by the build process.  Apparently, ```tracefmt.exe``` cannot run without this file and thus developers have no real-time access to the traces.

### Steps taken to reproduce bug

**On the dev machine:**
1. Build the full 'ebpf-for-windows' project.
2. Deploy the 'ebpf-for-windows' bits to a test VM by running the ```.\x64\debug\deploy_ebpf.ps1 --vm <test_vm_name>``` command from the root of the 'ebpf-for-windows` repo.  This copies over the requisite epbf-for-windows binaries to the ```c:\temp``` directory on the test VM.

**On the test VM:**
3. Open an 'admin' cmd/PowerShell terminal, change to the ```c:\temp``` directory and execute the ```powershell -ExecutionPolicy Bypass .\scripts\setup-ebpf.ps1``` command to install the ebpf drivers.
4. Open another cmd/PowerShell terminal and execute ```.\tracelog -start MyTrace -guid "c:\temp\ebpf-all.guid"``` to enable tracing.
5. In the same terminal from (4) above, run the ``` .\tracefmt -rt MyTrace -displayonly -jsonMeta 0``` to dump trace messages to the console in real time.
6. In the terminal from (3) above, run the ```api_test.exe``` application.
7. After the test in (7) above exits, run ```tracelog -stop MyTrace``` in the terminal from (4) above to stop trace generation.

### Expected behavior

The ```tracefmt.exe``` command in (6) in the repro should start displaying trace messages as they are being generated.  This command should continue running until explicitly terminated by a Ctrl-C key combination.

### Actual outcome

The ```tracefmt.exe``` command invocation terminates immediately with a message about a missing ```default.tmf``` file as seen in the output below:
```
C:\wrk\vm-setup
PS > .\tracefmt -rt MyTrace -displayonly -jsonMeta 0
Setting RealTime mode for  MyTrace
Examining C:\wrk\vm-setup\default.tmf for message formats,  none found, file not found
Searching for TMF files on path: C:\wrk\vm-setup
Error processing trace entry with status=0x1069 (GetLastError=0x0)
Files Processed:
        (null)
Total Buffers Processed 0
Total Events  Processed 0
Total Events  Lost      0
Total Format  Errors    0
Total Formats Unknown   0
Elapsed Time            0 sec
+-----------------------------------------------------------------------------------+
|EventCount    EventName            EventType   TMF                                 |
+-----------------------------------------------------------------------------------+
+-----------------------------------------------------------------------------------+

Processing completed   Buffers: 0, Events: 0, EventsLost: 0 :: Format Errors: 0, Unknowns: 0

C:\wrk\vm-setup
PS >
```

**Comment by saxena-anurag** [comment]
I tried the real time tracing commands, and it seems to be working. I had to install the SDK on the test machine (using the link provided in the getting started guide) to get tracelog.exe and tracefmt.exe binaries.

**Comment by Alan-Jowett** [comment]
Please re-open with details on how to repro this if this still reproduces with the binaries from the SDK.
