### ISSUE TITLE
Support address sanitizing on all projects, post-VS2022 port

### ISSUE THREAD

**Issue by gtrevi** [microsoft/ebpf-for-windows#1563]
### Describe the bug
As per PR #1521, address sanitizing has been temporarily disabled due to compiling issues. 
This issue is to track re-enabling address sanitizing checks once the VS2022 port is complete.

### OS information
Windows 11, Visual studio 2022

### Steps taken to reproduce bug
Compiling `ebpf-for-windows.sln` on VS2022 with address sanitizing checks fails (reported to fail on VS2019 as well).

### Expected behavior
Compiling `ebpf-for-windows.sln` on VS2022 with address sanitizing checks enables succeeds.

**Comment by gtrevi** [comment]
@Alan-Jowett please assign to me, thanks!

**Comment by Alan-Jowett** [comment]
@gtrevi investigating why enabling address sanitizer fails on VS2022.

**Comment by gtrevi** [comment]
> @gtrevi investigating why enabling address sanitizer fails on VS2022.

As part of this, investigating the same issue happening on VS2019 as well.

**Comment by gtrevi** [comment]
Closed by #1521
