### ISSUE TITLE
ebpf-for-windows should serialize data passed across security boundaries

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#159]
Data that is exchanged between EC and PPL process should use serialization to enforce type safety and correctness.

Proposed serialization engines are:
1) RPC - Use [RPC serialization services ](https://docs.microsoft.com/en-us/windows/win32/rpc/serialization-services)
2) protobuf/protobuf-c - Use [ProtocolBuffer](https://github.com/protocolbuffers/protobuf) or [ProtocolBuffer for c](https://github.com/protobuf-c/protobuf-c) 

Option 1 would be preferred due to familiarity, but it looks like the public DDK can't call msrpc.sys.
Option 2 should work, but we need to use the c port for kernel mode due to lack of support for conformant C++ new in the kernel (lack of support for C++ exceptions means new returns nullptr instead of throwing std::bad_alloc).

**Comment by Alan-Jowett** [comment]
A better option might be:  [FlatCC FlatBuffers in C for C](https://github.com/dvidelabs/flatcc) as it appears to give us a way to serialize our buffers with out a dependency on C++ features we can't use from kernel.

**Comment by dthaler** [comment]
@shankarseal can you common on whether this issue was fixed by #302?

**Comment by shankarseal** [comment]
> @shankarseal can you common on whether this issue was fixed by #302?

Yes I think we can resolve this against #302 .

**Comment by dthaler** [comment]
Closing per Shankar's note above.  Please reopen if you disagree.
