### ISSUE TITLE
Various tests fail to check for failure from bpf_object__open

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1630]
Failure to check the return from bpf_object__open causes an assert when the test calls bpf_object__load

- [ ] _test_bind_fd_to_prog_array
- [ ] _array_of_maps_test
- [ ] _wrong_inner_map_types_test
- [ ] _enumerate_program_ids_test
- [ ] _array_of_maps2_test

**Comment by dthaler** [comment]
Before assuming whether object__open can or cannot return success with 0 programs, please check what libbpf does and match the answer.
