### ISSUE TITLE
Verify we support any bpf() syscalls used by cilium/ebpf

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#1640]
### Describe the feature you'd like supported

Verify whcih bpf() syscalls we support that are used by [cilium/ebpf](https://github.com/cilium/ebpf)

And which ones of those are used by L3AF

### Proposed solution

Survey what syscalls cilium/ebpf uses with the BPF() call

### Additional context

For example, https://github.com/cilium/ebpf/blob/71b98d0977c1d669c709ff6ce897e5f356d06aec/internal/sys/types.go#L716 shows it uses the BPF_MAP_CREATE syscall.

https://github.com/microsoft/ebpf-for-windows/blob/main/libs/api/bpf_syscall.cpp#L16 shows the list of syscalls we currently support, where BPF_MAP_CREATE is supported at line 26.

This task is to enumerate any calls that cilium/ebpf makes that aren't in that list, and either add support for them or create tracking issues, or reference issues if they already exist.

**Comment by delaramamiri** [comment]
created a study to investigate the list of functions that are used in Cilium versus ebpf-for-windows. Categorized the syscalls and wrappers that are used. 
[support of cilium syscalls in ebpf-for-windows.pptx](https://github.com/microsoft/ebpf-for-windows/files/10348228/support.of.cilium.syscalls.in.ebpf-for-windows.pptx)
