### ISSUE TITLE
_ebpf_pe_add_section fails to mark pe_context->result with EBPF_NO_MEMORY on allocation failure

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1649]
https://github.com/microsoft/ebpf-for-windows/blob/6ef0ecc6acf2aff5861f9c471763079b86aa0744/libs/api/ebpf_api.cpp#L2097

This results in bpf_object__open returning a partially initialized bpf_object.

**Comment by saxena-anurag** [comment]
This is likely fixed by #1616. @Alan-Jowett can you please confirm this once, I will then close this issue.

**Comment by Alan-Jowett** [comment]
Still failing, this is not fixed yet.
