### ISSUE TITLE
Error HRESULT E_FAIL has been returned from a call to a COM component.

### ISSUE THREAD

**Issue by sydbarrett74** [microsoft/ebpf-for-windows#166]
Hello,

I followed the Getting Started guide verbatim, choosing the option of building from within VS2019. I get the following errors when loading the .sln:

C:\Users\xxx\ebpf-for-windows\libs\execution_context\unit\execution_context_unit_test.vcxproj : error  : Error HRESULT E_FAIL has been returned from a call to a COM component.

C:\Users\xxx\ebpf-for-windows\libs\platform\unit\platform_unit_test.vcxproj : error  : Error HRESULT E_FAIL has been returned from a call to a COM component.

Please advise.

**Comment by sydbarrett74** [comment]
I have quite a few...
![Screenshot 2021-05-11 214828](https://user-images.githubusercontent.com/6467403/117906620-427f8980-b2a3-11eb-9c4f-5a4270eeda3e.png)
![Screenshot 2021-05-11 214907](https://user-images.githubusercontent.com/6467403/117906635-49a69780-b2a3-11eb-948c-baf578ef527c.png)
![Screenshot 2021-05-11 214941](https://user-images.githubusercontent.com/6467403/117906639-4ca18800-b2a3-11eb-8cdf-13116f53e2ca.png)
![Screenshot 2021-05-11 215034](https://user-images.githubusercontent.com/6467403/117906645-50350f00-b2a3-11eb-9c10-c9803be1ec83.png)
![Screenshot 2021-05-11 215100](https://user-images.githubusercontent.com/6467403/117906651-532fff80-b2a3-11eb-9fd1-c577478909ac.png)
![Screenshot 2021-05-11 215124](https://user-images.githubusercontent.com/6467403/117906653-562af000-b2a3-11eb-88a9-3be4305226d7.png)
![Screenshot 2021-05-11 215153](https://user-images.githubusercontent.com/6467403/117906657-588d4a00-b2a3-11eb-84ba-7511950448df.png)
![Screenshot 2021-05-11 215208](https://user-images.githubusercontent.com/6467403/117906665-5b883a80-b2a3-11eb-9288-1914090c7fff.png)

**Comment by Alan-Jowett** [comment]
That's quite a few.

Any chance you could try this with them disabled? If that works, maybe start adding them back until you can isolate which one is breaking? Once you have that I can try installing it and digging further.

**Comment by dthaler** [comment]
@sydbarrett74 any chance you can provide more info before next week Monday's triage meeting?  Would love to track this down.  Thanks!

**Comment by sydbarrett74** [comment]
Sorry, have been slammed. I'll try and work on this over the weekend.

**Comment by dthaler** [comment]
@sydbarrett74 Any update?   Maybe others can help try to repro this as well?

**Comment by dthaler** [comment]
@sydbarrett74 Closing since we don't have a repro.  Please reopen this issue if you still have a repro and can provide more info.
