### ISSUE TITLE
Adding support for Multipath TCP

### ISSUE THREAD

**Issue by ohault** [microsoft/ebpf-for-windows#170]
More information on https://pluginized-protocols.org/tcp/

**Comment by dthaler** [comment]
@ohault is the ask to have a hook exposed by an MP-TCP implementation, or for someone to implement MP-TCP in an eBPF program, or something else?

**Comment by dthaler** [comment]
@ohault We don't have enough information here to know the details of the ask.  Please add more details of what is being requested and then please reopen this issue.  Thanks!

**Comment by ohault** [comment]
Indeed, there are two parts for the implementation of this feature :

- In one side, there is the core question about making the Windows TCP stack more extensible with eBPF and this point is far wider that the support of Mutipath TCP (see https://inl.info.ucl.ac.be/system/files/tcp-ebpf.pdf ). According to me, this is something at the heart of ebpf-for-windows to bring a symmetry with TCP-BPF implementation in Linux kernel starting at version 4.13 and later ( see https://netdevconf.info/2.2/papers/brakmo-tcpbpf-talk.pdf)
AFIAK, in the ebpf-for-windows architecture, this point is directly related to eBPF Shim for hooks/helpers (netebpfext.sys) and could require updates in TCP/IP stack (tcpip.sys) and/or Layer 2 Network Driver Subsystem (ndis.sys).

- On the other side, there are the plugins running eBPF bytecode and Multipath TCP could become one such plugin in the future. In follow-up to https://pluginized-protocols.org/tcp/ , a first start could be supporting the implementation of new TCP options like the Timestamps option described in RFC1323 still not supported by Windows TCP/IP stack.
