### ISSUE TITLE
Improve LRU performance using generational LRU

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1721]
Proposed algorithm for LRU.

1) The LRU map maintains N generational buckets. Each generation represents keys of a common age, with lower generation count interpreted as older keys. 
2) Periodically, the following checks are made:
a) Is the oldest generation empty?
b) Does the current generation have more than 1/N of the total number of entries in the map?
c) If true, roll over to the next generation.
3) When a key is accessed, move the key to the current generation.
4) When the map is full, start evicting keys from the oldest generation, moving forward until a key is found.

**Comment by dthaler** [comment]
FYI, see https://patchwork.kernel.org/project/netdevbpf/patch/20221103204330.3257910-1-joe@isovalent.com/ for some documentation about LRU maps.

**Comment by Alan-Jowett** [comment]
This borrows from the concepts described in this article [The multi-generational LRU](https://lwn.net/Articles/851184/)
