### ISSUE TITLE
LRU hash-map should handle concurrent _reap_oldest_map_entry and ebpf_hash_table_update

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1741]
A LRU map that is performing an insert into the hash-table will call _reap_oldest_map_entry to remove the oldest entry.

This can succeed, but the subsequent insert can still fail with EBPF_OUT_OF_SPACE.

This can occur in the following sequence (assuming threads T1 and T2):
1) T1: ebpf_hash_table_update - Gets back EBPF_OUT_OF_SPACE
2) T1: _reap_oldest_map_entry - Deletes oldest entry and returns success.
3) T2:  ebpf_hash_table_update - Gets back success and uses the space freed in step 2.
4) T1: ebpf_hash_table_update - Gets back EBPF_OUT_OF_SPACE

There needs to be a strategy to deal with this case.

**Comment by dthaler** [comment]
My recommendation is to allow an atomic reap-and-insert so that step 2 and step 4 both happen under the same lock.
