### ISSUE TITLE
Update documentation for fuzz testing

### ISSUE THREAD

**Issue by delaramamiri** [microsoft/ebpf-for-windows#1758]
Documentation for fuzz tasting is outdated and doesn't include instructions on how to debug using the crash files:
https://github.com/microsoft/ebpf-for-windows/blob/main/docs/Fuzzing.md

**Comment by delaramamiri** [comment]
fuzzing documentation doesn't include steps to reproduce the crashes using the artifacts. This PR updates the doc and set an example to better help developers.

Documentation
fuzzing.md is updated.

**Comment by Alan-Jowett** [comment]
Fixed by #1790
