### ISSUE TITLE
Auto-update of branch prevents CI/CD from running

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1769]
This commit:
https://github.com/microsoft/ebpf-for-windows/pull/1763/commits/17e1dc4c2bf9aa4da21183e30875681855bb17f6

Did not trigger a CI/CD run. This appears to only occurs from [autoupdate](https://github.com/microsoft/ebpf-for-windows/actions/workflows/autoupdate.yaml) workflow.

**Comment by Alan-Jowett** [comment]
Looks like this is a known issue:
https://github.com/peter-evans/create-pull-request/issues/48
https://github.com/orgs/community/discussions/35047

**Comment by Alan-Jowett** [comment]
Needs more investigation.

**Comment by dthaler** [comment]
See workarounds at https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

**Comment by dthaler** [comment]
> Use a [GitHub App to generate a token](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens) that can be used with this action. GitHub App generated tokens are more secure than using a PAT because GitHub App access permissions can be set with finer granularity and are scoped to only repositories where the App is installed. This method will trigger both `on: push` and `on: pull_request` workflows.

**Comment by dthaler** [comment]
Merge queue support obsoletes the need for the autoupdate workflow, which should be removed once the merge queue is working.
