### ISSUE TITLE
Build failure while building the 'bpf_conformance' package.

### ISSUE THREAD

**Issue by dv-msft** [microsoft/ebpf-for-windows#1786]
### Describe the bug

The ```ebpf-for-windows\external\bpf_conformance``` package fails to build when using the VS2022 build enviroment.

### OS information

Edition: Windows 11 Enterprise
Version: 22H2
OS build:	22623.1037
Experience: Windows Feature Experience Pack 1000.22638.1000.0

### Steps taken to reproduce bug

(Assumes installation of VS2022 build environment, per the 'GettingStarted.md' document).

1. cd to ```ebpf-for-windows\external\bpf_conformance``` directory.
2. Per instructions in the ```README.md``` at this location, run the commands ```cmake -S . -B build``` followed by ```cmake --build build``` to build the required ```bpf_conformance_runner.exe``` binary.

### Expected behavior

The build should succeed, and the ```bpf_conformance_runner.exe``` binary should be present in the ```ebpf-for-windows\x64\debug``` directory.

### Actual outcome

The ```cmake --build build``` command terminates with this linker error:

```
Generating Code...
  bpf_conformance.vcxproj -> D:\wrk\ebpf-for-windows\external\bpf_conformance\build\lib\Debug\bpf_conformance.lib
  Building Custom Rule D:/wrk/ebpf-for-windows/external/bpf_conformance/src/CMakeLists.txt
  runner.cc
LINK : fatal error LNK1104: cannot open file 'libboost_program_options-vc143-mt-gd-x64-1_80.lib' [D:\wrk\ebpf-for-windows\external\bpf_conformance\build\src\bpf_conformance_runner.vcxproj]
```

 
### Additional details

As a work-around, the ```bpf_conformance_runner.exe``` executable can be downloaded from [this](https://github.com/Alan-Jowett/bpf_conformance/releases/download/v0.0.3/bpf_conformance_runner.exe) location.

**Comment by Alan-Jowett** [comment]
Fixed:
https://github.com/Alan-Jowett/bpf_conformance/actions/runs/3833008149/jobs/6523985313
