### ISSUE TITLE
Fuzzers can't find __msan_scoped_disable_interceptor_checks

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#1817]
### Describe the bug

When following the GettingStarted.md instructions, the fuzzers built locally fail with the error:
```
ERROR: Function "__msan_scoped_disable_interceptor_checks" not defined.
```

Workaround is mentioned in comment in issue #1756.

Gianni and I discussed creating new configurations (not just Debug) that use address sanitizer.

### Steps taken to reproduce bug

See above.

### Expected behavior

All executables that are built should be executable.

### Actual outcome

Fuzzers give error and don't do anything.

**Comment by dthaler** [comment]
This is also related to issue #1815

**Comment by Alan-Jowett** [comment]
Suggestion is to document the steps to build the fuzzer.

**Comment by gtrevi** [comment]
Internal issue opened to the VS Team (blocking implementation through configurations) -> under investigation.

**Comment by dthaler** [comment]
Blocked on https://github.com/vbpf/ebpf-verifier/pull/482
