### ISSUE TITLE
Support for atomic instructions in bpf2c

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1819]
### Describe the feature you'd like supported

The BPF ISA defines a set of [atomic instructions](https://github.com/dthaler/ebpf-docs/blob/update/isa/kernel.org/instruction-set.rst#152atomic-operations). For parity we should support these in bpf2c.

### Proposed solution

Implement the atomic instructions.

**Comment by dthaler** [comment]
Good to support, but not needed until we also have verifier support for such instructions.

**Comment by Alan-Jowett** [comment]
@dv-msft please also create an issue in the verifier repo to track this.

**Comment by b1tg** [comment]
Is this already being developing or not, if not I would like to try it. I have read some BPF ISA stuff before while implementing an ebpf emulator[1] so I think I have the basic background knowledge to do this.

[1]: https://github.com/b1tg/ebpf-emu

**Comment by dv-msft** [comment]
> Is this already being developing or not, if not I would like to try it. I have read some BPF ISA stuff before while implementing an ebpf emulator[1](https://github.com/b1tg/ebpf-emu) so I think I have the basic background knowledge to do this.

@b1tg : You can certainly take this on :-) We also have a weekly [zoom meeting](https://github.com/microsoft/ebpf-for-windows/discussions/427) (every Monday) that you're welcome to join.  There's one coming up on 01/23/2022 and hope to see you there!
