### ISSUE TITLE
Replace dawidd6/action-download-artifact with actions/download-artifact

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#1837]
### Describe the bug

Currently we use two different github actions to download artifacts across our workflows:

> ossar-scan.yml:      uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
> reusable-build.yml:      uses: dawidd6/action-download-artifact@e6e25ac3a2b93187502a8be1ef9e9603afc34925
> reusable-cmake-build.yml:      uses: dawidd6/action-download-artifact@e6e25ac3a2b93187502a8be1ef9e9603afc34925
> reusable-test.yml:      uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7

We should make them all just use actions/download-artifact.

### Steps taken to reproduce bug

cd .github/workflows
findstr download *

### Expected behavior

Should just use actions/download-artifact

### Actual outcome

Half the workflows use one action, and half use the other action

**Comment by saxena-anurag** [comment]
https://github.com/dawidd6/action-download-artifact/commit/e6e25ac3a2b93187502a8be1ef9e9603afc34925 is to download artifacts across repositories (from demo repository in this case). At that time, https://github.com/actions/download-artifact/commit/9782bd6a9848b53b110e712e20e42d89988822b7 did not support downloading artifacts from a different repository.

**Comment by Alan-Jowett** [comment]
Note:
https://github.com/actions/download-artifact/issues/172 is already tracking adding the support to the official actions/download-artifact.
