### ISSUE TITLE
Platform abstraction layer for kernel mode needs tests in CI/CD

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#184]
Platform abstraction layer for kernel mode needs tests in CI/CD

Currently we only test the user mode PAL.

**Comment by Alan-Jowett** [comment]
Needs investigation:
Does the GitHub CI/CD pipeline permit loading unsigned drivers?

**Comment by dthaler** [comment]
Duplicate of #141
