### ISSUE TITLE
bpf prog run can cause DPC timeouts

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1844]
### Describe the bug

Slow BPF program with very large repeat count.
bpftool prog run id 196610 data_in data_in.txt data_out data_out.txt repeat 100000

Due to running at dispatch, the DPC timeout will eventually fire.

### Steps taken to reproduce bug

bpftool prog run id 196610 data_in data_in.txt data_out data_out.txt repeat 2147483647

### Expected behavior

Machine doesn't bug check.

### Actual outcome

DPC timeout.

### Additional details

When running BPF programs at DISPATCH IRQL, the worker thread should periodically drop down too passive to allow other DPCs to run.

**Comment by dthaler** [comment]
In my opinion, each iteration should separately raise to DISPATCH.  One should not run multiple iterations within the same DPC timeout
