### ISSUE TITLE
ebpf_program accesses information stored in the NMR provider with out protection

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1850]
Code in ebpf_program.c accesses data from the NMR program information provider without any form of protection. It currently sets a flag when the provider detaches, but this is not sufficient as there is still a race condition between accessing the NMR provider data and unload of the driver hosting this provider information.

**Comment by dthaler** [comment]
I don't understand what the issue is here, can you elaborate?  Drivers that follow the NMR API contract shouldn't have race conditions.

**Comment by dthaler** [comment]
Discussion: https://learn.microsoft.com/en-us/windows-hardware/drivers/network/detaching-a-provider-module-from-a-client-module explains how to use the NMR contract.  As discussed there, the provider is responsible for tracking when all using threads are complete and calling detach complete when done.

The Windows https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/run-down-protection on the other hand does not support that semantics but instead only supports a blocking call to wait until threads are complete.  It could be used though the impedence mismatch does make it a poor match for using with NMR recommendations.
