### ISSUE TITLE
```netebpfext/user/fwp_um.cpp``` has member functions that hold locks for potentially unbounded time.

### ISSUE THREAD

**Issue by dv-msft** [microsoft/ebpf-for-windows#1898]
### Describe the bug

The ```_fwp_engine::test_bind_ipv4()``` method calls ```test_out()``` with the ```_fwp_engine::lock``` held. This function seems to do a lot of possibly un-bounded work (call other functions) and we need to determine if all that needs to be done under lock. 
The current approach also raises also the potential for an (indirect) deadlock in some subsequent code-path(s).

(One solution could be to make the locks more granular using ```{ ... }``` scoping thus avoid holding locks across calls)

If the locks are absolutely needed across calls, we should add a SAL ```_Requires_lock_held_``` annotation to the functions called while holding locks.

There are other instances of this pattern in the file that would need similar modifications as well.

### Steps taken to reproduce bug

N/A (Found via Code review)

### Expected behavior

N/A

### Actual outcome

N/A

**Comment by dthaler** [comment]
To me this seems a minor optimization.  This is in user-mode tests that just use locks to serialize its own threads.  Fine to do, but seems relatively low priority compared to other issues.  Maybe a good first issue though.
