### ISSUE TITLE
Ebpf Netsh should provide option to unpin a program

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#190]
Ebpf Netsh should provide option to unpin a program

**Comment by dthaler** [comment]
this is the "set program" command, but implementing it requires an API to look up what name a filename/section is pinned to, which is blocked on issue #81

**Comment by dthaler** [comment]
For comparison there is apparently no "unpin" at https://www.mankier.com/8/bpftool-prog but perhaps unpin could be done by unlinking the file in the filesystem

**Comment by dthaler** [comment]
Currently the netsh helper help text suggests a command:
```
netsh ebpf set program [filename=]<string> [section=]<string> [[pinned=]<string>]
```

Pinning currently works by:
1) iterate through loaded programs until a match is found on the filename and section
2) call `ebpf_api_pin_object()` on the program handle (which can be replaced with libbpf's `bpf_obj_pin()` once work on fd's is done)

There is no libbpf `bpf_obj_unpin()`, however.  Given a path, one can unpin in Linux via unlink().
Libbpf has the following other APIs related to unpinning programs:

```
LIBBPF_API int bpf_program__unpin(struct bpf_program *prog, const char *path);
LIBBPF_API int bpf_program__unpin_instance(struct bpf_program *prog, const char *path, int instance);
LIBBPF_API int bpf_object__unpin_programs(struct bpf_object *obj, const char *path);
```

**Comment by dthaler** [comment]
Looks like `ebpf_api_unpin_object()` is the equivalent of unlink and should be usable if it works.

**Comment by saxena-anurag** [comment]
API doc has the following APIs for unpin:

```
ebpf_program_unpin
ebpf_map_unpin
ebpf_object_unpin
```

**Comment by dthaler** [comment]
Now blocked on #373
