### ISSUE TITLE
Ebpf Netsh should provide option to detach program from hook

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#191]
Ebpf Netsh should provide option to detach program from hook

**Comment by dthaler** [comment]
Blocked on issue #81

**Comment by dthaler** [comment]
For comparison, see "bpftool prog detach" at https://www.mankier.com/8/bpftool-prog

**Comment by dthaler** [comment]
And bpftool sources are at https://elixir.bootlin.com/linux/latest/source/tools/bpf/bpftool/main.c

**Comment by dthaler** [comment]
PR #352 should hopefully unblock this

**Comment by dthaler** [comment]
Now blocked on #372

**Comment by dthaler** [comment]
bpftool supports this with
```
bpftool prog detach PROG ATTACH_TYPE [MAP]
```

PR #482 adds the `bpf_link_detach` API to detach by link fd.  bpftool allows specifying link, map, and prog by id and then calls bpf_{link,map,prog}_get_fd_by_id to get the fd.
So if the user can get a link ID a netsh command could be done with the following libbpf APIs:
* link_fd = bpf_link_get_fd_by_id(link_id)
* bpf_link_detach(link_fd)

And bpftool enumerates all link IDs via the `bpf_link_get_next_id` libbpf API.

**Comment by dthaler** [comment]
Support for IDs is blocked in #396
