### ISSUE TITLE
Ebpf Netsh API should be able to get max instruction count about an eBPF program

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#193]
Ebpf Netsh API should be able to get stats about an eBPF program

A developer must be able to get statistics (e.g., size, max instruction count, etc.) about an eBPF program without running it.

**Comment by dthaler** [comment]
Many statistics are already available about eBPF programs without running it (e.g., size, etc.), which can be seen via
`netsh ebpf show sections bindmonitor.o level=verbose` for instance.

max instruction count is not yet visible, hence the rename of the issue.

**Comment by dthaler** [comment]
https://github.com/vbpf/ebpf-verifier/pull/232 tracks exposing the info from the verifier.
