### ISSUE TITLE
libfuzzer.h should not pull in fuzzer libraries

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#1934]
Regular dev build that does not need /Fuzzer should succeed without needing additional VS components such as address sanitizer. Since libfuzzer.h does `#pragma comment(lib, "libsancov.lib")` - that pulls in new dependencies that are not present unless "C++ AddressSanitizer" component is installed in VS.

This #prgama should be removed and all binaries that require the fuzzer libraries should include `$(SanitizerLibs)` in the `<Link>` section of vcxproj files.

**Comment by gtrevi** [comment]
This goes in pair with #1815

**Comment by gtrevi** [comment]
The docs now underscore to install the ASAN component (installed as default). This can be considered as the workaround in the meanwhile.
