### ISSUE TITLE
Remove ebpf_extension wrapper

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2021]
The ebpf_extension wrapper incorrectly masks parts of the NMR contract and results in incorrect behavior in the clients and providers. Now that there exists a user mode mock of NMR, there is no justification for this layer.

**Comment by Alan-Jowett** [comment]
The ebpf_extension wrapper makes it hard to correctly implement the NMR contract in the program and link code.

**Comment by dthaler** [comment]
@Alan-Jowett if you're taking this, can you remove the "help wanted" label?  or do you want help?
