### ISSUE TITLE
Add test coverage for WFP callout

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/ebpf-for-windows#2028]
### Describe the feature you'd like supported

Add test coverage for the WFP callout implementing the XDP hook.

### Proposed solution

- Add coverage of XDP_TX case
- Add coverage of various NMR + WFP/NDIS binding race conditions / failure modes
- Add coverage of "attach program" and "delete program" on a system with non-idle network traffic

### Additional context

We've hit several serious bugs by simply attempting to `attach program` and `detach program` at the XDP layer on a system with a fairly high rate of RX traffic.

**Comment by shankarseal** [comment]
Closing this issue as:

- Add coverage of XDP_TX case : **coverage exists**
- Add coverage of various NMR + WFP/NDIS binding race conditions / failure modes : ** covered by #2097 , #2099 and #2150 **
- Add coverage of "attach program" and "delete program" on a system with non-idle network traffic : ** covered by #2097 , #2099 and #2150 **
