### ISSUE TITLE
Make IOCTL call to fetch program context for a program type

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#205]
Currently get_program_type_windows() queries a local list of program types to get the program context. This should change to make ioctl call to EC to get the program context.

**Comment by dthaler** [comment]
Is this a duplicate of #67?

**Comment by dthaler** [comment]
Please close if a duplicate of #67.

**Comment by dthaler** [comment]
Verified duplicate since #223 tracks registry issue
