### ISSUE TITLE
_net_ebpf_sock_addr_get_program_context should not be saved in a global variable

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#2056]
### Describe the bug

Currently, when netebpfext registers a program info provider, and ebpfcore attaches to it, ebpfcore provides a client dispatch function to be able to get the context of the current program invocation. Netebpfext saves this function pointer in a global and not in a client context, as it is not possible to fetch a client context in the context of helper function invocation. netebpfext clears this function pointer when the client detaches.
If ebpfcore attaches with the same provider multiple times, and one of the client detaches, it is possible for this pointer to be NULL.

Proposed solution:
1. Abstract the `ebpf_state` logic in ebpfcore into a lib so it can be used in netebpfext also.
2. Have a similar logic in netebpfext which will save the context before invoking the ebpf program.
3. When a helper function is invoked which needs to get the context, it will use this saved state in netebpfext to get the context instead of calling ebpfcore supplied client dispatch function

### Steps taken to reproduce bug

netepbfext hits a bugcheck while calling client dispatch function.

### Expected behavior

No bugcheck

### Actual outcome

We hit a bugcheck due to null pointer dereference.

**Comment by shankarseal** [comment]
`_net_ebpf_sock_addr_get_program_context` is no longer in the src code.
