### ISSUE TITLE
Enable merge queue to improve code velocity

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2076]
What:
https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

How:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

**Comment by dthaler** [comment]
Temporarily removed BinSkim and license/cla as Required checks (can still manually require them before clicking merge) since they don't seem to be working on the merge queue.
