### ISSUE TITLE
rpc_interface.idl contains a duplicate of EbpfMapDescriptor 

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#208]
rpc_interface.idl currently has a duplicate definition of EbpfMapDescriptor. EbpfMapDescriptor is defined in spec_type_descriptors.hpp and that header file includes "vector" and "string". So spec_type_descriptors.hpp cannot be directly included in the IDL file.

**Comment by dthaler** [comment]
Is this a duplicate of #153?
