### ISSUE TITLE
Support for map batch operations

### ISSUE THREAD

**Issue by H0mTanks** [microsoft/ebpf-for-windows#2080]
### Describe the feature you'd like supported

Provide implementation for the following:
`BPF_MAP_LOOKUP_BATCH`
`BPF_MAP_UPDATE_BATCH`
`BPF_MAP_DELETE_BATCH`

along with the libbpf apis:
`bpf_map_delete_batch`
`bpf_map_lookup_batch`
`bpf_map_lookup_and_delete_batch`
`bpf_map_update_batch`

### Proposed solution

At the moment, maps can only be accessed on a per-element basis. 

Unsure if each map access translates to a syscall or not. If so, support for these functions would reduce map usage overhead.

This would also improve coverage of existing eBPF features and help increase the amount of compatible programs.

**Comment by dahavey** [comment]
@Alan-Jowett, are you actively working on this?

**Comment by dthaler** [comment]
@shankarseal  can you assign this one as appropriate?
