### ISSUE TITLE
Missing EbpfApi.dll symbols in ebpfapi.pdb symbol file

### ISSUE THREAD

**Issue by shpalani** [microsoft/ebpf-for-windows#2160]
[Issue-2160.docx](https://github.com/microsoft/ebpf-for-windows/files/10887251/Issue-2160.docx)
### Describe the bug

**Request:**
For ebpfapi.exe, the symbol file for EbpfApi.dll is needed.
   1. EbpfApi.dll  <<< not present
   2. EbpfApi.lib  <<< present.

Trigger: 
WPA reports that the symbol file EbpfApi.dll is missing.

**Root Cause Analysis:**
```
In Product.wxs,
<!-- Define the product's <Runtime> components -->
...
			<Component Id="EBPFAPI.DLL" DiskId="1" Guid="{C44E4B08-901E-4B71-8FD1-F0B3D11D063F}">
				**<File Id="EBPFAPI.DLL" Name="EbpfApi.dll" Source="$(var.EbpfApi.TargetDir)EbpfApi.dll**" />
			</Component>
			<Component Id="EBPFAPI.PDB" DiskId="1" Guid="{6912E957-E682-41CB-9C53-1D0B886528F7}">
				**<File Id="EBPFAPI.PDB" Name="EbpfApi.pdb" Source="$(var.EbpfApi.TargetDir)EbpfApi.pdb" />**
			</Component>
			...
<!-- Define the product's <Development> components -->
		<ComponentGroup Id="eBPF_Development_libs" Directory="dir_lib">
			<Component Id="eBPFApi_lib" Guid="{A164197B-3C57-4ECA-B138-CBF558DA4401}">
				**<File Id="EbpfApi.lib" Name="EbpfApi.lib" DiskId="1" Source="$(var.api.TargetDir)EbpfApi.lib" />**
			</Component>
			<Component Id="eBPFApi_lib_pdb" Guid="{197589BB-4A27-4313-9A70-BB455A58C987}">
				**<File Id="eBPFApi_lib.pdb" Name="EbpfApi.pdb" DiskId="1" Source="$(var.api.TargetDir)EbpfApi.pdb" />**
			</Component>
		</ComponentGroup>
```
The **reason** for this PDB mismatch/missing is 
-  EbpfApi.dll in EbpfApi.pdb is getting overwritten with EbpfApi.lib's EbpfApi.pdb

### Steps taken to reproduce bug

1. Capture the WPR traces with .wprp CPU profiling
2. Load the etl file in WPA. Configure the symbol file paths in WPA.
3. Navigate the stack flow for the netsh service, which will invoke EbpfApi.dll calls.

 

### Expected behavior

The EbpfApi.dll symbol file should be loaded.

### Actual outcome

No crash. WPA is an external tool.

**Comment by shpalani** [comment]
Still not seeing the EbpfApi.dll symbols in EbpfApi.pdb. 
This PR only removes the EbpfApi.pdb generated in the \lib directory in Product.wxs. Hence reopening the case.

**Comment by gtrevi** [comment]
@shpalani the Product.wsx was not related to your issue, therefore not the "root cause" as you mention, please redact the desctiption.

**Comment by shpalani** [comment]
In Release 0.7.0, I'm able to see the EbpfApi.dll symbols loaded in WPA CPU profiling.
