### ISSUE TITLE
ebpf program native code should be RO during execution

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#217]
As discussed at https://docs.cilium.io/en/v1.8/bpf/ and elsewhere:

> BPF locks the entire BPF interpreter image (struct bpf_prog) as well as the JIT compiled image (struct bpf_binary_header) in the kernel as read-only during the program’s lifetime in order to prevent the code from potential corruptions. Any corruption happening at that point, for example, due to some kernel bugs will result in a general protection fault and thus crash the kernel instead of allowing the corruption to happen silently.

We need to make sure ebpf-for-windows similarly locks the image to be read-only during the eBPF program's lifetime.

**Comment by dthaler** [comment]
Same must be true for bytecode used by the interpreter

**Comment by Alan-Jowett** [comment]
To protect byte code we need to change uBPF:
https://github.com/iovisor/ubpf/issues/76

**Comment by Alan-Jowett** [comment]
First PR was prep work for fix.
