### ISSUE TITLE
.msi Installer fails when installing development files only

### ISSUE THREAD

**Issue by H0mTanks** [microsoft/ebpf-for-windows#2187]
### Describe the bug

The `0.7.0` release fails with the following error when trying to install only the `Development files`.
Issue is present on `0.6.0` as well.

![image](https://user-images.githubusercontent.com/59693193/224905204-df9aeebc-555c-4d1e-a282-e6462e1bfa41.png)

Installer works on the Test Mode VM if `Runtime components` are also installed. (Correct Behaviour)

Happens both on my VM which has Test Mode enabled, and on the development machine without Test Mode.

I believe wanting to run the `.msi` on the development machine for just the development files is a common enough use case for the installer to work on non test-signed machines as well. Although this might not be a needed fix because at some point with the `1.0.0` release, I presume that all the installer features would work on non Test-signed machines as well.

### OS information

1) Windows 11 Enterprise VM
Hyper-V Manager
Test-signed

2) Windows 11 Pro
Non Test-signed development machine.

### Steps taken to reproduce bug

1. Run the `.msi installer`.
2. In the features selection page, set Runtime Components to `Feature will be installed when required` (btw no `Entire Feature will be unavailable` option for `Runtime Components`?
3. Set `Development Components` to `Will be installed on the local hard drive`.
4. Proceed with installation.

### Expected behavior

Installation should succeed in providing just the Development files.

Currently it only succeeds if `Runtime Components` are also installed.

### Actual outcome

Installation fails with the following error:

![image](https://user-images.githubusercontent.com/59693193/224905204-df9aeebc-555c-4d1e-a282-e6462e1bfa41.png)

**Comment by gtrevi** [comment]
@H0mTanks This is by design.

The runtime components are mandatory, as documented [here](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/InstallEbpf.md):

```
The following feature-components are available for customization, and must be assigned as comma-separated values to the ADDLOCAL parameter:

- eBPF_Runtime_Components (mandatory): runtime components (installed in [Installation folder]\*, [Installation folder]\drivers).
- eBPF_Runtime_Components_JIT (optional): JIT compiler service (installed in [Installation folder]\JIT).
- eBPF_Development (optional): header files, scripts and libraries for development (installed in [Installation folder]\include,[Installation folder]\lib,[Installation folder]\scripts).
- eBPF_Testing (optional): header files for development (installed in [Installation folder]\testing).
```
