### ISSUE TITLE
Add test that validates the include/dev files from both internal repo and external projects.

### ISSUE THREAD

**Issue by gtrevi** [microsoft/ebpf-for-windows#2194]
### Describe the feature you'd like supported

As of #2186, include files from external projects are cherry-picked for ensuring license compliance.

On the other side, in order to actually ensure new legit files are added, a script should enumerate all files of interest within the external projects, and ensure that they match what is being delivered, with eventual exception handling (for a list of intentionally excluded files).

Same thing should be checked in the MSI, with the addition of the internal `\include\` directory, since by design the MSI handles each file as a fully independent component.

### Proposed solution

On the CI/CD pipeline, add a script step that parses the nuget and the MSI packages and checks for any mismatch for the following paths, including exception handling for a list of intentionally excluded files (full path):

- `\include\**\*.*`
- `\external\bpftool\libbpf\src\**\*.h`

**Comment by shankarseal** [comment]
This will be addressed by #3046 .
