### ISSUE TITLE
Ebpfcore needs to guard against/account for cpu affinity changes from user mode.

### ISSUE THREAD

**Issue by dv-msft** [microsoft/ebpf-for-windows#2260]
### Describe the bug

The thread affinities set by Ebpfcore can be changed by user mode applications unbeknownst to ebpfcore.  This can cause issues in the epoch handling logic which (currently) makes certain assumptions about thread affinities being constant, while in an epoch.

### Steps taken to reproduce bug

N/A - Identified as a 'drive-by' issue while investigating another bug.

### Expected behavior

The epoch logic should be resilient to such unforseen affinity changes.

### Actual outcome

This can cause a kernel crash.

**Comment by dthaler** [comment]
See https://lwn.net/Articles/825415
