### ISSUE TITLE
Getting MSB8040: Spectre-mitigated libraries are required for this project, but I have installed the lib

### ISSUE THREAD

**Issue by lianghaoGao** [microsoft/ebpf-for-windows#227]
I have installed MSVC v142 - VS 2019 C++ x64/x86 Spectre-mitigated libs (v14.28)" as an Individual component in the VS installer but still getting "MSB8040: Spectre-mitigated libraries are required for this project" error.

![image](https://user-images.githubusercontent.com/84546191/119600598-3663f380-bd9c-11eb-8082-830471db2f72.png)

Also I double checked under Project Property -> C/C++ -> Code Generation -> Spectre Mitigation is set to “Enabled (/Qspectre)”.

**Comment by Alan-Jowett** [comment]
Can you please make sure you have the version of spectre libraries that match your toolchain? I ended up installing all spectre related packages to make sure I had the right one. 

![image](https://user-images.githubusercontent.com/20480683/119852203-51358580-becc-11eb-985c-a3a2e69483e8.png)

**Comment by lianghaoGao** [comment]
Thanks Alan. I installed all spectre related packages and it worked.
