### ISSUE TITLE
The WFP connect redirect callout should set `FWPS_CONNECT_REQUEST::redirectContext` with original destination

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#2303]
The WFP connect redirect callout in sock_addr hook should set the original destination in the `FWPS_CONNECT_REQUEST::redirectContext`. User mode proxy could then query the [socket option](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/sio-query-wfp-connection-redirect-context) to get the original destination address. In addiition to the original destination IP address; it should also store 64-bit [`FWPS_METADATA_FIELD_TRANSPORT_ENDPOINT_HANDLE`](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/metadata-fields-at-each-filtering-layer). The data structure for the custom redirect context should be defined in `ebpf_nethooks.h`.

**Comment by saxena-anurag** [comment]
@shankarseal How will proxy app use the transport endpoint handle provided in the redirect context?

**Comment by saxena-anurag** [comment]
Probably a SOCK_ADDR specific helper function should be exposed so that eBPF program can set a custom redirect context, which will then be read by the proxy app using the WFP IOCTLs.

**Comment by dthaler** [comment]
> Probably a SOCK_ADDR specific helper function should be exposed so that eBPF program can set a custom redirect context, which will then be read by the proxy app using the WFP IOCTLs.

Insufficient justification to add a new helper function.  Need explanation of why we would diverge from Linux, i.e., use the existing socket cookie helper function.

**Comment by matthewige** [comment]
The proposal of using an existing Linux function such as the socket cookie helper functions would not work as the proxy application needs the ability to retrieve the socket cookie, and it has no way of doing this.
