### ISSUE TITLE
Remove global lock on invoke path when performing tail calls

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2314]
The tail call path currently acquires and releases a global lock (_ebpf_object_tracking_list_lock) twice during a tail call:
1) During the bpf_tail_call helper (to grab a reference on the object)
2) After the tail call completes (to release the reference on the object).

Given that program and map objects are protected by epoch logic, it should be possible to do this without needing to grab a reference to the object.

**Comment by saxena-anurag** [comment]
Alternatively, we can also use per-object lock, and a "deleting" state, which will remove need to acquire global locks for each acquire / release of ref:

**Acquire ref**:
1. Call interlockedIncrement

**Release ref**:
1. Acquire object lock
1. Call InterlockedDecrement
2. If ref is 0 ==> mark object as "deleting"
3. Release object lock
4. Delete object from hash table.

**Query hash table:**
1. Acquire table lock and find object using the key
2. Acquire object lock
3. If object is "deleting", return NOT FOUND
4. Else, acquire reference on the object.
5. Release object lock
6. Release table lock
