### ISSUE TITLE
Test batch begin/invoke/end routines via NPI dispatch tables

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#2331]
Currently batch APIs are not tested via NPI dispatch tables. We should add tests for these using the sample ext driver.

Created per comment in #2329

**Comment by saxena-anurag** [comment]
Maybe also update netebpfext to invoke batch APIs for XDP hook.

**Comment by mtfriesen** [comment]
The routines and the NPI contract also need to be documented.
