### ISSUE TITLE
Fuzzer build randomly fails in CI/CD

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2349]
![image](https://user-images.githubusercontent.com/20480683/232874396-04904cc3-0b0f-496b-84ca-132391112a1d.png)

Appears to be caused by running bpf2c with address sanitizer.

**Comment by shpalani** [comment]
To debug, picked the 
1. Good Build-x64-FuzzerDebug from https://github.com/microsoft/ebpf-for-windows/actions/runs/4814385428?pr=2380
2. Crashdump from https://github.com/microsoft/ebpf-for-windows/actions/runs/4813266565

There were 2 Crash dumps, which showed the same call stack. The symbols can be mismatched/wrong.
- bpf2c.exe.6692.dmp
- bpf2c.exe.2936.dmp

************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\Users\shpalan\Downloads\Build-x64-FuzzerDebug\build-FuzzerDebug\FuzzerDebug
0:000> k
 # Child-SP          RetAddr               Call Site
00 00000057`9e2fc3e8 00007fff`140a1e88     ntdll!NtWaitForMultipleObjects+0x14
01 00000057`9e2fc3f0 00007fff`140a145e     ntdll!WerReportExceptionWorker+0x568
02 00000057`9e2fc470 00007fff`140a0c1b     ntdll!RtlReportExceptionEx+0x80e
03 00000057`9e2fc540 00007fff`140c4014     ntdll!RtlReportException+0x9b
04 00000057`9e2fc5c0 00007ffe`df21eb5e     ntdll!RtlIsZeroMemory+0x154
05 00000057`9e2fc5f0 00007fff`140643af     ucrtbased!_C_specific_handler+0x16e
06 00000057`9e2fc6a0 00007fff`13ff170e     ntdll!_chkstk+0x12f
07 00000057`9e2fc6d0 00007fff`1400f2c3     ntdll!RtlVirtualUnwind2+0x35e
08 00000057`9e2fce10 00007fff`140c3fd9     ntdll!RtlRaiseException+0x163
09 00000057`9e2fdc30 00007fff`140c3fa3     ntdll!RtlIsZeroMemory+0x119
0a 00000057`9e2fdc80 00007fff`140ccdaa     ntdll!RtlIsZeroMemory+0xe3
0b 00000057`9e2fdd70 00007fff`140cd08a     ntdll!_misaligned_access+0x41a
0c 00000057`9e2fdda0 00007fff`140d7709     ntdll!_misaligned_access+0x6fa
0d 00000057`9e2fddd0 00007fff`1406a6d3     ntdll!_misaligned_access+0xad79
0e 00000057`9e2fde00 00007fff`13fd4dc9     ntdll!memset+0x4593
0f 00000057`9e2fde50 00007fff`13fd7a6a     ntdll!RtlTryEnterCriticalSection+0xde9
10 00000057`9e2fde90 00007fff`13fdb550     ntdll!RtlEnterCriticalSection+0x5ea
11 00000057`9e2fdff0 00007fff`13fda8c1     ntdll!RtlGetCurrentServiceSessionId+0xbf0
12 00000057`9e2fe0b0 00007ffe`da1907d9     ntdll!RtlFreeHeap+0x51
13 00000057`9e2fe0f0 00007fff`1402994a     clang_rt_asan_dbg_dynamic_x86_64!_asan_wrap_GlobalSize+0x4d7bd
14 00000057`9e2ff220 00007fff`14029879     ntdll!RtlRealSuccessor+0x18a
15 00000057`9e2ff250 00007fff`140298b8     ntdll!RtlRealSuccessor+0xb9
16 00000057`9e2ff280 00007fff`140298b8     ntdll!RtlRealSuccessor+0xf8
17 00000057`9e2ff2b0 00007fff`140298b8     ntdll!RtlRealSuccessor+0xf8
18 00000057`9e2ff2e0 00007fff`140979f9     ntdll!RtlRealSuccessor+0xf8
19 00000057`9e2ff310 00007fff`14037b28     ntdll!LdrInitShimEngineDynamic+0x3319
1a 00000057`9e2ff6e0 00007fff`1405d94d     ntdll!LdrInitializeThunk+0x208
1b 00000057`9e2ff760 00007fff`1403792e     ntdll!LdrStandardizeSystemPath+0x23d
1c 00000057`9e2ff9e0 00000000`00000000     ntdll!LdrInitializeThunk+0xe

From analyze -v
FILE_IN_CAB:  bpf2c.exe.6692.dmp

CONTEXT:  (.ecxr)
rax=00007fff13feeabe rbx=00000000c0000374 rcx=00007ffedf5222b1
rdx=000000579e2fd430 rsi=0000000000000001 rdi=00007fff14131810
rip=00007fff140c3fd9 rsp=000000579e2fdc30 rbp=000001654daec5c0
 r8=000000579e2fd490  r9=0000000000000000 r10=000000579e2fd478
r11=0000000000000000 r12=0000000000000001 r13=0000000000000000
r14=0000000000000010 r15=000001654daf12e0
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000202
ntdll!RtlIsZeroMemory+0x119:
00007fff`140c3fd9 eb00            jmp     ntdll!RtlIsZeroMemory+0x11b (00007fff`140c3fdb)
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007fff140c3fd9 (ntdll!RtlIsZeroMemory+0x0000000000000119)
   ExceptionCode: c0000374
  ExceptionFlags: 00000081
NumberParameters: 1
   Parameter[0]: 00007fff14131810

---
From bpf2c.exe.2936.dmp

0:000> k
 # Child-SP          RetAddr               Call Site
00 00000092`5b2fbd98 00007fff`140a1e88     ntdll!NtWaitForMultipleObjects+0x14
01 00000092`5b2fbda0 00007fff`140a145e     ntdll!WerReportExceptionWorker+0x568
02 00000092`5b2fbe20 00007fff`140a0c1b     ntdll!RtlReportExceptionEx+0x80e
03 00000092`5b2fbef0 00007fff`140c4014     ntdll!RtlReportException+0x9b
04 00000092`5b2fbf70 00007ffe`df21eb5e     ntdll!RtlIsZeroMemory+0x154
05 00000092`5b2fbfa0 00007fff`140643af     ucrtbased!_C_specific_handler+0x16e
06 00000092`5b2fc050 00007fff`13ff170e     ntdll!_chkstk+0x12f
07 00000092`5b2fc080 00007fff`1400f2c3     ntdll!RtlVirtualUnwind2+0x35e
08 00000092`5b2fc7c0 00007fff`140c3fd9     ntdll!RtlRaiseException+0x163
09 00000092`5b2fd5e0 00007fff`140c3fa3     ntdll!RtlIsZeroMemory+0x119
0a 00000092`5b2fd630 00007fff`140ccdaa     ntdll!RtlIsZeroMemory+0xe3
0b 00000092`5b2fd720 00007fff`140cd08a     ntdll!_misaligned_access+0x41a
0c 00000092`5b2fd750 00007fff`140d7709     ntdll!_misaligned_access+0x6fa
0d 00000092`5b2fd780 00007fff`1406a6d3     ntdll!_misaligned_access+0xad79
0e 00000092`5b2fd7b0 00007fff`13fd4dc9     ntdll!memset+0x4593
0f 00000092`5b2fd800 00007fff`13fd7a6a     ntdll!RtlTryEnterCriticalSection+0xde9
10 00000092`5b2fd840 00007fff`13fdb550     ntdll!RtlEnterCriticalSection+0x5ea
11 00000092`5b2fd9a0 00007fff`13fda8c1     ntdll!RtlGetCurrentServiceSessionId+0xbf0
12 00000092`5b2fda60 00007ffe`da1907d9     ntdll!RtlFreeHeap+0x51
13 00000092`5b2fdaa0 00007fff`1402994a     clang_rt_asan_dbg_dynamic_x86_64!_asan_wrap_GlobalSize+0x4d7bd
14 00000092`5b2febd0 00007fff`14029879     ntdll!RtlRealSuccessor+0x18a
15 00000092`5b2fec00 00007fff`140298b8     ntdll!RtlRealSuccessor+0xb9
16 00000092`5b2fec30 00007fff`140298b8     ntdll!RtlRealSuccessor+0xf8
17 00000092`5b2fec60 00007fff`140298b8     ntdll!RtlRealSuccessor+0xf8
18 00000092`5b2fec90 00007fff`140979f9     ntdll!RtlRealSuccessor+0xf8
19 00000092`5b2fecc0 00007fff`14037b28     ntdll!LdrInitShimEngineDynamic+0x3319
1a 00000092`5b2ff090 00007fff`1405d94d     ntdll!LdrInitializeThunk+0x208
1b 00000092`5b2ff110 00007fff`1403792e     ntdll!LdrStandardizeSystemPath+0x23d
1c 00000092`5b2ff390 00000000`00000000     ntdll!LdrInitializeThunk+0xe

**Comment by shpalani** [comment]
Got a CI/CD run which failed FuzzerDebug build:
https://github.com/microsoft/ebpf-for-windows/actions/runs/4833124330
