### ISSUE TITLE
eBPF binary version metadata is inconsistent 

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/ebpf-for-windows#2350]
### Describe the bug

eBPF binaries are stamped with inconsistent version metadata: some fields (file and product version strings) are [dynamically](https://github.com/microsoft/ebpf-for-windows/blob/f64dd9c15c2f9ad6c259fd08e7f25a5366e1bd7c/resource/ebpf_resource.rc#L68-L73) set, but logically equivalent fields (file and product version numbers) are [hard-coded](https://github.com/microsoft/ebpf-for-windows/blob/f64dd9c15c2f9ad6c259fd08e7f25a5366e1bd7c/resource/ebpf_resource.rc#L50-L52).

The hard-coded version numbers cause pain with tools that rely on accurate version metadata, such as the internal AzWatson portal:
![image](https://user-images.githubusercontent.com/3517159/232887134-5f9bfa8e-b2eb-4f8d-8e55-53c41e1c52fb.png)

The right-click info is also inconsistent - Windows displays the file version integer but the product version string:

![image](https://user-images.githubusercontent.com/3517159/232888162-add69ab0-4052-4883-9a51-23bd21b294a2.png)

eBPF binaries should report (as near as possible) the same version number in string and integer forms.

### OS information

N/A.

### Steps taken to reproduce bug

Query ebpfcore.sys or ebpfapi.dll file version number, e.g. using Windows file info dialog or the output of internal AzWatson portal.

### Expected behavior

The binary version metadata should be as consistent as possible, and also uniquely identify an official release. If possible, file versions should match product versions should match eBPF versions.

### Actual outcome

Some versions are `0.0.0.1` and others match the eBPF project version.

### Additional details

The copyright date is also hard-coded.

**Comment by Alan-Jowett** [comment]
Is there any easy way to get the file description during AzWatson? The file description includes the git commit id that generated the files.

**Comment by mtfriesen** [comment]
> Is there any easy way to get the file description during AzWatson? The file description includes the git commit id that generated the files.

We might be able to retrieve that from AzWatson via the debugger interactively. If we want it to show up in the dump metadata, I expect we'd have to make a feature request.

> Can you link a document (MSDN page?) that says they should be the same?

I'm not aware of any requirement - components can probably use these fields however they wish. Do we have a reason to prefer `0.0.0.1` to accurate version numbers?

**Comment by mtfriesen** [comment]
I've confirmed we can interactively query the version from AzWaton interactively:

```
0:008> lmDvmebpfapi
Browse full module list
start             end                 module name
00007ffb`0b280000 00007ffb`0b3a0000   EbpfApi    (deferred)             
    Image path: C:\ebpf\EbpfApi.dll
    Image name: EbpfApi.dll
    Browse all global symbols  functions  data
    Timestamp:        Sun Apr  9 07:52:39 2023 (64326EC7)
    CheckSum:         00000000
    ImageSize:        00120000
    File version:     0.0.0.1
    Product version:  0.0.0.1
    File flags:       0 (Mask 3F)
    File OS:          40004 NT Win32
    File type:        2.0 Dll
    File date:        00000000.00000000
    Translations:     0409.04b0
    Information from resource tables:
        CompanyName:      Microsoft
        ProductName:      eBPF for Windows
        InternalName:     ebpfapi.dll
        OriginalFilename: ebpfapi.dll
        ProductVersion:   0.8.0
        FileVersion:      0.8.0
        FileDescription:  eBPF For Windows User API e03f2fee2165da46c8c5c3a6405951561900f5ec
        LegalCopyright:   Copyright (C) 2022
```
