### ISSUE TITLE
Inconsistency between PREVAIL verifier and uBPF

### ISSUE THREAD

**Issue by tobashi** [microsoft/ebpf-for-windows#2362]
Through fuzzing we have generated the following eBPF program and respective bytecode, pointing to an inconsistency in how PREVAIL or uBPF handles load instructions:

`mov64 r0, 0x0`
`and64 r0, 0x5d3f6d75`
`mov64 r1, r0`
`mov64 r3, 0x33345ddc`
`lddw r0, 0x68123b3f68123b3f`
`exit`

`b700 0000 0000 0000`
`5700 0000 756d 3f5d`
`bf01 0000 0000 0000`
`b703 0000 dc5d 3433`
`1800 0000 3f3b 1268`
`1800 0000 3f3b 1268`
`9500 0000 0000 0000`

PREVAIL verifies this eBPF program as being correct, however when executing the eBPF program in uBPF an error occurs: Incomplete load instruction at PC

**Comment by Alan-Jowett** [comment]
Thanks for reporting this. I will take a look.

**Comment by tobashi** [comment]
We create an ELF file with a .text section that contains the generated eBPF program.
We use `./ebpf-verifier/check data.o` to verify the ELF file/eBPF program and `./ubpf/vm/test -j data.o` to execute.

Here is an example of a data.o file for which uBPF returns "Failed to load code: incomplete lddw at PC 4":

`7f45 4c46 0201 0100 0000 0000 0000 0000`
`0100 f700 0100 0000 0000 0000 0000 0000`
`0000 0000 0000 0000 0001 0000 0000 0000`
`0000 0000 4000 3800 0000 4000 0500 0100`
`b700 0000 0000 0000 0700 0000 7c5a a266`
`a700 0000 dae8 6e49 8700 0000 21f5 9553`
`1805 5822 6390 7075 1805 5822 6390 7075`
`3705 0000 83d3 5000 9500 0000 0000 0000`
`002e 7374 7274 6162 002e 7379 6d74 6162`
`006f 626a 2d66 696c 6573 2f64 6174 612e`
`6f00 2e74 6578 7400 2e6e 6f74 652e 474e`
`552d 7374 6163 6b00 0000 0000 0000 0000`
`0000 0000 0000 0000 0000 0000 0000 0000`
`1100 0000 0400 f1ff 0000 0000 0000 0000`
`0000 0000 0000 0000 0000 0000 0300 0300`
`0000 0000 0000 0000 0000 0000 0000 0000`
`0000 0000 0000 0000 0000 0000 0000 0000`
`0000 0000 0000 0000 0000 0000 0000 0000`
`0000 0000 0000 0000 0000 0000 0000 0000`
`0000 0000 0000 0000 0000 0000 0000 0000`
`0100 0000 0300 0000 0000 0000 0000 0000`
`0000 0000 0000 0000 8000 0000 0000 0000`
`3800 0000 0000 0000 0000 0000 0000 0000`
`0100 0000 0000 0000 0000 0000 0000 0000`
`0900 0000 0200 0000 0000 0000 0000 0000`
`0000 0000 0000 0000 b800 0000 0000 0000`
`4800 0000 0000 0000 0100 0000 0300 0000`
`0800 0000 0000 0000 1800 0000 0000 0000`
`2200 0000 0100 0000 0600 0000 0000 0000`
`0000 0000 0000 0000 4000 0000 0000 0000`
`4000 0000 0000 0000 0000 0000 0000 0000`
`1000 0000 0000 0000 0000 0000 0000 0000`
`2800 0000 0100 0000 0000 0000 0000 0000`
`0000 0000 0000 0000 0000 0000 0000 0000`
`0000 0000 0000 0000 0000 0000 0000 0000`
`0100 0000 0000 0000 0000 0000 0000 0000`

**Comment by Alan-Jowett** [comment]
LLVM seems to think this is an invalid instruction sequence, suggesting that this a prevail issue.
```
alanjo@alanjo-dev:~/ubpf$ llvm-objdump -Sl test.o

test.o: file format elf64-bpf

Disassembly of section .text:

0000000000000000 <.text>:
       0:       b7 00 00 00 00 00 00 00 r0 = 0
       1:       07 00 00 00 7c 5a a2 66 r0 += 1721916028
       2:       a7 00 00 00 da e8 6e 49 r0 ^= 1232005338
       3:       87 00 00 00 21 f5 95 53 r0 = -r0
       4:       18 05 58 22 63 90 70 75 <unknown>
       5:       18 05 58 22 63 90 70 75 <unknown>
       6:       37 05 00 00 83 d3 50 00 r5 /= 5297027
       7:       95 00 00 00 00 00 00 00 exit
```

**Comment by Alan-Jowett** [comment]
As per:
https://datatracker.ietf.org/doc/draft-thaler-bpf-isa/

Unused fields are supposed to be zero, which makes this an invalid sequence that prevail should probably reject.
```

   As discussed below in 64-bit immediate instructions (Section 5.3), a
   64-bit immediate instruction uses a 64-bit immediate value that is
   constructed as follows.  The 64 bits following the basic instruction
   contain a pseudo instruction using the same format but with opcode,
   dst_reg, src_reg, and offset all set to zero, and imm containing the
   high 32 bits of the immediate value.

   This is depicted in the following figure:

           basic_instruction
     .-----------------------------.
     |                             |
     code:8 regs:8 offset:16 imm:32 unused:32 imm:32
                                    |              |
                                    '--------------'
                                   pseudo instruction

   Thus the 64-bit immediate value is constructed as follows:

   |  imm64 = (next_imm << 32) | imm

   where 'next_imm' refers to the imm value of the pseudo instruction
   following the basic instruction.  The unused bytes in the pseudo
   instruction are reserved and shall be cleared to zero.
```

**Comment by Alan-Jowett** [comment]
Note:
Issues related to uBPF should be filed here: https://github.com/iovisor/ubpf/issues. Resolving this as it's the wrong repo.

Also, uBPF behavior appears to be conformant, so resolving this issue in favor of https://github.com/vbpf/ebpf-verifier/issues/484
