### ISSUE TITLE
NetEbpfExt should check ebpf_program_type_t prior to allowing a program to attach

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#239]
NetEbpfExt should check ebpf_program_type_t before allowing a program to attach.

Failure to check this permits attaching an XDP program to a BIND attach point, resulting in a bugcheck.

**Comment by Alan-Jowett** [comment]
EC should pass ebpf_program_type_t in the eBPF client data in addition to the hook-specific context data.

**Comment by dthaler** [comment]
Extension could register program type and ebpfcore.sys can only look at extensions with a compatible program type for a given eBPF program
