### ISSUE TITLE
Add Azure pipeline yml to GitHub repo

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#2390]
This issue is to add the Azure pipeline yml to the GitHub repo. This will ensure whenever a release branch is forked from `main`, the release branch automatically has the yml files, and pipeline can run on the forked branch.

Otherwise, whenever a release branch is forked, we need to manually add the Azure pipeline yml to the release branch.

**Comment by shankarseal** [comment]
provide details and we will re-visit in next triage meeting.
