### ISSUE TITLE
EbpfNetsh code should have CI/CD tests

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#240]
EbpfNetsh code should have tests that run in CI/CD pipeline, preferably able to run on the development machine (i.e. no need for real driver loaded/running).

**Comment by dthaler** [comment]
Need to figure out how to test stdout output from catch framework.  Is there an example somewhere?

**Comment by dthaler** [comment]
https://stackoverflow.com/questions/4191089/how-to-unit-test-function-writing-to-stdout-stdcout may be useful information
