### ISSUE TITLE
Tune `ebpf_tracing.cmd` to use the least amount of CPU.

### ISSUE THREAD

**Issue by gtrevi** [microsoft/ebpf-for-windows#2429]
Given that the compressing operation on the `wfpstate.xml` file can cause some CPU spikes, this operation should be delegated to an external log-collector job (which should in turn run with CPU-limitation).

Therefore, the tracing script should be reverted to its initial behavior, to regards of handling the WFP rundown file, that is, not compressing the `wfpstate.xml` file before moving it to the `.\committed` folder, and in turn, its max size check should be raised to account for the final compression ratio.

**Comment by dthaler** [comment]
Please add requested info above, to this issue before closing.  Thanks!

**Comment by gtrevi** [comment]
> Please add requested info above, to this issue before closing. Thanks!

Please let's sync offline, thanks
