### ISSUE TITLE
Add ETW tracing in ebpf UM components.

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#247]
Add tracing (preferably TraceLogging?) in ebpf user mode components.

**Comment by dthaler** [comment]
Closely related to issue #137 which is tracing from EC.   Should be merge them or track them separately?

**Comment by dthaler** [comment]
@chgray Any feedback on this one?

**Comment by dthaler** [comment]
Merging with #137 as a duplicate for now.
