### ISSUE TITLE
Remove duplicate copy of boost 1.81

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#2471]
### Describe the bug

PREVAIL depends on boost 1.81 and results in one install.
Then ebpf-for-windows installs a second copy.
Boost 1.81 is very large and this results in double the disk space usage and download time contributing to build time.

### Steps taken to reproduce bug

Clone and build.

### Expected behavior

Clone and build should result in only one copy of boost 1.81.

### Actual outcome

Clone and build results in two copies of boost 1.81.

**Comment by dthaler** [comment]
Blocked on #2465

**Comment by Alan-Jowett** [comment]
Taking a stab at fixing this.
