### ISSUE TITLE
ebpf_stress_tests_km failing over 1min and 8min intervals

### ISSUE THREAD

**Issue by rectified95** [microsoft/ebpf-for-windows#2477]
`.\ebpf_stress_tests_km -tt=32 -td=1` - failure in `jit_load_attach_detach_unload_random_v4_test`
![km_stress_1min](https://github.com/microsoft/ebpf-for-windows/assets/12816515/8644733e-c67c-4117-a8fc-34752136781f)

`.\ebpf_stress_tests_km -tt=32 -td=8` - failure with `abort()` at `stress_tests_km.cpp`@723

![km_stress_8min](https://github.com/microsoft/ebpf-for-windows/assets/12816515/e1b0204b-0439-4ada-9cc2-1e654bc69d47)

**Comment by dahavey** [comment]
@dv-msft, please reach out to @rectified95 to get more details.

**Comment by dv-msft** [comment]
@rectified95: Could you please attach traces?  The instructions are available [here](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/GettingStarted.md#capturing-traces).

**Comment by dv-msft** [comment]
Closing as 'No-Repro':
1. No traces available
2. Local, multi-hour runs have not repro'd this issue.

If seen again, please re-open with traces attached.
