### ISSUE TITLE
[unit_test.exe] failures in end_to_end.cpp

### ISSUE THREAD

**Issue by rectified95** [microsoft/ebpf-for-windows#2478]
### Describe the bug

Seeing three failures in the unit test suite, details in section below.

### Steps taken to reproduce bug

Run .\unit_test.exe

### Expected behavior

Test should not fail.

### Actual outcome

-------------------------------------------------------------------------------
bad_map_name-native
-------------------------------------------------------------------------------
D:\ebpf-for-windows\tests\end_to_end\end_to_end.cpp(988)
...............................................................................

D:\ebpf-for-windows\tests\end_to_end\end_to_end.cpp(566): FAILED:
  REQUIRE( result == -22 )
with expansion:
  -2 == -22

-------------------------------------------------------------------------------
verify bad1.o
-------------------------------------------------------------------------------
D:\ebpf-for-windows\tests\end_to_end\end_to_end.cpp(1066)
...............................................................................

D:\ebpf-for-windows\tests\end_to_end\end_to_end.cpp(1062): FAILED:
  REQUIRE( (error_message != nullptr && std::string(error_message) == expected_error_message) )
with expansion:
  false

-------------------------------------------------------------------------------
verify bad2.o
-------------------------------------------------------------------------------
D:\ebpf-for-windows\tests\end_to_end\end_to_end.cpp(1073)
...............................................................................

D:\ebpf-for-windows\tests\end_to_end\end_to_end.cpp(1062): FAILED:
  REQUIRE( (error_message != nullptr && std::string(error_message) == expected_error_message) )
with expansion:
  false

**Comment by dahavey** [comment]
@rectified95 need more details. Will reach out.

**Comment by saxena-anurag** [comment]
@rectified95 can you share more details about the failures. These tests run in CICD everyday.

**Comment by saxena-anurag** [comment]
@rectified95 if this issue is resolved, is it ok to close this issue?

**Comment by rectified95** [comment]
@saxena-anurag Looks like this was a one-off if the CI has been passing, so this is ok to close.
