### ISSUE TITLE
Add mutual auth for RPC client / server.

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#249]
RPC client and server should authenticate each other, to ensure:

Only admin client makes a call to ebpfsvc.
Client is talking only to ebpfsvc.

**Comment by dthaler** [comment]
@saxena-anurag can you edit the description of this issue to provide more details (at least a sentence or two)?

**Comment by saxena-anurag** [comment]
RPC client and server should authenticate each other, to ensure:
1. Only admin client makes a call to ebpfsvc.
2. Client is talking only to ebpfsvc.
