### ISSUE TITLE
deploy-ebpf.ps1 doesn't deploy redist

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#2533]
### Describe the bug

After using the deploy method at 
https://github.com/microsoft/ebpf-for-windows/blob/main/docs/InstallEbpf.md#method-2-install-files-you-built-yourself

Running unit_tests.exe fails missing MSVCP140D_ATOMIC_WAIT.dll

### Steps taken to reproduce bug

Follow the instructions at 
https://github.com/microsoft/ebpf-for-windows/blob/main/docs/InstallEbpf.md#method-2-install-files-you-built-yourself

Run unit_tests.exe in the VM.

### Expected behavior

unit_tests.exe passes

### Actual outcome

unit_tests.exe fails

**Comment by dthaler** [comment]
@gtrevi can you take a look?

**Comment by dahavey** [comment]
Fixing #2422 will also fix this bug.
