### ISSUE TITLE
On board api test to azure pipeline 

### ISSUE THREAD

**Issue by delaramamiri** [microsoft/ebpf-for-windows#2535]
To achieve scalability and eliminate the need for GitHub runners in API testing, It is necessary to transfer CI/CD Kernel Tests from GitHub runners to Azure Pipeline.
1. builds the project and uploads the resulting artifacts. 
2. supports different build configurations, such as Debug and Release, 
3. steps for restoring NuGet packages, creating project files, 
4. building the solution,
6. downloading a demo repository, and 
7. uploading the build output. It also 
8. handles the publishing of MSI and NuGet packages based on specified conditions.
In the test yml file:
1.  creates a generated artifact folder.
2. starts ETW tracing if specified.
3. configures the eBPF store and installs eBPF components.
4. installs regression components.
5. runs the test with code coverage in Visual Studio Developer Command Shell if specified.
6. runs the test with code coverage and low resource simulation if specified.
7. runs the test with/without code coverage if specified.
8. checks for crash dumps and uploads them if specified.
9. on board api_test 
10.  Create an automatic pipeline to consume the yml file from Github to trigger during the schedule, and PR to the main branch.

**Comment by dahavey** [comment]
No longer needed.
