### ISSUE TITLE
Visual Studio builds fail on github

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#2538]
### Describe the bug

Scheduled run failed:
https://github.com/microsoft/ebpf-for-windows/actions/runs/5149210014/jobs/9271934842

Same for other PRs trying to build.

The "Create verifier project" fails with error:
```
CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_C_COMPILER:

    C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933/bin/HostX64/x64/cl.exe

  is not a full path to an existing compiler tool.

```

https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md says 

<html>
<body>

Name | Version | Path
-- | -- | --
Visual Studio Enterprise 2022 | 17.6.33712.159 | C:\Program Files\Microsoft Visual Studio\2022\Enterprise

</body>
</html>

...
<html>
<body>

Microsoft.Component.MSBuild | 17.6.33605.316
-- | --

</body>
</html>

https://github.com/microsoft/ebpf-for-windows/actions/runs/5149210014/jobs/9271935728 says:

MSBuild version 17.5.1+f6fdcf537 for .NET Framework

and
```
 17>ClCompile:
         C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\CL.exe /c /I"D:\a\ebpf-for-windows\ebpf-for-windows\libs\execution_context" /I"D:\a\ebpf-for-windows\ebpf-for-windo...
```
in the regular/build step that succeeded, so 14.34.31933 was found.

but the analyze/build step of the same run reports that
```
C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933/bin/HostX64/x64/cl.exe

  is not a full path to an existing compiler tool.
```

### Steps taken to reproduce bug

Normal github CI/CD

### Expected behavior

CI/CD passes

### Actual outcome

CI/CD fails

### Additional details

Perhaps a problem with github itself?

**Comment by shpalani** [comment]
Also observed in https://github.com/microsoft/ebpf-for-windows/actions/runs/5161688391/jobs/9299147216
