### ISSUE TITLE
ebpfsvc should be localservice

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#257]
Currently ebpfsvc starts as localsystem. It should instead be running with less privileges as localservice.

**Comment by dthaler** [comment]
@saxena-anurag why was PR #258 abandoned?  are you looking at a different approach?

**Comment by saxena-anurag** [comment]
When ebpfsvc is running as LocalService, it is not able to open device handle to ebpfcore (failed with ERROR_ACCESS_DENIED).
Need to investigate that.
