### ISSUE TITLE
Factor the usersim code into a separate repository

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#2586]
### Describe the feature you'd like supported

Allow the usersim code to be used by other projects, not just ebpf-for-windows

### Proposed solution

Move the appropriate code into a separate github repository
Include that repository as a submodule

Some candidate code includes:
* libs\platform\user\kernel_um.{cpp,h}
* libs\platform\user\nmr_um.cpp
* libs\platform\user\nmr_impl.{cpp,h}
* libs\platform\user\ebpf_fault_injection.{cpp,h}
* libs\platform\user\ebpf_leak_detector.{cpp,h}
* netebpfext\user\fwp_um.cpp
* netebpfext\user\fwp_um.h
* netebpfext\user\ndis_um.cpp

**Comment by saxena-anurag** [comment]
One question -- Since these are tightly coupled with any code changes done in ebpf-for-windows repo (e.g.: a code change is calling a new kernel API, whose mock also then needs to be added in the user sim files), what will be the workflow when a code change needs to be done in these files?

**Comment by dthaler** [comment]
> One question -- Since these are tightly coupled with any code changes done in ebpf-for-windows repo (e.g.: a code change is calling a new kernel API, whose mock also then needs to be added in the user sim files), what will be the workflow when such a code change needs to be done?

Same as for ubpf, prevail, and bpf_conformance today.
