### ISSUE TITLE
README refers to XDP hook instead of NDIS hook

### ISSUE THREAD

**Issue by pravb** [microsoft/ebpf-for-windows#260]
"eBPF programs installed into the kernel-mode execution context can attach to various hooks (currently two hooks so far: XDP and a socket bind hook) and call various helper APIs exposed by the eBPF shim, which internally wraps public Windows kernel APIs, allowing the use of eBPF on existing versions of Windows. More hooks and helpers will be added over time."

Worth clarifying that the current hook is an NDIS hook. We don't have a proper XDP hook yet.

**Comment by dthaler** [comment]
Agree it should be renamed for now (not just in the documentation)

**Comment by dthaler** [comment]
Suggest making a new attach type, but not a new program type, so hook prototype and set of legal helpers remains the same.

**Comment by dthaler** [comment]
This is related to issue #125
