### ISSUE TITLE
Remove `bpf2c.exe` from the `redist-package` project.

### ISSUE THREAD

**Issue by gtrevi** [microsoft/ebpf-for-windows#2623]
The `redist-package` project should just contain the CLI `bpftool.exe` utility.

**Comment by saxena-anurag** [comment]
@gtrevi is bpf2c.exe not needed by the customer for converting .o file to .sys file?

**Comment by dthaler** [comment]
> @gtrevi is bpf2c.exe not needed by the customer for converting .o file to .sys file?

It's needed in the MSI, but not in the redist, which my understanding is for things that are needed on the runtime machine.
