### ISSUE TITLE
Support for attaching different eBPF programs at EBPF_ATTACH_TYPE_CGROUP_INET*_CONNECT for the same compartment

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#2626]
### Describe the feature you'd like supported

This issue is to add support for attaching more than one eBPF programs to EBPF_ATTACH_TYPE_CGROUP_INET{4|6}_CONNECT attach hook per compartment. Currently it supports attaching only one eBPF program per compartment.

### Proposed solution

1. Add support for attaching multiple eBPF programs.
2. The eBPF programs should be invoked in a chain, order of invocation being the order in which they were attached.
3. netebpfext should then return the action based on the cumulative verdict of all the programs invoked.

**Comment by saxena-anurag** [comment]
@saxena-anurag see if there is a similar solution present in Linux.

**Comment by saxena-anurag** [comment]
Specifically for `CONNECT{4|6}`, the following logic can be used to support attach of multiple programs to the same compartment (this still needs _some_ support to specify priorities to manage ordering).

SOCK_ADDR hook today allows either a wildcard bind, or a specific bind. If doing specific binds, SOCK_ADDR hook already supports multiple attaches, as long as they are in different compartments.

In the new approach, following can be  expected flow for SOCK_ADDR
1. SOCK_ADDR will still allow _either_ wildcard bind, _or_ a specific bind.
2. For each specific bind in the same compartment, netebpfext will add a WFP filter. The filter will have weight which will be derived from **some** priority (_TBD_).
3. As each filter will have different weights, WFP will automatically take care of invoking the callout in that order.

**Comment by shankarseal** [comment]
Assigning this to @rectified95 .

**Comment by rectified95** [comment]
@saxena-anurag / @shankarseal Can the programs be invoked in the order they were attached or should we allow users to influence that? Here are some considerations for the decision:
 
**A) invoke in the order attached** 
  - consistent for 1 user
  - if 2 user apps, or 2 eBPF runtimes 
    Desired invocation order might not match attach order, if apps start in the same order or when indeterministic
    - _for our scenario, cloud VM services start in fixed order - does it match the desired program invocation order?_
    
**B) change attach API to specify order**
  - if users agree on order: can agree weight values; even so if 3rd user/program is introduced, we might need to re-assign old weight, if it needs to be inserted in between the old ones.
  - if users disagree about invocation order - not an eBPF problem, need to agree their scenarios if running on one host
  - if specified non-unique weight by accident: how can user find out what weight other programs are attached with?
    - could expose the weight to bpftool/netsh ebpf
  -  if no order specified by user then auto-generate
      - Ensure these random weights aren't greater than user-specified ones:
      Specify  FWP_UINT8 - top 4 bits of UINT64, WFP generates bottom 60. 
      https://learn.microsoft.com/en-us/windows/win32/fwp/filter-weight-assignment
      Make non-specified weights always use some value from the from 0-15 range, **lower than** the range we assign to user-specified weights.
      - Should non-modifying programs run always before or after modifying ones?

**Comment by dthaler** [comment]
As Anurag noted above, there are existing solutions for this, for other hooks first but we would want the same ideally for all hooks, hence implemented generically if possible.

* https://github.com/xdp-project/xdp-tools/blob/master/lib/libxdp/protocol.org is the spec for XDP support
* https://github.com/l3af-project/l3af-arch/blob/main/discussions/chaining_enhancements.md discusses L3AF's proposed support

Point being we should not diverge from already deployed practice without a very good reason and even then we would want to try to _also_ support the Linux API.

**Comment by saxena-anurag** [comment]
@dthaler @rectified95 I have added some details about the 2 possible solutions (and an interim solution to meet our current requirement, while we implement the more generic solution) in https://github.com/microsoft/ebpf-for-windows/discussions/3456

**Comment by rectified95** [comment]
Based on the discussion linked above, due to business need, the short-term solution will be scoped to just the sock_addr hook, and use attachment order as priority. After that, we will implement the generic Linux approach.

// // Some code notes for this task:
Function call flow: 
```
ebpfAPI!ebpf_program_attach -> _link_ebpf_program -> invoke_ioctl(EBPF_OPERATION_LINK_PROGRAM) ->
 _ebpf_core_protocol_link_program -> ebpf_link_create [sets NPI for link], ebpf_link_attach_program-> NmrRegisterClient

net_ebpf_ext_sock_addr_register_providers -> net_ebpf_extension_hook_provider_register 
[set _net_ebpf_extension_sock_addr_on_client_attach[set filter weight, compartment]]

_ebpf_link_client_attach_provider calls NmrClientAttachProvider
_ebpf_link_client_attach_provider set in _ebpf_link_client_characteristics (NPI)
```

**Comment by dthaler** [comment]
Often I see the term "short term approach" used in cases where the "long term approach" is backlogged and never done and so what is claimed to be a "short term approach" is just an excuse to make a sub-optimal long term approach.   What is the plan getting the long term approach done?
