### ISSUE TITLE
data_offset field in tcphdr in the wrong place

### ISSUE THREAD

**Issue by kalin-toshev** [microsoft/ebpf-for-windows#2643]
### Describe the bug

`data_offset` field ([here](https://github.com/microsoft/ebpf-for-windows/blob/62537b4f15b7c1cb03b8a2e4e425dc8243770b1d/include/net/tcp.h#L11)) seems to be in the wrong place (swapped with the next 2 fields); data_offset ('th_off') takes the higher 4 bits. As a result, we cannot properly parse TCP packets, containing tcp options (like mss, sack, etc.). Probably nobody used this field so far, but I thought it might be worth it fixing this. Right now, we have to extract the real offset like this - `(tcp->ns << 3) + tcp->reserved` (as a workaround). 

### Steps taken to reproduce bug

Try to implement TCP packet parsing (when TCP packets contain options - i.e. SYN, SYN/ACK) with XDP hook. 

### Expected behavior

`data_offset` should contain values >= 5

### Actual outcome

data_offset always contains 0 right now, because it occupies the reserved fields.

**Comment by dthaler** [comment]
PR #2637 discusses a related issue with tcphdr which should probably be addressed in the same PR as a fix for this issue.
