### ISSUE TITLE
Test case "wer_report_fatal_exception" generates spurious messages

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2660]
During execution of the unit tests, the test case "wer_report_fatal_exception" emits the message "Generation of crash dump succeeded" when no actual dump is created.

**Comment by dthaler** [comment]
So does the bpf_obj_get_info_by_fd test.  https://github.com/microsoft/ebpf-for-windows/blob/main/tests/unit/libbpf_test.cpp#L2144 intentionally tries to pass an invalid pointer which results in [the code](https://github.com/microsoft/ebpf-for-windows/blob/main/libs/platform/user/framework.h#L97) correctly checking it and raising an exception which results in the confusing error message without any actual dump.
