### ISSUE TITLE
ebpf_provider_load should add support for asynchronous detach of clients

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#270]
ebpf_provider_load should add support for asynchronous detach of clients.

The NMR contract permits a detach to return STATUS_PENDING and then complete the detach asynchronously. 

See:
[NPI_PROVIDER_DETACH_CLIENT_FN](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/netioddk/nc-netioddk-npi_provider_detach_client_fn)

Currently, the attach hook provider blocks the client's detach callback until all invocations are complete.

**Comment by dthaler** [comment]
@Alan-Jowett are you planning to do this one?  If so, please set milestone.  If not, please remove triaged label.
