### ISSUE TITLE
eBPF uninstallation via MSI occasionally hangs

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/ebpf-for-windows#2705]
### Describe the bug

We're using MSIs to install and uninstall eBPF in the XDP CI, and we very rarely encounter hangs while trying to uninstall eBPF. We've added diagnostics to try to understand the root cause, but there's nothing obviously wrong with eBPF or XDP.

The diagnostics are collected once the MSI process has been running for 60 seconds. I can see nothing of interest in ebpfsvc. I'm not sure what I should expect the msiexec process to be doing, but it doesn't appear to be stuck doing anything eBPF-related.

I realized XDP hasn't updated to consume eBPF 0.9.1 yet - I've started that now.

### OS information

Varies; this repro is `20348.1.amd64fre.fe_release.210507-1500`

### Steps taken to reproduce bug

In XDP CI, over many iterations:

1. Install XDP
2. Install eBPF using MSI
3. Uninstall eBPF using MSI

### Expected behavior

eBPF should uninstall cleanly.

### Actual outcome

The MSI process responsible for uninstalling eBPF hangs indefinitely.

### Additional details

ZIP containing MSI logs, kernel dump, ebpfsvc process dump, msiexec process dump, and symbols: https://1drv.ms/u/s!Au_lmmNH35OUgY19dau0eJcR4kh3ZA?e=ptdNJU

**Comment by gtrevi** [comment]
@mtfriesen what features are you installing with the MSI (i.e. the CL you're executing)?

**Comment by mtfriesen** [comment]
The install command line is:
`msiexec.exe /i $EbpfMsiFullPath INSTALLFOLDER=$EbpfPath ADDLOCAL=eBPF_Runtime_Components_JIT /qn /l*v $LogsDir\ebpfinstall.txt`

The uninstall command line is:
`msiexec.exe /x $EbpfMsiFullPath /qn /l*v $LogsDir\ebpfuninstall.txt`

Here's the code in question: https://github.com/microsoft/xdp-for-windows/blob/935cc87e378a383f2fb6574844d5a8ea9d90db7e/tools/setup.ps1#L556-L621

**Comment by gtrevi** [comment]
It seems that the uninstall log is empty... is that actually the case?

**Comment by saxena-anurag** [comment]
@mtfriesen when eBPF is being uninstalled, is any user mode app running which has handles opened to eBPF? Like loaded programs, etc.?

**Comment by mtfriesen** [comment]
> It seems that the uninstall log is empty... is that actually the case?

As far as we can tell, yes, a symptom of this hang is no content in the eBPF uninstall log

> @mtfriesen when eBPF is being uninstalled, is any user mode app running which has handles opened to eBPF? Like loaded programs, etc.?

To the best of my knowledge, the only XDP process that would have been interacting with eBPF has been cleanly terminated. Now, I'm not sure if anything else is interacting with eBPF, but it shouldn't be caused by our CI code.

```
0: kd> !process 0 0 spinxsk.exe
[no zombie process]
0: kd>
```

**Comment by gtrevi** [comment]
> @mtfriesen when eBPF is being uninstalled, is any user mode app running which has handles opened to eBPF? Like loaded programs, etc.?

On a side note, please update the CL in the script with the following (as documented [here](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/InstallEbpf.md#method-1-install-a-release-with-the-msi-installer)):

```bash
msiexec.exe /i $EbpfMsiFullPath INSTALLFOLDER=$EbpfPath ADDLOCAL=eBPF_Runtime_Components,eBPF_Runtime_Components_JIT /qn /l*v $LogsDir\ebpfinstall.txt
```

**Comment by gtrevi** [comment]
Looking to collect msiexec.exe dumps (https://github.com/microsoft/xdp-for-windows/issues/363).

**Comment by shankarseal** [comment]
blocked on [xdp 363](https://github.com/microsoft/xdp-for-windows/issues/363)

**Comment by gtrevi** [comment]
Closing this as no repro for the moment. @mtfriesen this is linked to https://github.com/microsoft/xdp-for-windows/issues/363, therefore please feel free to reopen as we have more data to investigate on. Thanks!
