### ISSUE TITLE
map_in_map and tail call operations does not scale well

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2746]
https://github.com/microsoft/ebpf-for-windows/blob/3f3b834c2fa85a57559135b6bfd4e48dae7cf4a2/libs/platform/ebpf_object.c#L12 

This spinlock is hit on each tail_call / map_in_map operations, causing significant contention.

https://github.com/microsoft/ebpf-for-windows/blob/3f3b834c2fa85a57559135b6bfd4e48dae7cf4a2/libs/platform/ebpf_object.c#L457 

Is called to resolve ID in prog_array and hash_of_map / array_of_map to object pointer, killing performance.

**Comment by saxena-anurag** [comment]
Currently we use `KSPIN_LOCK` which is always exclusive only. Can we instead switch to `EX_SPIN_LOCK` which supports shared vs exclusive acquire APIs?

**Comment by Alan-Jowett** [comment]
```
C:\test>Debug\bpf_performance_runner.exe tests_native.yml BPF_MAP_TYPE_ARRAY_OF_MAPS.*
BPF_MAP_TYPE_ARRAY_OF_MAPS read,6399,6639,6640,6610,6635,6332,6383,6301,6318,6409,6411,6404
BPF_MAP_TYPE_ARRAY_OF_MAPS update,7598,7708,7701,7587,7705,7433,7456,7461,7471,7627,7611,7615

C:\test>Debug\bpf_performance_runner.exe tests_native.yml bpf_tail_call
bpf_tail_call,28586,28344,28281,28216,28283,27640,27691,27614,27606,28612,28569,28496
```
