### ISSUE TITLE
Support of map batching libbpf functions

### ISSUE THREAD

**Issue by shpalani** [microsoft/ebpf-for-windows#2749]
### Describe the feature you'd like supported

This issue is to evaluate adding support for the following helper functions:

1.     bpf_map_update_batch
2.     bpf_map_lookup_batch
3.     bpf_map_delete_batch

----
1. LIBBPF_API int **bpf_map_update_batch** (int fd, const void *keys, const void *values, __u32 *count, const struct bpf_map_batch_opts *opts)
```
bpf_map_update_batch() updates multiple elements in a map by specifying keys and their corresponding values.

The keys and values parameters must point to memory large enough to hold count items based on the key and value size of the map.

The opts parameter can be used to control how bpf_map_update_batch() should handle keys that either do or do not already exist in the map. In particular, the flags parameter of bpf_map_batch_opts can be one of the following:

Note that count is an input and output parameter, where on output it represents how many elements were successfully updated. Also note that if EFAULT then count should not be trusted to be correct.

BPF_ANY Create new elements or update existing.
BPF_NOEXIST Create new elements only if they do not exist.
BPF_EXIST Update existing elements.
BPF_F_LOCK Update spin_lock-ed map elements. This must be specified if the map value contains a spinlock.

Parameters:
- fd – BPF map file descriptor
- keys – pointer to an array of count keys
- values – pointer to an array of count values
- count – input and output parameter; on input it’s the number of elements in the map to update in batch; on output if a non- 
-             EFAULT error is returned, count represents the number of updated elements if the output count value is not equal to the 
-             input count value. If EFAULT is returned, count should not be trusted to be correct.
- opts – options for configuring the way the batch update works

Returns:
0, on success; negative error code, otherwise (errno is also set to the error code)
```
---
2. LIBBPF_API int **bpf_map_lookup_batch** (int fd, void *in_batch, void *out_batch, void *keys, void *values, __u32 *count, const struct bpf_map_batch_opts *opts)
3. LIBBPF_API int **bpf_map_delete_batch** (int fd, const void *keys, __u32 *count, const struct bpf_map_batch_opts *opts)

### Proposed solution

 In the case of user-space programs that access/set a lot of data in BPF maps, the ioctl system-call overhead may be too much. The key to good performance is avoiding system calls as much as possible.

 **Use-case:**  XDP L4LB to set backend services. Let's say, there are 100 backend services to be added/updated/deleted. 
```
With the existing approach,
1. To add:
  for (i = 0 ; i  < 100; ++i)
     bpf_map_update_elem(...);

2. To delete:
   for (i = 0 ; i  < 100; ++i)
     bpf_map_delete_elem(...);

3. To lookup: (for delete/replace a particular entry)
   uint32_t key = 0;
   uint32_t value = 0;
   bpf_map_lookup_elem(map_fd, &key, &value);  // First value.
   for (i = 0 ; i  < 100; ++i) {
         // Get the key
        bpf_map_get_next_key(map_fd, &key, &key);
        // Get the value corresponding to that key.
        bpf_map_lookup_elem(map_fd, &key, &value);
  }
```

- New helper function. Hence the implementation needs to be brainstormed, with flow control for batching.
```
struct { 
         in_batch;
        out_batch;
        pointer to an array of   keys;
        pointer to an array of   values;
        integer         count;
        fd         map_fd;
    } batch;
```
### Additional context

Some batching helpers may not be applicable to map types:
BPF_MAP_TYPE_HASH,
BPF_MAP_TYPE_PERCPU_HASH,
BPF_MAP_TYPE_LRU_HASH,
BPF_MAP_TYPE_LRU_PERCPU_HASH,

**Comment by dthaler** [comment]
Looks like a duplicare of #2080

**Comment by shpalani** [comment]
There is an existing feature request:
  - [Support for map batch operations · Issue #2080 · microsoft/ebpf-for-windows (github.com)](https://github.com/microsoft/ebpf-for-windows/issues/2080)

As part-1, committed:
- Hash table iterator merged in
[Implement hash-table iterator by Alan-Jowett · Pull Request #2566 · microsoft/ebpf-for-windows (github.com)](https://github.com/microsoft/ebpf-for-windows/pull/2566)

To continue, there is an existing implementation in 
Work in Progress in branch: [Alan-Jowett/ebpf-for-windows at issue2080-part2 (github.com)](https://github.com/Alan-Jowett/ebpf-for-windows/tree/issue2080-part2)

---
So the decision was to add this request in Issue #2080
