### ISSUE TITLE
[SC] StartService FAILED 3:  The system cannot find the path specified.

### ISSUE THREAD

**Issue by TylerJaacks** [microsoft/ebpf-for-windows#275]
sc start EbpfCore

[SC] StartService FAILED 3:

The system cannot find the path specified.

sc start NetEbpfExt

[SC] StartService FAILED 3:

The system cannot find the path specified.

**Comment by dthaler** [comment]
Issue #248 might also help with this once that is resolved, unsure.

**Comment by dthaler** [comment]
@TylerJaacks did you build for Debug or Release?   And on what version of Windows did you try this?

**Comment by shankarseal** [comment]
@TylerJaacks  - please send the output to:
(Get-ItemProperty "HKLM:\Software\Microsoft\Windows NT\CurrentVersion").BuildLabEx

**Comment by dthaler** [comment]
@TylerJaacks we have not been able to repro this.  If you can get a repro, please Reopen and provide the above info.

**Comment by TylerJaacks** [comment]
@shankarseal 19041.1.amd64fre.vb_release.191206-1406
