### ISSUE TITLE
ebpfapi.dll should not depend on usersim.dll

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2756]
Non-test programs using eBPF for Windows should not pull in usersim.dll

**Comment by saxena-anurag** [comment]
If ebpfapi.dll depends on usersim.dll, it will require one more user mode binary to be installed. It can probably also increase load time.

**Comment by dthaler** [comment]
framework.h already has this:
```
// TODO(#2677): remove the following include, which should be private to usersim.dll.
#include "..\..\..\external\usersim\src\framework.h"
```
which I think is what this issue needs to do.
