### ISSUE TITLE
api_test.exe documentation is wrong

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#2758]
### Describe the bug

[ebpf-for-windows/docs/GettingStarted.md at main · microsoft/ebpf-for-windows (github.com)](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/GettingStarted.md#api_testexe) says:
> **api_test.exe**
This test exercises various eBPF user mode eBPF APIs, including those to load programs, enumerate maps and programs etc. This test requires the eBPF user mode service (EbpfSvc), and the kernel execution context (`EbpfCore.sys`) and the Network Extension (`NetEbpfExt.sys`) to be running. This test is currently _not_ part of the CI pipeline. Developers must run this test manually before checking in changes.

However it does seem to be part of the pipeline.  Also when I run it locally, it fails because the regression test fails and there's no instructions I can find on how to get it to pass (I shouldn't have to look at the CI/CD build files to know)

### Steps taken to reproduce bug

Install ebpf
Run api_test.exe
The regression test will fail

### Expected behavior

All tests should pass when installing ebpf

### Actual outcome

One test fails, which regression is from #2444

**Comment by dahavey** [comment]
#3013 fixes this
