### ISSUE TITLE
When Building Tests I get Custom build for 'bindmonitor.c;bpf.c;bpf_call.c;droppacket.c;divide_by_zero.c;droppacket_unsafe.c' exited with code 9009.

### ISSUE THREAD

**Issue by TylerJaacks** [microsoft/ebpf-for-windows#276]
Build started...
1>------ Build started: Project: sample, Configuration: Debug x64 ------
1>Performing Custom Build Tools
1>'clang' is not recognized as an internal or external command,
1>operable program or batch file.
1>Performing Custom Build Tools
1>'clang' is not recognized as an internal or external command,
1>operable program or batch file.
1>Performing Custom Build Tools
1>'clang' is not recognized as an internal or external command,
1>operable program or batch file.
1>Performing Custom Build Tools
1>'clang' is not recognized as an internal or external command,
1>operable program or batch file.
1>Performing Custom Build Tools
1>'clang' is not recognized as an internal or external command,
1>operable program or batch file.
1>Performing Custom Build Tools
1>'clang' is not recognized as an internal or external command,
1>operable program or batch file.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'bindmonitor.c;bpf.c;bpf_call.c;droppacket.c;divide_by_zero.c;droppacket_unsafe.c' exited with code 9009.
1>Done building project "sample.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 19 up-to-date, 0 skipped ==========

**Comment by Alan-Jowett** [comment]
Thanks for the feedback. Can you please confirm that clang is installed and in the path?

**Comment by dthaler** [comment]
@TylerJaacks please check to make sure you have all the prerequisites installed that are listed in the Getting Started Guide, and that they are in your PATH.

**Comment by dthaler** [comment]
@TylerJaacks we have been unable to repro this.  If you can get a repro, please reopen this issue and provide any more info you can.
