### ISSUE TITLE
ebpf map helper needed for copying contents of packet for various purposes

### ISSUE THREAD

**Issue by poornagmsft** [microsoft/ebpf-for-windows#278]
For multiple scenarios it is useful to get contents of the packet copied over for analysis by user mode program.

See: https://github.com/microsoft/ebpf-for-windows/issues/274

So far I've been using the xdp hook to do some packet inspection/dropping. I'd like to also use the bpf_map_* helpers to forward specific packets to a userspace process for further analysis/logging, which then helps make drop decisions for subsequent packets. The feature requested here:
#214
Would also be highly valuable.

**Comment by shankarseal** [comment]
The solution to this is the ring buffer map which is already implemented.
