### ISSUE TITLE
user mode program should be notified when map is updated by an ebpf program running in kernel

### ISSUE THREAD

**Issue by poornagmsft** [microsoft/ebpf-for-windows#279]
What is the notification model for ebpf is a great question we will need to answer..
classic windows model includes things like IRP completion for a pending IRP posted by a user mode as one way of generating notifications.

**Comment by dthaler** [comment]
How about a helper that fires an ETW event, e.g., with the key that was updated.

**Comment by dthaler** [comment]
We need a design proposal to review.

**Comment by Alan-Jowett** [comment]
Proposal:
A user-mode process can associate an event with a map. When the map changes, the event is signaled.

**Comment by Alan-Jowett** [comment]
Notification of user mode is typically done via #353. Resolving this as duplicate.
