### ISSUE TITLE
bpf_tail_call with MAX_TAIL_CALL count does not scale in performance. 

### ISSUE THREAD

**Issue by shpalani** [microsoft/ebpf-for-windows#2812]
### Describe the bug

This issue is created to improve the helper bpf_tail_call code for tail call processing. 

Performance number:
ebpf-for-windows: (nanosecs)
   - bpf_tail_callee_max,120783,**120361**

Linux: (nanosecs)
  - bpf_tail_callee_max,287,**294**

(the difference shows 400 times more).

---
To repro: Test case and runs in 
https://github.com/microsoft/bpf_performance/blob/main/bpf/max_tail_call.c

Note: The above tail calls do not have bpf_printk() helper in it.
 

### OS information

Windows 10 and above

### Steps taken to reproduce bug

To repro: Check out the test case and runs in 
   https://github.com/microsoft/bpf_performance/blob/main/bpf/max_tail_call.c

### Expected behavior

To meet approx. Linux results.

### Actual outcome

Performance number:
ebpf-for-windows:
   - bpf_tail_callee_max,120783,120361

Linux:
  - bpf_tail_callee_max,287,294

### Additional details

- The test max tail calls already incorporate static initializer in prog array.
-  [Helper bpf_tail_call is very slow · Issue #2766 · microsoft/ebpf-for-windows (github.com)](https://github.com/microsoft/ebpf-for-windows/issues/2766).

**Comment by dahavey** [comment]
Possibly same root cause as #2746

**Comment by Alan-Jowett** [comment]
This is a performance improvement, not a big.
