### ISSUE TITLE
ebpfcore DriverEntry - fail to unregister if _ebpf_driver_initialize_objects fails

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2838]
DriverEntry calls ebpf_trace_initiate but doesn't call ebpf_trace_terminate if subsequent APIs fail.

**Comment by amitschendel** [comment]
Hey, I have opened a [PR ](https://github.com/microsoft/ebpf-for-windows/pull/2921)to tackle this issue.
