### ISSUE TITLE
ye olde unit test is too slow

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#2879]
In presence of AVRF the program verifications take too slow. This is increasing the CI runs to take more than an hour. Suggestions to speed things up
- split the unit test into 2 chunks that can run in parallel on github runners.
- move the chk build runs to scheduled runs instead of PR.

**Comment by saxena-anurag** [comment]
Since now memory leak detection and fault injection are only present in debug builds, we cannot move debug builds to scheduled runs.

**Comment by Alan-Jowett** [comment]
Can we split out native vs JIT in the unit tests and run them in parallel? For the native only build, we can also then skip the JIT tests.

**Comment by Alan-Jowett** [comment]
Alternative:
Only run scheduled builds with app-verifier enabled. We already have an address sanitizer build for PR, so both seems redundant for PRs.

**Comment by rectified95** [comment]
> Alternative: Only run scheduled builds with app-verifier enabled. We already have an address sanitizer build for PR, so both seems redundant for PRs.

Looks like these don't overlap perfectly. From the ASAN team about our appverif config:
`appverif -enable Exceptions Handles Heaps Leak Locks Memory SRWLock Threadpool TLS DangerousAPIs DirtyStacks TimeRollOver -for unit_tests.exe`

> No, asan won't detect all the same bugs, and is incompatible with app verifier. Asan detects primarily memory safety issues and can do so with more accuracy and precision than app verifier can. However, it does not detect threading issues, tls issues, time rollover issues, etc. Asan is more invasive than app verifier as well, the compiler knows about asan and generates additional code to track memory allocation metadata, particularly for stack allocations.
>
> So, asan won't detect all the bugs that app verifier can with those settings but appverifier can't detect all the bugs that asan can either.
