### ISSUE TITLE
_ebpf_program_program_information_provider_changed updates trampoline with older helper functions

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#289]
```
_ebpf_program_program_information_provider_changed(..., const ebpf_extension_dispatch_table_t* provider_dispatch_table)
```

This function updates the trampoline with existing provider dispatch table, before updating it later.

```
        return_value = ebpf_update_trampoline_table(
            program->trampoline_table, program->program_information_provider_dispatch_table);

    program->program_information_provider_dispatch_table = provider_dispatch_table;
```

The provider dispatch table on program object is not updated until ebpf_extension_load returns.

```

    return_value = ebpf_extension_load(
        ...
        &program->program_information_provider_dispatch_table,
        _ebpf_program_program_information_provider_changed);
```
ebpf_extension_load sets the output dispatch table parameter only after NmrRegisterClient call returns.

```

ebpf_extension_load

status = NmrRegisterClient(client_characteristics, local_client_context, ...);

    *provider_dispatch_table = local_client_context->provider_dispatch_table;
```

The register client will cause attach_provider callback. This calls NmrClientAttachProvider which gets the provider dispatch table. The notify_change (_ebpf_program_program_information_provider_changed) callback happens right after this. But the program object's provider dispatch table is not updated at this point.

```
_ebpf_extension_client_attach_provider

    status = NmrClientAttachProvider(
        ...,
        &local_client_context->provider_dispatch_table);

    _ebpf_extension_client_notify_change(local_client_context);
```

Also it looks like in provider detach case _ebpf_program_program_information_provider_changed  will only mark the program as invalidated but not set the provider dispatch table to NULL.

```
        if (provider_dispatch_table == NULL) {
            program->program_invalidated = true;
            return;
        }
```

**Comment by Alan-Jowett** [comment]
A secondary issue is that we currently don't test this code. https://github.com/microsoft/ebpf-for-windows/issues/300
