### ISSUE TITLE
Simplify selection criteria in cicd.yml

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2903]
It should be possible to write the selection criteria in the yaml file as:
```yml
if: ${{fromJson(fromJson(needs.select-jobs.outputs.tests)[github.job])}}
```

But this causes the GitHub workflow to fail with an internal error.

Instead the condition needs explicitly name the job:
```yml
if: ${{fromJson(fromJson(needs.select-jobs.outputs.tests)['unit_tests'])}}
```

**Comment by rectified95** [comment]
I think this should be a backlog item. not sure if this even applies to the code as is today, or a prototype Alan was working on.

**Comment by Alan-Jowett** [comment]
Not relevant anymore.
