### ISSUE TITLE
Replace ebpf_bitmap.* with RTL_BITMAP

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2905]
https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/eprocess#rtl_bitmap

**Comment by dthaler** [comment]
We also want the runtime to be capable of running in user mode, so perhaps it should be in cxplat?

**Comment by dahavey** [comment]
@Alan-Jowett please file an issue in cxplat.

**Comment by Alan-Jowett** [comment]
RTL_BITMAP doesn't support the required features (atomically test and set bits).
