### ISSUE TITLE
MSI installer should deploy test setup scripts in Debug config.

### ISSUE THREAD

**Issue by rectified95** [microsoft/ebpf-for-windows#2969]
### Describe the bug

The list of expected files the MSI installer deploys in the Debug configuration includes various test EXEs.
However, for xdp_tests and connect_redirect_tests the tests won't run without additional setup with PS scripts (unlike eg. unit_tests.exe)
If we believe the Debug config should deploy test binaries, I contend they should come with their dependencies to facilitate local running. Otherwise, we should not copy over the tests.

**Comment by shankarseal** [comment]
@Alan-Jowett argues that the retail and debug MSI should not be different in what components (including tests) that are deployed.
