### ISSUE TITLE
Implement feature in the MSI to detect and uninstall manual installations.

### ISSUE THREAD

**Issue by gtrevi** [microsoft/ebpf-for-windows#2983]
Implement feature in the MSI to detect and uninstall deployments via non-canonical methods (i.e. manually, via script, etc.).

**Comment by shankarseal** [comment]
@gtrevi  please review if this issue can be closed.

**Comment by gtrevi** [comment]
Windows installer can only detect if another version of the MSI is installed. Installations "out of band" (i.e. through scripts or manual installation), cannot be detected is not with other scripts that make assumptions on the scenario. This is prone to incorrect assumptions and risks of breaking the system's state, in which 3rd party apps may be relying on.
Also, uninstalling what could "seem" a manual installation (i.e. not done through the MSI) could potentially break *other* forms of deployments used on the VM.
