### ISSUE TITLE
Eliminate emulated TLS in kernel

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2994]
TLS emulation in kernel adds significant overhead. It would be good to get rid of this and make this an explicit parameter passed to helper functions. 

![image](https://github.com/microsoft/ebpf-for-windows/assets/20480683/6c906f9a-3c25-4207-9b11-d07e8940d904)

**Comment by saxena-anurag** [comment]
Closing this bug as completed as we now have support for implicit context as well as context header for tail calls.

#3656 
#3698
