### ISSUE TITLE
No tests for program type specific helper functions

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#300]
No tests for program type-specific helper functions

There is [code](https://github.com/microsoft/ebpf-for-windows/blob/360aa224eafa6d21ad830d341af0893a5a7bb4fa/libs/execution_context/ebpf_program.c#L52) in ebpf_program.c that builds a trampoline table, but there is no test for this code.

To test this, we need to be able to provide a test program information providers with program type-specific helper functions. 

This is currently blocked until we can correctly enumerate program information at runtime and provide it to the verifier.

**Comment by Alan-Jowett** [comment]
Blocked on https://github.com/microsoft/ebpf-for-windows/issues/223

**Comment by shankarseal** [comment]
this is fixed by #336

**Comment by dthaler** [comment]
Closing per Shankar's note that this is fixed
