### ISSUE TITLE
ebpf_store_helper_um.lib is missing from nuget package

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/ebpf-for-windows#3037]
### Describe the bug

Extensions developed outside the eBPF repo need to produce a user mode helper binary that call the eBPF store APIs to allow eBPF programs to be compiled.

These APIs are not included in the nuget package.

### OS information

N/A.

### Steps taken to reproduce bug

Attempt to call `ebpf_store_update_section_information` or similar APIs from outside the eBPF repo in user mode. The APIs cannot be linked without ebpf_store_helper_um.lib.

### Expected behavior

Callable eBPF APIs are included in the nuget package. It is also expected that eBPF APIs used by developers are tested, at least to the absolute bare minimum of verifying their existence.

### Actual outcome

The callable APIs are not included in the nuget package.

**Comment by mtfriesen** [comment]
I attempted to build my code using a copy of the lib from 0.12.0 and ran into two further issues:

```
    2>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [D:\wtc\
       src\bpfexport\bpfexport.vcxproj]
     2>ebpf_store_helper_um.lib(ebpf_registry_helper.obj) : error LNK2001: unresolved external symbol cxplat_free [D:\w
       tc\src\bpfexport\bpfexport.vcxproj]
     2>ebpf_store_helper_um.lib(ebpf_registry_helper.obj) : error LNK2001: unresolved external symbol cxplat_allocate [
       D:\wtc\src\bpfexport\bpfexport.vcxproj]
     2>D:\wtc\build\bin\amd64chk\bpfexport.exe : fatal error LNK1120: 2 unresolved externals [D:\wtc\src\bpfexport\bpfe
       xport.vcxproj]
```

1. The static library is built using one flavor of the CRT, when consumers of this code may have their own CRT preferences.
2. The static library depends on internal eBPF libraries.

**Comment by mtfriesen** [comment]
Another bug:

```
      c\src\bpfexport\bpfexport.vcxproj]
         ebpf_store_helper_um.lib(ebpf_store_helper.obj) : warning LNK4291: module may contain '__except' (Structured E
       xception Handling) but was not compiled with /guard:ehcont; generating conservative metadata [D:\wtc\src\bpfexpo
       rt\bpfexport.vcxproj]
```

You may want to consider distributing this helper as a header-only library or a DLL.

Ideally the need for these helpers would be entirely eliminated: it should be possible for extensions to provide static metadata to the eBPF compiler and runtime in a static file, i.e., a manifest of some kind.

**Comment by saxena-anurag** [comment]
Actually, not including the um lib was intentional as only the extensions were expected to use the km lib and populate the store.
(um lib was intended to be used only by ebpf-for-windows). But I think we may need to include the um lib also, if an extension needs to write an equivalent of `export_program_info.exe`.

>> You may want to consider distributing this helper as a header-only library or a DLL

At least for kernel, we did export a header-only library initially, but later changed it to a .lib

**Comment by mtfriesen** [comment]
Right, but the user mode library is essential, is it not? Otherwise if a developer wants to build their extension and eBPF program as part of the same build, or build eBPF programs on any build machine that can't load their kernel driver, then they're stuck?
