### ISSUE TITLE
netebpfext's implementation of the cgroup/sock_addr_connect hook can result in incorrectly blocking a connected UDP connection

### ISSUE THREAD

**Issue by matthewige** [microsoft/ebpf-for-windows#3053]
### Describe the bug

Our cgroup/sock_addr_connect has an assumption that for a given connection, our callout should be invoked at both the connect_redirect and connect layers. However, this assumption is broken for connected UDP. When a UDP socket issues a connect() call, we see only a connect_redirect callout invocation and NOT at the connect layer.

When an ebpf program issues a reject verdict followed by a permit verdict for a connected UDP socket, our netebpfext will block the connection istead of allowing it.

### OS information

This was observed on both server 2019 and server 2022.

### Steps taken to reproduce bug

- attach a program at the cgroup/sock_addr_connect hook
- UDP socket issues connect() call
- ebpf program is invoked at the connect_redirect layer. ebpf program issues a block verdict. netebpfext stores this connection_context.
- UDP socket issues send() call
- ebpf program is again invoked at the connect_redirect layer. ebpf program now issues a permit verdict.
- netebpfext at the connect layer looks for a connection_context and finds it from the first invocation of the ebpf program and blocks the connection.

### Expected behavior

Connection should be allowed.

### Actual outcome

Connection is blocked.

### Additional details

Proposal: When processing the connect_redirect callout, we should check to see if this connection has a previous connection_context stored. If so, remove it.

This would resolve the above situation with connected UDP sockets. For normal UDP and TCP, we should not enter this scenario (we'd always expect calls at the connect_redirect and connect layer). In any case, the last provided verdict for a connection should stand, and this solution produces that.

**Comment by saxena-anurag** [comment]
We may also need to bring back periodic LRU list purge to ensure the entries are not leaked permanently.
