### ISSUE TITLE
Need test for batch invocation of programs.

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#3061]
Currently there are no tests for the following eBPF hook NPI client dispatch:

```

- [ ]     ebpf_program_batch_begin_invoke_function_t ebpf_program_batch_begin_invoke_function;
- [ ]     ebpf_program_batch_invoke_function_t ebpf_program_batch_invoke_function;
- [ ]     ebpf_program_batch_end_invoke_function_t ebpf_program_batch_end_invoke_function;

```
Having these test cases would have avoided: #3057

**Comment by saxena-anurag** [comment]
There is a test which does batch invocation for sample extension. PR #2593 added the test.

**Comment by rectified95** [comment]
I checked, and as Anurag said, this is already in place.
