### ISSUE TITLE
bpf2c should emit compiler barriers between emulated BPF instructions

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#3086]
Compilers can re-order operations, potentially mixing operations between two BPF operations. While this behavior is guaranteed to be correct for single-threaded cases, this can result in incorrect behavior being observed in the cross-CPU case.

**Comment by Alan-Jowett** [comment]
On review, emitting compiler barriers is pointless as the underlying CPU can still reorder the instructions. Need to more closely investigate the BPF memory model to determine which, if any, instructions imply compiler / memory barriers.

**Comment by dthaler** [comment]
> On review, emitting compiler barriers is pointless as the underlying CPU can still reorder the instructions. Need to more closely investigate the BPF memory model to determine which, if any, instructions imply compiler / memory barriers.

Alexei's presentation at IETF 118: https://datatracker.ietf.org/meeting/118/materials/slides-118-bpf-bpf-memory-model-00
