### ISSUE TITLE
eBPF store APIs do not provide an inverse operation

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/ebpf-for-windows#3089]
### Describe the bug

When an extension registers its characteristics using the eBPF store APIs, there is no mechanism to revert the changes when the extension is stopped or uninstalled.

### OS information

N/A.

### Steps taken to reproduce bug

Call ebpf_store_update* during install/start. The developer cannot find a way to revert the operation during uninstall/stop.

### Expected behavior

There should be a mechanism to undo the eBPF store changes.

### Actual outcome

There is no apparent mechanism to undo eBPF store changes.

**Comment by shankarseal** [comment]
This should be addressed by #3055 .

**Comment by saxena-anurag** [comment]
Fixed by #3055.
