### ISSUE TITLE
Revert C6011 override in external\Analyze.external.ruleset once upstream issue is fixed

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#309]
Revert C6011 override in external\Analyze.external.ruleset once upstream issue is fixed.

Due to https://github.com/vbpf/ebpf-verifier/issues/239 there is an override that make C6011 a warning in the external submodules. Once this is resolved, remove this overide.

**Comment by dthaler** [comment]
The ebpf-verifier fix in 239 was not sufficient.  The following warning remains:

> D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\asm_files.cpp(131): error C6011: Dereferencing NULL pointer 'maps_section'.

**Comment by Alan-Jowett** [comment]
![image](https://user-images.githubusercontent.com/20480683/123824253-1bb0fd00-d8bb-11eb-945c-d78602ac3b51.png)

It looks like that is the case based on the detailed trace.

**Comment by Alan-Jowett** [comment]
Created PR https://github.com/vbpf/ebpf-verifier/pull/242 to get this resolved.
