### ISSUE TITLE
`ebpf_serialize` module should be moved to test code.

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#3118]
Currently `ebpf_serialize` module is only used in unit test code path. So, it should be moved from production code to test code.

**Comment by dahavey** [comment]
Here is where this is used: libs\execution_context\ebpf_core.c:    retval = ebpf_serialize_program_info(
Do you still agree that it should be moved?

**Comment by dahavey** [comment]
Please reopen if you disagree.
