### ISSUE TITLE
Fix the IOCTL numbers so that ebpfapi.dll for x64 and x64-NativeOnly  are cross-compatible.

### ISSUE THREAD

**Issue by gtrevi** [microsoft/ebpf-for-windows#3126]
This is to triage our new requirements, in terms of:

- Artifacts being defined and built from the `cicd.yml` & `reusable-build.yml`.
- Artifacts to be published for Releases.

**Comment by saxena-anurag** [comment]
Currently for the pre-releases, the nuget package is generated from "x64-Release" build, and the published MSI is from "x64-NativeOnlyRelease". These both are incompatible as ebpfapi.dll generated from `x64-Release` build does not work with `x64-NativeOnlyRelease` bits.
