### ISSUE TITLE
_ebpf_program_program_information_provider_changed must ensure program type descriptor and helper prototypes remain unchanged upon provider load.

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#313]
ebpf_program must save the program type descriptor and helper prototypes once a program-info provider attaches. After that it must use the saved value to compare when provider reloads to make sure those havent changed. The only allowed change are the helper function addresses.

**Comment by dthaler** [comment]
Maybe save a hash
