### ISSUE TITLE
ebpfapi relies on HKCU for program, etc. type info

### ISSUE THREAD

**Issue by ben-zen** [microsoft/ebpf-for-windows#3202]
### Describe the bug

When loading a JIT'ted ebpf application, ebpfapi looks up the segment name in HKCU\Software\eBPF\Providers. This only works for a user that has previously exported the program, segments, and attach hook info for that user; this normally happens on installation, so unless you've run the installation steps as the user you are running your validation against, the operation fails with an opaque error.

In my case, I discovered this by installing eBPF as an interactive user, and then using TShell to deploy and run test binaries; in that case, I observed the registry calls being redirected to HKU\Default\..., which of course did not have the correct contents.

### OS information

N/A

### Steps taken to reproduce bug

1. Install eBPF as an interactive user on a VM
2. Open a TShell connection to the machine under test
3. Deploy the port_quota sample
4. Run `port_quota.exe load` via TShell

### Expected behavior

The BindMonitor eBPF program should be loaded into the kernel and start running

### Actual outcome

The program fails to load with an empty error message.

### Additional details

`netsh ebpf` commands will also misbehave when run under TShell because of this issue; they'll report any programs as being of unspec type, with no recognized attach hooks.

**Comment by absrivas12** [comment]
Attaching trace file
[ebpf_trace.txt](https://github.com/microsoft/ebpf-for-windows/files/14246625/ebpf_trace.txt)

Is this a known issue?  Any workaround that I can try for loading the sample in JIT mode?

**Comment by shankarseal** [comment]
Will be fixed by #3046 .
