### ISSUE TITLE
bpf2c should support callx instruction

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#3237]
### Describe the feature you'd like supported

"callx" instructions are generated by both clang (under -O0 or -O1) and gcc (if the
experimental -mxbpf option is passed to the compiler), but are not supported by Linux.

Per mailing list discussion at
https://mailarchive.ietf.org/arch/msg/bpf/CDQjTO8R8gdPdfeKVnoxWco8_Lw/ the intent is for the Linux verifier to support them eventually, and there is a newly filed [PREVAIL PR](https://github.com/vbpf/ebpf-verifier/pull/584) to add support in PREVAIL. This will also unblock the ability to use versions of clang later than clang-11 by using -O1 instead of -O2, which generates correlated branches PREVAIL can't deal with.

### Proposed solution

bpf2c should support callx

Possible approaches, in increasing order of complexity:
a) Only support the case where the previous instruction assigns an immediate value to the register that callx uses (I think this is the normal clang case, but need to verify)
b) Run verifier with no_simplify and ask verifier for value of register at the time of the callx instruction.
c) Support calls through a function pointer with varying prototypes, e.g.:
```
$ cat t1.c
struct t {
   void (*foo)(void);
};
void bar(struct t *arg) {
   arg->foo();
$ clang --target=bpf -O2 -c t1.c
$ llvm-objdump -d t1.o

t1.o:   file format elf64-bpf

Disassembly of section .text:

0000000000000000 <bar>:
        0:       79 11 00 00 00 00 00 00 r1 = *(u64 *)(r1 + 0x0)
        1:       8d 00 00 00 01 00 00 00 callx r1
        2:       95 00 00 00 00 00 00 00 exit
$ clang --target=bpf -c t1.c
$ llvm-objdump -d t1.o

t1.o:   file format elf64-bpf

Disassembly of section .text:

0000000000000000 <bar>:
        0:       7b 1a f8 ff 00 00 00 00 *(u64 *)(r10 - 0x8) = r1
        1:       79 a1 f8 ff 00 00 00 00 r1 = *(u64 *)(r10 - 0x8)
        2:       79 11 00 00 00 00 00 00 r1 = *(u64 *)(r1 + 0x0)
        3:       8d 00 00 00 01 00 00 00 callx r1
        4:       95 00 00 00 00 00 00 00 exit
$
```

**Comment by hawkinsw** [comment]
In binutils, this instruction is classified as being in the xbpf "cpu". As a result, objdump does not properly decode it. I am going to submit a patch but I was wondering which "cpu" version should it go under? 

Thanks!!

**Comment by dthaler** [comment]
llvm-objdump does display it as "callx".   In the bpf_conformance repo, I put it under cpu "v1" because clang generates it even if you tell it to use cpu-v1.

**Comment by dthaler** [comment]
For gcc, Jose Marchesi said on the mailing list:
> > > > GCC also generates BPF_CALL|BPF_X also named callx, but only if 
> > > > the experimental -mxbpf option is passed to the compiler.

That sounds consistent with what you said, but I'm not sure what that means for objdump.

**Comment by hawkinsw** [comment]
That's right.  That's *exactly* what I see with the code. My change is one line!! I will link here.

**Comment by hawkinsw** [comment]
Not sure whether I will get flamed or not, but here is the submission: 

https://sourceware.org/pipermail/binutils/2024-February/132394.html

**Comment by hawkinsw** [comment]
I must say, I am very confused:

```
0000000000000000 <bar>:
        0:       7b 1a f8 ff 00 00 00 00 *(u64 *)(r10 - 0x8) = r1
        1:       79 a1 f8 ff 00 00 00 00 r1 = *(u64 *)(r10 - 0x8)
        2:       79 11 00 00 00 00 00 00 r1 = *(u64 *)(r1 + 0x0)
        3:       8d 00 00 00 01 00 00 00 callx r1
        4:       95 00 00 00 00 00 00 00 exit
```

The callx instruction's first 8 bits look like

```
1000 1101
```

If I parse that out, that's `0x8` (`1000`) for the code (i.e., a call), `0x5` (`0101`) for the class (i.e., a jump) and then a `1` for the source to indicate `BPF_X`. 

It seems very strange to me that they choose to encode the register number in the `imm` field and not the `dst_reg` field. 

In fact, the assembler in bpf_conformance *does* code it that way. It turns `call %r8` into

```
8d  80  00  00  00  00  00  00
```

From the looks of the objdump source code from binutils, their callx instruction also encodes it in the `dst_reg`. 

If you look at the code in llvm that does the `callx` instruction encoding, it looks like they intentionally put the register number in the immediate field:

```C++
class CALLX<string OpcodeStr>
    : TYPE_ALU_JMP<BPF_CALL.Value, BPF_X.Value,
                   (outs),
                   (ins GPR:$BrDst),
                   !strconcat(OpcodeStr, " $BrDst"),
                   []> {
  bits<32> BrDst;
  
  let Inst{31-0} = BrDst;
  let BPFClass = BPF_JMP;
}
```

I am very tired but I just cannot seem to get past the fact that something does not add up. 

Can you help? Thank you!

**Comment by dthaler** [comment]
> I must say, I am very confused:
> 
> ```
> 0000000000000000 <bar>:
>         0:       7b 1a f8 ff 00 00 00 00 *(u64 *)(r10 - 0x8) = r1
>         1:       79 a1 f8 ff 00 00 00 00 r1 = *(u64 *)(r10 - 0x8)
>         2:       79 11 00 00 00 00 00 00 r1 = *(u64 *)(r1 + 0x0)
>         3:       8d 00 00 00 01 00 00 00 callx r1
>         4:       95 00 00 00 00 00 00 00 exit
> ```
> 
> The callx instruction's first 8 bits look like
> 
> ```
> 1000 1101
> ```
> 
> If I parse that out, that's `0x8` (`1000`) for the code (i.e., a call), `0x5` (`0101`) for the class (i.e., a jump) and then a `1` for the source to indicate `BPF_X`.

Correct.

> It seems very strange to me that they choose to encode the register number in the `imm` field and not either of the reg fields.

Yes that's what llvm did for some reason and it so widely deployed that it may not make sense to change it now.

> In fact, the assembler in bpf_conformance _does_ code it that way. It turns `call %r8` into
> 
> ```
> 8d  80  00  00  00  00  00  00
> ```

Probably my bug then.

> From the looks of the objdump source code from binutils, their callx instruction encodes it in the `dst_reg`.

Can you verify?  I might have expected src_reg.  Can you compile the program in the issue description above and paste the hex dump (with objdump I guess) into this issue?

> If you look at the code in llvm that does the `callx` instruction encoding, it looks like they intentionally put the register number in the immediate field:
> 
> ```c++
> class CALLX<string OpcodeStr>
>     : TYPE_ALU_JMP<BPF_CALL.Value, BPF_X.Value,
>                    (outs),
>                    (ins GPR:$BrDst),
>                    !strconcat(OpcodeStr, " $BrDst"),
>                    []> {
>   bits<32> BrDst;
>   
>   let Inst{31-0} = BrDst;
>   let BPFClass = BPF_JMP;
> }
> ```
> 
> I am very tired but I just cannot seem to get past the fact that something does not add up -- it seems like there are three different encodings here.

The patch i sent to the bpf mailing list documents what llvm does.
My intent was for bpf_conformance to do the same but it sounds like I have a bug in it.

**Comment by dthaler** [comment]
@hawkinsw In your patch, I see this:

> --- a/opcodes/bpf-opc.c
> +++ b/opcodes/bpf-opc.c
> @@ -274,6 +274,8 @@ const struct bpf_opcode bpf_opcodes[] =
>     BPF_V1, BPF_CODE, BPF_CLASS_JMP|BPF_CODE_JNE|BPF_SRC_X},
>    {**BPF_INSN_CALLR**, "call%W%dr", "**callx%w%dr**",
>     BPF_XBPF, BPF_CODE, BPF_CLASS_JMP|BPF_CODE_CALL|BPF_SRC_X},
> +  {BPF_INSN_CALLX, "callx%W%dr", "callx%w%dr",
> +   BPF_V1, BPF_CODE, BPF_CLASS_JMP|BPF_CODE_CALL|BPF_SRC_X},
>    {BPF_INSN_CALL, "call%W%d32", "call%w%d32",
>     BPF_V1, BPF_CODE, BPF_CLASS_JMP|BPF_CODE_CALL|BPF_SRC_K},
>    {BPF_INSN_EXIT, "exit", "exit",

So it looks to me like `BPF_INSN_CALLR` is the callx instruction already.

**Comment by hawkinsw** [comment]
> @hawkinsw In your patch, I see this:
> 
> ```
> --- a/opcodes/bpf-opc.c
> +++ b/opcodes/bpf-opc.c
> @@ -274,6 +274,8 @@ const struct bpf_opcode bpf_opcodes[] =
>     BPF_V1, BPF_CODE, BPF_CLASS_JMP|BPF_CODE_JNE|BPF_SRC_X},
>    {BPF_INSN_CALLR, "call%W%dr", "callx%w%dr",
>     ^^^^^^^^^^^^^^                ^^^^^^^^^^
>     BPF_XBPF, BPF_CODE, BPF_CLASS_JMP|BPF_CODE_CALL|BPF_SRC_X},
> +  {BPF_INSN_CALLX, "callx%W%dr", "callx%w%dr",
> +   BPF_V1, BPF_CODE, BPF_CLASS_JMP|BPF_CODE_CALL|BPF_SRC_X},
>    {BPF_INSN_CALL, "call%W%d32", "call%w%d32",
>     BPF_V1, BPF_CODE, BPF_CLASS_JMP|BPF_CODE_CALL|BPF_SRC_K},
>    {BPF_INSN_EXIT, "exit", "exit",
> ```
> 
> So it looks to me like `BPF_INSN_CALLR` is the callx instruction already (in the xbpf cpu as you mentioned). Does objdump let you specify xbpf and a v# both? if so, then it may be fine as is.

Well, yes, ish. I only realized very late last night that there was something odd happening here. So, I went back and refashioned the patch to make it do the right thing. It now will look something like this:

```diff
+  {BPF_INSN_CALLX, "callx%W%i32", "callx%w%i32",
+   BPF_V1, BPF_CODE, BPF_CLASS_JMP|BPF_CODE_CALL|BPF_SRC_X},
```

*However*, because it is specified as coming from the `imm`, the output looks odd:

```
  28:	8d 00 00 00 02 00 00 00 	callx 2
```

I bet that we can fix that, though. I will take a look as soon as possible!

**Comment by hawkinsw** [comment]
> 
> > From the looks of the objdump source code from binutils, their callx instruction encodes it in the `dst_reg`.
> 
> Can you verify? I might have expected src_reg. Can you compile the program in the issue description above and paste the hex dump (with objdump I guess) into this issue?
> 

Absolutely! I am compiling gcc now so that I can have the bpf target!

**Comment by hawkinsw** [comment]
@dthaler Thank you for responding to me so quickly. I was really, really worried that I was seeing ghosts. You and @Alan-Jowett  are truly a pleasure to work with!

**Comment by Alan-Jowett** [comment]
Any thought on which approach would be better for bpf2c?
https://godbolt.org/z/T8zxe3eaK

1) Provide an API that dynamically resolve helper ID -> address.
2) Provide an API that dispatches the call to the helper function by ID.

Looking at code gen, I *think* option might be better from a branch prediction POV.

**Comment by hawkinsw** [comment]
FYI: I have a WIP for binutils so that `objdump` will disassemble the instruction properly:

```
  28:   8d 00 00 00 02 00 00 00         callx %r2
```

**Comment by hawkinsw** [comment]
Posted: 

https://sourceware.org/pipermail/binutils/2024-February/132416.html

**Comment by hawkinsw** [comment]
I have successfully compiled gcc with the bpf target and can confirm that it does produce what we think it produces. In other words, a `call %r2` is encoded as

```
8d 02 00 00 00 00 00 00
```

**Comment by hawkinsw** [comment]
Binutils is updated:

https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=7921285b6c2ba0bee9bb21d8e23fdea4c790c181

**Comment by Alan-Jowett** [comment]
@dthaler Was this behavior added to the IETF BPF ISA? I want to make sure the implementation matches the spec.

**Comment by dthaler** [comment]
It is not currently in the ISA as there is not yet consensus on how it should work (even if clang and gcc both support it the same way).

I think it's ok for now to close as "not planned" and reopen if that changes.
