### ISSUE TITLE
Issues getting started with "DNS flood attack demo"

### ISSUE THREAD

**Issue by absrivas12** [microsoft/ebpf-for-windows#3253]
### Describe the bug

I am attempting to follow the "Getting started" instructions https://github.com/microsoft/ebpf-for-windows/blob/main/docs/GettingStarted.md#installing-ebpf-for-windows  .   

After compiling droppacket.c on the test VM with "clang -I ../include  -target bpf -O2 -g -Werror -c droppacket.c -o droppacket.o", verification succeeds but loading program keeps failing with error "22"

C:\test\sample>netsh ebpf add program droppacket.o xdp
error 22: could not load program

### OS information

OS Name	Microsoft Windows Server 2022 Datacenter Azure Edition
Version	10.0.20348 Build 20348

### Steps taken to reproduce bug

1. Followed instructions to setup azure VM first time with test signing on and rebooted vm.
2. Followed https://github.com/microsoft/ebpf-for-windows/blob/main/docs/InstallEbpf.md to install ebpf  for JIT compiled programs.  
3. The msi in [v0.13.0](https://github.com/microsoft/ebpf-for-windows/releases/tag/Release-v0.13.0) didnot show "JIT" option during install.  So used the MSI file from the release zip folder of same release.  it showed the JIT mode. installed with all options included.
4. Tried loading droppacket.o (using droppacket.o from the installation - "C:\Program Files\ebpf-for-windows\testing\droppacket.o").  using cmd "netsh ebpf add program droppacket.o xdp"  .  Failed with "error 22: could not load program"
5. Tried compiling droppacket.c locally on test VM.  Same result.

### Expected behavior

droppacket.o program should load successfully.

### Actual outcome

Loading droppacket.o failed with "error 22: could not load program"

**Comment by absrivas12** [comment]
Attaching trace file
[ebpf_trace.txt](https://github.com/microsoft/ebpf-for-windows/files/14247057/ebpf_trace.txt)

Is this a known issue?  Any workaround for loading the sample in JIT mode?

**Comment by absrivas12** [comment]
Hi,
I am getting the same error with the simplest possible ebpf program

<img width="601" alt="image" src="https://github.com/microsoft/ebpf-for-windows/assets/17738115/863204b8-c5e0-4c11-9604-49392ed41bf2">

i see this error in trace .   also am using azure VM with trusted launch off.

<img width="957" alt="image" src="https://github.com/microsoft/ebpf-for-windows/assets/17738115/346399f4-ee99-4f6e-a539-d08a6b5adec4">

**Comment by shpalani** [comment]
>> cmd "netsh ebpf add program droppacket.o **xdp**"

We are in the process of updating the document.
1. program type 'xdp' is not supported. The document will be updated with instructions to install '[xdp-for-windows](https://github.com/microsoft/xdp-for-windows)' extension for xdp programs.
2. For the short term, you can use 'xdp_test'.

**Comment by absrivas12** [comment]
Thanks for your suggestion @shpalani .  with xdp_test workaround i am able to load the sample.  But now after sending the flood i dont see any packets getting dropped by the program.   following the TSG i ran these commands but they dont show attach type - is that expected?


<img width="238" alt="image" src="https://github.com/microsoft/ebpf-for-windows/assets/17738115/da68f545-744d-4e93-8b5a-c84c99a98ea2">

**Comment by absrivas12** [comment]
Hi,
i was able to identify that the sample droppacket program was infact getting invoked.  it was bailing out at first set of statements that check the interface index as the default value of "0" in array map didnt match.

After commenting it out i was able to see it dropping all the 0-bytes UDP packets.   However i notice that it takes around half of the cpu .  Is it because i compiled the program with "-g" flag?   without "-g" flag the program load itself fails with missing BLF section error.  I also removed the counter lookup/increment code.  but still 50% of the one core is used 

<img width="841" alt="image" src="https://github.com/microsoft/ebpf-for-windows/assets/17738115/f108c0c3-ced9-4bed-a4ba-9aad49428cd6">

**Comment by absrivas12** [comment]
@shpalani i installed [xdp-for-windows](https://github.com/microsoft/xdp-for-windows)'  but i still cant load program with "xdp"  .  Do i still need to use use xdp_test even after installing xdp-for-windows?

**Comment by shpalani** [comment]
> Do i still need to use use xdp_test even after installing xdp-for-windows?

No, it has to xdp, with a proper interface.

**Comment by dahavey** [comment]
This has been resolved.
