### ISSUE TITLE
generate_expected_bpf2c_output.ps1: Remove the generated  xdp_adjust_head_unsafe_[dll|raw|sys].c

### ISSUE THREAD

**Issue by shpalani** [microsoft/ebpf-for-windows#3267]
### Describe the bug

While running '.\scripts\generate_expected_bpf2c_output.ps1 .\x64\Debug\', the below 3 files are being generated in addition to others.  These files are not checked in. This issue is created to check and remove those, if not needed.

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        tests/bpf2c_tests/expected/xdp_adjust_head_unsafe_dll.c
        tests/bpf2c_tests/expected/xdp_adjust_head_unsafe_raw.c
        tests/bpf2c_tests/expected/xdp_adjust_head_unsafe_sys.c
```

### OS information

Windows 10 and above.

### Steps taken to reproduce bug

Run '.\scripts\generate_expected_bpf2c_output.ps1 .\x64\Debug\'
Check 'git status'

### Expected behavior

Not sure whether those files are needed? 
If needed, should those files be checked in?
 If not needed, can those files be removed?

### Actual outcome

git status
...
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        tests/bpf2c_tests/expected/xdp_adjust_head_unsafe_dll.c
        tests/bpf2c_tests/expected/xdp_adjust_head_unsafe_raw.c
        tests/bpf2c_tests/expected/xdp_adjust_head_unsafe_sys.c

**Comment by Alan-Jowett** [comment]
Files are already removed. Fixed by: #3263
