### ISSUE TITLE
README.md should provide link to the doxygen docs

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#330]
The main README.md page should have a link to the doxygen docs that are generated by the build tools.

**Comment by dthaler** [comment]
Why?  Currently there is a layer of indirection where README has a link to the Getting Started Guide, which has the link to the doxygen docs.  The theory being that you only care about the API docs if you actually want to Get Started.

**Comment by Alan-Jowett** [comment]
Makes sense. Didn't see it in the getting started guide when I looked, but agree that's the right place for it.
