### ISSUE TITLE
ebpf-for-windows should emit unwind information

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#332]
eBPF for Windows should emit the correct unwind information so that [x64 exception handling](https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?view=msvc-160) works correctly. 

This will improve the diagnosability of crash dumps.

It should probably use [RtlInstallFunctionTableCallback](https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-rtlinstallfunctiontablecallback) to dynamically add the exception handler when needed.

**Comment by poornagmsft** [comment]
@Alan-Jowett  is this for jitted code or the ebpf execution context ?

**Comment by Alan-Jowett** [comment]
Windows kernel doesn't export the functionality to emit dynamic unwind information for generated code, so there is no mechanism available to implement this.
