### ISSUE TITLE
`bpf2c` does not build correctly when `ebpfcore` is running.

### ISSUE THREAD

**Issue by gtrevi** [microsoft/ebpf-for-windows#3350]
When building the solution from VS, on a VM where `ebpfcore` is running, the bpf2c does not build correctly.
(a similar bug should have been open/closed in the past)

**Comment by saxena-anurag** [comment]
Is this duplicate of https://github.com/microsoft/ebpf-for-windows/issues/2763?

**Comment by gtrevi** [comment]
Closed as duplicate of #2763 2763
