### ISSUE TITLE
Implement bpf_object__open_mem 

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#3352]
Libbpf supports loading ELF files from both memory and from disk.

To aid in fuzzing the verifier, it would be useful to permit the following combination:
1) Loading ELF file from memory instead of disk.
2) Running in interpret mode with ubpf_toggle_bounds_check switched on.

This can be used to fuzz the verifier for safety of the generated program (i.e. does executing a fuzzed program access out-of-bounds memory etc).

**Comment by saxena-anurag** [comment]
Related issue: https://github.com/iovisor/ubpf/issues/68
