### ISSUE TITLE
bpf2c should support bpf2bpf function calls

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#3388]
### Describe the feature you'd like supported

currently bpf2c only supports inlined function calls, not bpf2bpf function calls.
PREVAIL is adding support for non-inlined function calls, and bpf2c should do the same.                

### Proposed solution

Generate function calls when the bpf bytecode uses the call local instruction

**Comment by shankarseal** [comment]
The verifier changes are covered by https://github.com/vbpf/ebpf-verifier/pull/608 in the verifier repo. We need to make a similar change in bpf2c tool.

**Comment by shankarseal** [comment]
@dthaler are you OK with backlogging this? We will revisit this in the next week's triage.

**Comment by dthaler** [comment]
Blocked on https://github.com/vbpf/ebpf-verifier/pull/608 being merged

**Comment by dthaler** [comment]
Reactivating this for local stack variables which #3506 did not fix.
That support is blocked on https://github.com/vbpf/ebpf-verifier/issues/720
