### ISSUE TITLE
Add "verified" info in bpf2c output code

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#3391]
Currently bpf2c invokes the verifier and once the verification succeeds, it generates the native C code. For `Release` builds, the verification step cannot be skipped today. Though, the `Debug` version of bpf2c supports `--skip-verification` to skip the verification step and allow native code generation. `--skip-verification` option is used to test features that are supported by bpf2c, but not yes supported in the verifier.

To ensure that unverified native module cannot be loaded, add "verified" info in the native code. This can simply be a boolean in `program_entry_t` that tells whether the program has been verified or not.

**Comment by dthaler** [comment]
> To ensure that unverified native module cannot be loaded, add "verified" info in the native code. 

That would not "ensure" that unverified native modules cannot be loaded.  All it takes it someone hand editing the native code to add verified info manually.  Hence I'm not convinced this idea is useful.

**Comment by saxena-anurag** [comment]
> > To ensure that unverified native module cannot be loaded, add "verified" info in the native code.
> 
> That would not "ensure" that unverified native modules cannot be loaded. All it takes it someone hand editing the native code to add verified info manually. Hence I'm not convinced this idea is useful.

Agree. The intent of this change is not to block malicious users from loading unverified programs, but to disallow a developer from making a mistake (say by using debug version of bpf2c.exe that supports an option to bypass verification) and catching such cases at load time.

**Comment by saxena-anurag** [comment]
Looks like this scenario is already covered by the program hash logic -- if the verification is skipped in bpf2c, then the hash length is set to 0, and ebpfcore fails to load the program with error `EBPF_INVALID_ARGUMENT`. Maybe we can update the error code in this case to a more specific one -- something like INVALID_HASH
