### ISSUE TITLE
Add xdp helper functions for packet modification, like bpf_xdp_adjust_head, etc.

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#341]
This issue is to track adding the following XDP specific helper functions for adjusting XDP packet header and computing checksum.

- [ ] bpf_xdp_adjust_head
- [ ] bpf_csum_diff

The following networking specific helper functions that should also be supported in eBPF for Windows:

- bpf_xdp_adjust_meta (Issue #524 )
- bpf_xdp_adjust_tail (Issue #524)
- bpf_fib_lookup (Issue #525)

**Comment by poornagmsft** [comment]
@saxena-anurag bpf_csum_diff and fib_lookup should be a separate issue.
lets use this one for tracking xdp helpers.

**Comment by dthaler** [comment]
@saxena-anurag Please file new issue for the other APIs listed above

**Comment by dthaler** [comment]
Related PR is #522

**Comment by saxena-anurag** [comment]
Moved `bpf_csum_diff` and `bpf_fib_lookup` to issue #525 and `bpf_xdp_adjust_meta` to issue #524
