### ISSUE TITLE
Issues with ebpf_extension_header

### ISSUE THREAD

**Issue by matthewige** [microsoft/ebpf-for-windows#3420]
### Describe the bug

- The CURRENT_VERSION_SIZE macros cannot be used by extensions without first defining the EBPF_SIZE_INCLUDING_FIELD macro. This EBPF_SIZE_INCLUDING_FIELD macro (and its dependents) should be moved to a header that is exported in our nuget package, to allow for developers to use it.
- The following are missing sizes:
EBPF_HELPER_FUNCTION_ADDRESSES_CURRENT_VERSION_SIZE
EBPF_ATTACH_CLIENT_DATA_CURRENT_VERSION_SIZE
EBPF_ATTACH_PROVIDER_DATA_CURRENT_VERSION_SIZE
EBPF_PROGRAM_INFORMATION_CLIENT_DATA_CURRENT_VERSION_SIZE
- There seems to be some issues with our code which uses EBPF_HELPER_FUNCTION_ADDRESSES_CURRENT_VERSION, some of which point to incorrect size. This should be updated to use the new EBPF_HELPER_FUNCTION_ADDRESSES_CURRENT_VERSION_SIZE once it is added.
- For ebpf_extension_data_t - The header was added, but it looks like this may have replaced the actual extension_data_t fields for version and size (of the data field).

### Steps taken to reproduce bug

Consume ebpf 0.15.0. Adding the extension header ran into the above issues.

### Expected behavior

n/a

### Actual outcome

n/a

**Comment by mtfriesen** [comment]
Thanks, I was discovering the same issues when trying to consume 0.15.0 from XDP.
