### ISSUE TITLE
Add support for BPF_MAP_TYPE_LRU_HASH

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#343]
eBPF for Windows only supports 2 map types currently -- array and hash table. This issue is to track other map types for which support needs to be added:

- BPF_MAP_TYPE_PERCPU_ARRAY (issue #192)
- BPF_MAP_TYPE_PERCPU_HASH (issue #192)
- BPF_MAP_TYPE_LPM_TRIE (issue #560)
- BPF_MAP_TYPE_PERF_EVENT_ARRAY (issue #353)
- [x] BPF_MAP_TYPE_LRU_HASH
- BPF_MAP_TYPE_HASH_OF_MAPS (issue #375)
- BPF_MAP_TYPE_PROG_ARRAY (issue #344)

**Comment by dthaler** [comment]
Support for BPF_MAP_TYPE_HASH_OF_MAPS is blocked on https://github.com/vbpf/ebpf-verifier/issues/228

**Comment by dthaler** [comment]
I plan to do BPF_MAP_TYPE_HASH_OF_MAPS (and BPF_MAP_TYPE_ARRAY_OF_MAPS) by end of 2108.

**Comment by dthaler** [comment]
Some details are at:
- https://www.ferrisellis.com/content/ebpf_syscall_and_maps/#bpf_map_type_lru_hash-and-bpf_map_type_lru_percpu_hash
- https://www.ferrisellis.com/content/ebpf_syscall_and_maps/#bpf_map_type_lpm_trie

**Comment by dthaler** [comment]
For LPM_TRIE, according to https://github.com/iovisor/bcc/blob/master/tests/python/test_lpm_trie.py (Apache licensed), the key struct be a struct containing a 32-bit prefix length, followed by the actual prefix, padded to the maximum key size.

**Comment by Alan-Jowett** [comment]
Moved LPM_TRIE to it's own issue #560

**Comment by dthaler** [comment]
Closing as all other map types are now in other issues and LRU Hash is merged.
