### ISSUE TITLE
Add support for tail calls

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#344]
This issue to track adding support for tail calls in eBPF for Windows. This mainly requires the following things:

- [x] 1. Verifier support for tail calls.  It should verify that the argument is indeed ctx pointer with offset 0, and that the type of the map is BPF_MAP_TYPE_PROG_ARRAY.
- [x] 2. Support for BPF_MAP_TYPE_PROG_ARRAY map, including not allowing any entries to hold programs with a different type from the calling program.
- [x] 3. bpf_tail_call like helper function, including limiting the number of calls.

**Comment by poornagmsft** [comment]
@saxena-anurag  we need to open a issue for prevail for tail calls and then link here. I believe @dthaler  already has opened one.
this particular one could be used for tracking the helper function. 
Doesn't item #2 need a separate issue?

**Comment by dthaler** [comment]
The prevail issue is https://github.com/vbpf/ebpf-verifier/issues/117

**Comment by dthaler** [comment]
@Alan-Jowett Does this have any impact on the JIT compiler?  Check.

**Comment by dthaler** [comment]
In vbpf/ebpf-verifier#117, Elazar explained:

`I think the runtime is responsible for not allowing any prog_array_map to hold programs with different type. The verifier should simply verify that this is indeed ctx pointer with offset 0, and that the type of the map is PROG_ARRAY. This addresses both (a) and (b), and I think that's how it is done in the Linux verifier and runtime. The runtime also limits the number of calls.`

**Comment by dthaler** [comment]
Prevail added some verification support in https://github.com/vbpf/ebpf-verifier/pull/244

**Comment by Alan-Jowett** [comment]
https://github.com/iovisor/ubpf/issues/87 

Add support fo uBPF to support unwind on success to enable tail-call behavior.

**Comment by Alan-Jowett** [comment]
More work to be done still.

**Comment by Alan-Jowett** [comment]
All parts of this are now complete.
