### ISSUE TITLE
Retire old ebpf_performance tests

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#3460]
The existing ebpf_performance tests have been exceeded replaced by the in-kernel BPF performance tests.

**Comment by shankarseal** [comment]
Move the Bpf perfromance tests to netperf, as it will provide stable results and the ability to query previous data and automatically block PRs if a regression is detected.

**Comment by Alan-Jowett** [comment]
Test still serve as a good stress test. They shouldn't be retired.
