### ISSUE TITLE
_ebpf_link_instance_invoke_batch_begin/_ebpf_link_instance_invoke_batch_end use expensive EX_RUNDOWN_REF

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#3483]
_ebpf_link_instance_invoke_batch_begin and _ebpf_link_instance_invoke_batch_end use the expensive EX_RUNDOWN_REF construct. 

Given that this block of code is already protected by epoch_enter/epoch_exit, the code should rely on epoch protection to detect when the last program using a program information has exited.

Proposed changes:
1) In [_ebpf_program_type_specific_program_information_detach_provider](https://github.com/microsoft/ebpf-for-windows/blob/c2419acd662b58a816e42e4062885834dfb576ad/libs/execution_context/ebpf_program.c#L558) set program->extension_program_data to NULL, then call ebpf_epoch_synchronize.
2) In [ebpf_program_invoke](https://github.com/microsoft/ebpf-for-windows/blob/c2419acd662b58a816e42e4062885834dfb576ad/libs/execution_context/ebpf_program.c#L1424_) check if extension_program_data is NULL and fail the invoke.
3) Remove rundown protection from batch_begin/batch_end.

This will achieve two things:
1) Speed up batch begin/end.
2) Allow batch across different programs.

**Comment by Alan-Jowett** [comment]
Upon review, this may actually be entirely redundant.

1) When the ref-count on the program reaches zero, it calls _ebpf_program_zero_ref_count
2) _ebpf_program_zero_ref_count calls _ebpf_program_detach_links
3) _ebpf_program_detach_links calls NmrDeregisterClient on the hook provider.

As long as the hook provider is well formed and stops invoking the BPF program before it finishes detaching, the program can't be unloaded while a call is being dispatched.

**Comment by shankarseal** [comment]
@Alan-Jowett 
Re-opening the issue for phase 2 of the changes.
