### ISSUE TITLE
bpf2c doesn't generate well-formatted code for tail calls

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#3509]
### Describe the bug

For tail_call_sequential.c and tail_call_max_exceed.c, bpf2c generates code where the string table lists each function on a separate line, e.g.:
```
static const char* _map_initial_string_table[] = {
    "sequential0",
    "sequential1",
    "sequential2",
    "sequential3",
    "sequential4",
    "sequential5",
...
```

However format-code requires them to be multiple per line, so that after any change it couldn't be checked in without using --no-verify or reformatting the code.  Reformatting the code just results in test failures where the actual output wouldn't match the expected output, so one must check in with no-verify which is not ideal since that then skips code formatting on any _other_ files in the same changelist.

### Steps taken to reproduce bug

Make a change to  tail_call_sequential.c or tail_call_max_exceed.c
Build the project
Do `.\scripts\generate_expected_bpf2c_output.ps1 .\x64\Debug\`
Try to check in the change.

### Expected behavior

Checking in the change should not require no-verify

### Actual outcome

Checking in the change requires no-verify

**Comment by saxena-anurag** [comment]
We can probably update bpf2c to generate `clang format` pragma at start and end of the above code block.
