### ISSUE TITLE
Add `total_size` field in `ebpf_extension_header_t`

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#3526]
Currently `ebpf_extension_header_t` struct is defined as below:

```
typedef struct _ebpf_extension_header
{
    uint16_t version; ///< Version of the extension data structure.
    size_t size;      ///< Size of the extension data structure.
} ebpf_extension_header_t;
```

This works fine, as long as the runtime gets a pointer to single object, and the `version` and `size` fields are sufficient to safely read and copy the fields from the original struct. But if the extension (or any other versioned interface which is also using this header for versioning) passes an array of structs, then the runtime also needs to figure out the total size of a struct. Due to padding, the struct will not be same as `size` above. So for each case, the runtime has to calculate the total size of the struct, and padding added for each struct will be different.

One way to simplify this is to add another field `total_size` in the above struct, which will be simply `sizeof(<struct>)`.

**Comment by dthaler** [comment]
When would an extension pass an array of `ebpf_extension_header_t` structs?
