### ISSUE TITLE
eBPF for Windows should support ringbuf map types

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#353]
Provide implementations for:
BPF_MAP_TYPE_RINGBUF
bpf_ringbuf_output()
ring_buffer__new()
ring_buffer__free)

Reference:
https://nakryiko.com/posts/bpf-ringbuf/

**Comment by qmonnet** [comment]
Regarding perf event array vs. eBPF ring buffer:

> There are two distinctive motivators for this work, which are not satisfied by existing perf buffer, which prompted creation of a new ring buffer implementation.
> -  more efficient memory utilization by sharing ring buffer across CPUs;
> -  preserving ordering of events that happen sequentially in time, even across multiple CPUs (e.g., fork/exec/exit events for a task).

(Extract from the [kernel documentation for the ring buffer](https://www.kernel.org/doc/html/latest/bpf/ringbuf.html) - Andrii's post linked above is also an excellent resource)

My understanding is that new applications would benefit from going with the ring buffer, although most existing programs that need to send data to user space have used the perf event array so far so it might be worth supporting too, for compatibility.
