### ISSUE TITLE
NMR Client for helper functions should delay detaching until epoch ended.

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#354]
NMR Client for helper functions should delay detaching until epoch ended.

eBPF programs are marked as invalidated when an NMR Provider for helper functions requests detach. This prevents new instances of the program from running. 

The problem is that instances of the program that have already started will continue to reference the helper functions until the current epoch ends. The net effect is that we need to delay the NMR client detach until the epoch ends to prevent calling into an unloaded helper function.

**Comment by Alan-Jowett** [comment]
Note:
This only matters if there are program-type-specific helpers or general helpers that are hosted outside the execution context, which isn't the case yet.

**Comment by dthaler** [comment]
> Note:
> This only matters if there are program-type-specific helpers or general helpers that are hosted outside the execution context, which isn't the case yet.

The sample extension already has this case.

**Comment by Alan-Jowett** [comment]
Already fixed. See:
https://github.com/microsoft/ebpf-for-windows/blob/acb6859758c141314d1086db34142f0466b138ec/libs/execution_context/ebpf_program.c#L206
