### ISSUE TITLE
Release policy must be updated to bump the minor version of the main branch immediately following a release.

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#3669]
Structs used in NMR interface of native modules are not versioned. Instead, they rely on the version of bpf2c that was used to generate the native module. eBPF runtime is expected to use this version to handle multiple versions of native module.

To allow this, the version in the `main` branch should be bumped to next version once a version has been released.

We should also update the release process document to capture this step after a release is done.

**Comment by shankarseal** [comment]
@saxena-anurag file a different issue to track the NMR module versioning discussion, and please author a markdown explaining the versioning strategy (along with the motivation) for the native module.
