### ISSUE TITLE
Sample extension tests should test both JIT and interpret mode

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#370]
https://github.com/microsoft/ebpf-for-windows/blob/8f46b4020f79c32f994d3a59671ce8782e4b4cf0/tests/sample/ext/app/sample_ext_app.cpp#L72

Can we add a test for interpreter mode here?

**Comment by poornagmsft** [comment]
@shankarseal please link to the appropriate issue on which this particular one is blocked.

**Comment by poornagmsft** [comment]
Note: Support for program_type specific helpers in interpreter mode.
