### ISSUE TITLE
Replace murmur32 with XXH3

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#3706]
Performance testing suggests that the [XXH3 hash algorithm](https://xxhash.com/) outperforms the murmur32 algorithm while still maintaining relatively good randomness.

**Comment by dthaler** [comment]
LSF/MM/BPF 2022 talked about this, and Linux switched from murmur32 to xxh64 in the kernel.
My note from a discussion we had around that time said we currently use murmur3, xxh3 seems much better but can't use SSE2 in kernel because of floating pt arithmetic.

**Comment by Alan-Jowett** [comment]
No measurable improvement for switching to XXH3 for small key sizes.
