### ISSUE TITLE
API(s) to detach an already loaded program

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#372]
Support for detaching an already loaded program.

Following is the expected flow:
1. ebpf_object_get() to get fd of the pinned program.     <== already implemented.
2. **ebpf_get_program_info_by_fd**() to get program info. This will also contain link info (along with link fd) for all attaches of this program
3. **ebpf_link_detach_by_fd**() to detach the link. This should be easy to implement as ebpf_link_detach() is already present.

**Comment by poornagmsft** [comment]
@dahavey we need to be able to track issues like these which are not cleanup/nice to have but important so they are not buried in backlog after triage.

**Comment by dthaler** [comment]
bpftool supports this with `bpftool prog detach PROG ATTACH_TYPE [MAP]` which uses libbpf.

The relevant libbpf APIs are:
```
LIBBPF_API int bpf_prog_detach(int attachable_fd, enum bpf_attach_type type);
LIBBPF_API int bpf_prog_detach2(int prog_fd, int attachable_fd, enum bpf_attach_type type);
```

**Comment by saxena-anurag** [comment]
For this issue, an API `ebpf_get_program_info_by_fd()` or something equivalent is still pending.

**Comment by dthaler** [comment]
> For this issue, an API `ebpf_get_program_info_by_fd()` or something equivalent is still pending.

One libbpf API is
```
int bpf_obj_get_info_by_fd(int bpf_fd, void *info, __u32 *info_len);
```
which is not type-safe, and I think the prog_info returned is not specified by libbpf by varies by platform.  It writes data into the memory provided by the caller.

The type-safe libbpf API is:
```
struct bpf_prog_info_linear *
bpf_program__get_prog_info_linear(int fd, __u64 arrays);
```
It allocates memory that the caller must call `free()` on.

**Comment by dthaler** [comment]
looking at bpftool, I think the expected user flow is "bpftool link list" to see all links, and then "bpftool link detach id <linkid>" to do the detach.  This translates into an expected libbpf flow of:

1. bpf_link_get_next_id to enumerate link ids
2. bpf_link_get_fd_by_id to get a link fd from the link id
3. bpf_obj_get_info_by_fd to get the bpf_link_info structure with the data to print

We already support 1 and 2, just missing 3 to enable this bpftool flow.
