### ISSUE TITLE
API to enumerate all pin paths for a program

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#373]
This can either be clubbed with ebpf_get_program_info() API which will also return all the pin paths for the specified program or it can be a new API to just query all the pin paths for a program.

The same is applicable for maps.

**Comment by poornagmsft** [comment]
Related to issue https://github.com/microsoft/ebpf-for-windows/issues/364

**Comment by qmonnet** [comment]
> Related to issue #364
To clarify: Relation comes from the fact bpftool is already able to do this, so porting bpftool should bring this feature to Windows?
Also mentioned during the call: even with bpftool, there would still be a need for an API version of the feature.

**Comment by dthaler** [comment]
https://elixir.bootlin.com/linux/latest/source/tools/bpf/bpftool/common.c works as follows:

For each path under the bpf mount point:
1. Call bpf_obj_get() to get an fd
2. Call get_fd_type() to see if it's the type we're looking for (e.g., program)
3. Call bpf_obj_get_info_by_fd() to get the info about it

**Comment by dthaler** [comment]
Related to issue #188
