### ISSUE TITLE
eBPF external extensions missing extensions

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#3761]
### Describe the bug

PR #3752 added a list of [extensions that integrate with eBPF for Windows](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/GettingStarted.md#ebpf-external-extensions).

However it only lists XDP for Windows.
https://github.com/microsoft/ntosebpfext seems to have two more extensions that should probably be on the list.

### Steps taken to reproduce bug

Read the GettingStarted doc.

### Expected behavior

External extension list should include known extensions.

### Actual outcome

Only XDP for Windows is listed.

**Comment by shankarseal** [comment]
@shpalani can you please add the ntosebpfext extensions to the document?
