### ISSUE TITLE
Print compartment ID in `connect_redirect` hook traces

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#3762]
Currently connect_redirect hook traces do not include compartment ID. It will be helpful to include compartment ID in the traces to debug in a multi-tenant environment.

**Comment by vpidatala94** [comment]
Testing is a blocker - as it requires a 2 VM setup. Current guidance is to create a self hosted runner and run the ci-cd yml tests and capture the traces while connect_redirect_tests.exe are being run
