### ISSUE TITLE
Need support to associate manually created map to an eBPF program.

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#379]
We need implementation for this libbpf API bpf_prog_bind_map that can be used to associate any map to a program.

**Comment by dthaler** [comment]
https://www.kernel.org/doc/html/latest/userspace-api/ebpf/syscall.html says:

> **BPF_PROG_BIND_MAP**
> **Description**
> Bind a map to the lifetime of an eBPF program.
> 
> The map identified by map_fd is bound to the program identified by prog_fd and only released when prog_fd is released. This may be used in cases where metadata should be associated with a program which otherwise does not contain any references to the map (for example, embedded in the eBPF program instructions).
> 
> **Return**
> Returns zero on success. On error, -1 is returned and errno is set appropriately.
