### ISSUE TITLE
Tracer with this project

### ISSUE THREAD

**Issue by grubeli** [microsoft/ebpf-for-windows#382]
There are many syscall tracers build by people based on ebpf on Linux, is it possible to do same on Windows using this project?

**Comment by poornagmsft** [comment]
@grubeli Could you provide more details into this request? Did you mean ability to trace what syscalls (or the equivalent on Windows) are called using eBPF or anything else?

**Comment by grubeli** [comment]
yes, if that's possible

**Comment by dthaler** [comment]
If this is about kprobe hooks, then this is a duplicate of issue #206, so resolving as a duplicate.  Please reopen if this is not covered by that issue.
