### ISSUE TITLE
Switch eBPF for Windows over to using the new nuget based Windows Driver Kit model

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#3844]
WDK team now publishes the WDK as a nuget package, making it easier to consume on projects.

eBFP for Windows should switch over to using this model in the future.

**Comment by shankarseal** [comment]
@LakshK98 - try building the sample driver using the nuget package first. Take help from ither maintainers for this project.

**Comment by Alan-Jowett** [comment]
Switching usersim over first:
https://github.com/microsoft/usersim/pull/232
