### ISSUE TITLE
Should eBPF programs always be run in a non-preemptible  mode?

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#385]
Linux documents that BPF programs always execute in a non-preemptible mode. 

eBPF-for-Windows has three possible modes:
1) Execute at IRQL == Dispatch - Programs run to completion without pre-emption.
2) Execute at IRQL == Passive - Programs can be pre-empted.
3) User mode - Programs can be pre-empted. 

Should we simplify this logic and always run programs in a non-preemptible mode? 

This would simplify:
1) Epoch tracking
2) Per-CPU map logic.

**Comment by dthaler** [comment]
For the kernel as an execution context, I would say yes dispatch level only (non-preemptible). 
For user mode execution contexts, dispatch level is not possible so requires more thought.

**Comment by Alan-Jowett** [comment]
For kernel-mode:
1) Raise to IRQL on epoch_enter.
2) Restore the previous IRQL on epoch exit.

For user-mode, we can do the following:
1) Affinitize thread to current CPU on epoch_enter.
2) Acquire a per-CPU lock on epoch_enter.
3) Release a per-CPU lock on epoch_exit.
4) Restore thread affinity on epoch_exit.

This will give non-preemption behavior for user mode, with respect to the execution context. Only 1 thread per CPU will execute within the execution context and threads won't migrate between CPUs during the eBPF program execution.

Threads can still be pre-empted by other non-EC threads, but this is no different than DPC's being pre-empted by hyper-v in the kernel.

Thoughts?

**Comment by dthaler** [comment]
@qmonnet @teknoraver can you provide more info on whether programs are pre-emptible on Linux?
