### ISSUE TITLE
ARM64 - hash-table replace is very expensive on arm64

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#3869]
![image](https://github.com/user-attachments/assets/42b9c93e-fec9-4d9f-874b-d8d030c07e56)

**Comment by shankarseal** [comment]
@Alan-Jowett, can you ask the customer that is requesting this and we can discuss this the following week with that information.

**Comment by shankarseal** [comment]
ARM v8.0 is required.
So the proposed solution is to do CPU check at runtime and fallback to functions that are compatible with hardware as needed. This is what the current behavior in PR #3838 .
