### ISSUE TITLE
xdp_md_t is not binary compatible with Linux

### ISSUE THREAD

**Issue by lmb** [microsoft/ebpf-for-windows#3873]
### Describe the bug

netebpfext uses the following definition for xdp_md_t:

```
typedef struct xdp_md_
{
    void* data;               ///< Pointer to start of packet data.
    void* data_end;           ///< Pointer to end of packet data.
    uint64_t data_meta;       ///< Packet metadata.
    uint32_t ingress_ifindex; ///< Ingress interface index.

    /* size: 26, cachelines: 1, members: 4 */
    /* last cacheline: 26 bytes */
} xdp_md_t;
```

This is not binary compatible with Linux because the first two fields are pointers instead of uint32 values as on Linux. The same goes for data_meta, which should also be 32 bit.

### Steps taken to reproduce bug

I attempted to load an XDP program written in BPF assembler which assumes that the data pointers are 32 bit.

### Expected behavior

The program loads.

### Actual outcome

The verifier rejects the program.

**Comment by shankarseal** [comment]
eBPF for Windows promises source compatibility with Linux, and not binary compatibility. Please re-activate the issue if you are blocked on this @lmb. Issue #634 (assigned to @dthaler) will update the documentation around this.
