### ISSUE TITLE
ebpf_hash_table_update copies large buffer twice

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#390]
ebpf_hash_table_update copies the data twice, once before calling RtlInsertElementGenericTableAvl and then again after.   The second one makes sense if an existing entry was found.
It seems the first copy could be removed as it's redundant.

**Comment by Alan-Jowett** [comment]
Note:
This is obsoleted by https://github.com/microsoft/ebpf-for-windows/issues/387, which is being addressed in https://github.com/microsoft/ebpf-for-windows/pull/389

Per the commit message from the Linux side, the behavior of update is to atomically replace the old value with the new value.
```
Note that non-per-cpu hash map always allocates new element
and then deletes old after rcu grace period to maintain atomicity
of update. Per-cpu hash map updates element values in-place.
```

The new BPF_MAP_TYPE_HASH now atomically replaces the old hash-map entry with the new one.

**Comment by Alan-Jowett** [comment]
Closing this as the code is gone.
