### ISSUE TITLE
XDP_TX action support for XDP program types

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#397]
Currently XDP program type only supports XDP_PASS and XDP_DROP. This issue is to add support for XDP_TX return value.

The behavior for XDP_TX:

"The XDP_TX action result in TX bouncing the received packet-page back out the same NIC it arrived on. This is usually combined with modifying the packet contents before returning action XDP_TX."

**Comment by dthaler** [comment]
This is related to #125
