### ISSUE TITLE
Directory.Build.Props uses %(AdditionalOptions) instead of $(AdditionalOptions)

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#3992]
When expanding additional options, MSBuild only does replacement for $(AdditionalOptions) and not %(AdditionalOptions), so as a result subsequent additional options don't inherit correctly.

**Comment by shankarseal** [comment]
> Fixed by [#3991](https://github.com/microsoft/ebpf-for-windows/pull/3991)?

Indeed this PR should fix this issue.
