### ISSUE TITLE
Netsh show verification should work without EC and extension drivers.

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#420]
Developers of eBPF programs should be able to verify the program on their dev boxes without installing EC and extension drivers.

In long term, netsh show verification should take a URI parameter, which will point to some online database of program type information, that can be downloaded on demand and used for verification.

Short term, there has to be some mechanism (perhaps another netsh command) that can be run on a system that has extension driver installed to query the program type information, and persist the serialized buffer in a file that can be later used on a different box for verification.

Note: the API for verification/loading programs must always go through EC and query program types from installed extension drivers.

**Comment by Alan-Jowett** [comment]
Appears to have been fixed:
C:\privates>sc query ebpfcore

SERVICE_NAME: ebpfcore
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\privates>sc query netebpfext

SERVICE_NAME: netebpfext
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\privates>netsh ebpf show verification droppacket.o


Verification succeeded
Program terminates within 157 instructions
