### ISSUE TITLE
Consider adding functionality equivalent to Linux syscall BPF_PROG_TEST_RUN

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#462]
It looks like folks are using [BPF_PROG_TEST_RUN to measure the performance of eBPF on Linux](https://pchaigno.github.io/ebpf/2021/03/22/cost-bpf-tail-calls.html). This seems like it might be useful concept to adopt as it would permit side-by-side comparisons of BPF performance on the two platforms.

**Comment by dthaler** [comment]
@teknoraver Can you verify where the data comes from?  If it comes from the calling app or from the eBPF program, then how does the verifier know it is safe?

**Comment by teknoraver** [comment]
> @teknoraver Can you verify where the data comes from? If it comes from the calling app or from the eBPF program, then how does the verifier know it is safe?

both `data_in` and `data_out` are buffers supplied by userspace.
