### ISSUE TITLE
Suggestion: Add strict option to ebpf-verifier

### ISSUE THREAD

**Issue by pcy190** [microsoft/ebpf-for-windows#477]
When `ebpf_api_load_program()` call `load_byte_code()` for both parsing and verification of the program, we may need to add the 6th `.strict` parameter to initialize the `verifier_options` completely. Meanwhile, set `.strict` to true is necessary to reject the potential harmful program.

https://github.com/microsoft/ebpf-for-windows/blob/2aaa711f7d046f455e7e8a3de83f19b469357480/libs/api/ebpf_api.cpp#L730-L731

We could set `verifier_options` to 
```
ebpf_verifier_options_t verifier_options{false, false, false, false, false, true};
```

**Comment by dthaler** [comment]
@pcy190  The strict parameter does not affect safety, it checks additional things that would fail at runtime, to help the eBPF program developer catch bugs that would cause runtime functions to return failure.  For example, passing an index > max_entries to bpf_map_lookup_elem will return a failure, but is still safe.

Can you provide more info on what you would want to see here, given it is still safe?

**Comment by pcy190** [comment]
> it checks additional things that would fail at runtime, to help the eBPF program developer catch bugs that would cause runtime functions to return failure.

I agree, the strict parameter doesn't affect the safety.
