### ISSUE TITLE
Refactor tests in ebpf_performance

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#479]
Test cases in ebpf_performance have grown organically over time. We should refactor them to make them more uniform and easier to understand.

**Comment by dthaler** [comment]
@Alan-Jowett if you can provide details we might be able to add "good first issue" on this one.

**Comment by Alan-Jowett** [comment]
Some tests cover the following functionality:
1) Epoch tracking code.
2) Lock-free hash-table.
3) State tracking table. (Planned)
4) BPF helper functions.
5) Running a BPF program.
6) Run programs in kernel mode. (Planned / #462)

They are currently intermixed within [performance.cpp](https://github.com/microsoft/ebpf-for-windows/blob/master/tests/performance/performance.cpp).

It would probably make sense to break this apart into the following groups:
1) Tests that cover the core platform abstraction layer (hashtable, epoch tracking, and state tracking).
2) Tests that cover the execution context (BPF helper functions, invoke path tests, and others TBD)
3) Tests that cover the end-to-end scenario of loading and running a BPF program.

Then tag the tests using catch2's tagging system so that specific functional groups can be tested without the need to run all the tests.
