### ISSUE TITLE
sample_ext_app.exe system crash

### ISSUE THREAD

**Issue by dbarac** [microsoft/ebpf-for-windows#489]
Hello,

after following the instructions for building and installing eBPF programs (with the OS running in test-signing mode),
I tried running the tests. Running `sample_ext_app.exe` crashed the system with the stop code `IRQ_NOT_LESS_OR_EQUAL`.

Adding `"sample_ebpf_ext.sys"` to the `built_files` array in [scripts/deploy-ebpf.ps1](https://github.com/microsoft/ebpf-for-windows/blob/master/scripts/deploy-ebpf.ps1#L8) seems to fix the issue.
After re-running the [deploy-ebpf.ps1](https://github.com/microsoft/ebpf-for-windows/blob/master/scripts/deploy-ebpf.ps1) and [install-ebpf.bat](https://github.com/microsoft/ebpf-for-windows/blob/master/scripts/install-ebpf.bat) scripts, `sample_ext_app.exe` worked with no crash.

Should I create a PR for this fix?

@jvijtiuk @lperkov

**Comment by dthaler** [comment]
@shankarseal Can you look at this?

**Comment by shankarseal** [comment]
Thanks for catching this @dbarac . Can you please create the PR with the fix ?

**Comment by dbarac** [comment]
@shankarseal Sure, here's the pull request: [#494](https://github.com/microsoft/ebpf-for-windows/pull/494)
