### ISSUE TITLE
Require approval on CI/CD runs for external contributors

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#495]
We should set this policy:
https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/disabling-or-limiting-github-actions-
for-a-repository#configuring-required-approval-for-workflows-from-public-forks

If we do this, we can safely support adding self-host runners to our CI/CD pipeline and run tests that load unsigned kernel drivers.

**Comment by dthaler** [comment]
I just checked and the repo is already configured to do this.
