### ISSUE TITLE
ebpfcore.sys should load on Windows version 17763 (not just 19041)

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#506]
EbpfCore takes a dependency on an API that is only present in 19041+, but Server 2019 ships with 17763.

As a result, EbpfCore doesn't work on public Server SKU's of Windows.

**Comment by dthaler** [comment]
Our main readme says "Windows Server 2016" not 2019.  What build should we be targeting for 2016?

**Comment by Alan-Jowett** [comment]
We should add this to the https://github.com/microsoft/ebpf-for-windows/blob/master/.github/workflows/driver_test.yml test matrix and setup 2 self-hosted runners, one on Server 2016 and one on Server 2019.
