### ISSUE TITLE
Kernel CI/CD pipeline should upload crash dumps + symbols as workflow artifacts.

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#530]
Kernel CI/CD pipeline should cache pdb's for drivers.

Symbols are needed to debug kernel mode crashes.

The following command will create a local symcache on the CI/CD machine:
```c:\debuggers\SymChk.exe -v *.sys -s cache*c:\symbols;.```

**Comment by dthaler** [comment]
Can you provide more information about how to use this to debug kernel mode crashes?

**Comment by Alan-Jowett** [comment]
To use the symbol cache, you can do the following
```windbg -z memory.dmp -y SRV*;cache*c:\symbols```

What the symchk command does is to copy the PDB files to a sub-directory under the c:\symbols\image_name\GUID where the guid uniquely identifies the version of the PE file.

The debugger can then find the pdb file by searching that directory.

Long term, we might need to create  scavenger to remove older symbols from the symbol cache to conserve disk space.

**Comment by dthaler** [comment]
> To use the symbol cache, you can do the following
> `windbg -z memory.dmp -y SRV*;cache*c:\symbols`
> 
> What the symchk command does is to copy the PDB files to a sub-directory under the c:\symbols\image_name\GUID where the guid uniquely identifies the version of the PE file.
> 
> The debugger can then find the pdb file by searching that directory.
> 
> Long term, we might need to create scavenger to remove older symbols from the symbol cache to conserve disk space.

I'd expect a markdown file with the relevant info to be in a PR

**Comment by Alan-Jowett** [comment]
I think the right solution is to assume developers have no access to the kernel CI/CD machine. 

At the conclusion of the Kernel CI/CD flow, it should upload the drivers + symbols + crash dump if the workflow failed, similar to what is done for user mode CI/CD pipeline.

**Comment by dthaler** [comment]
@Alan-Jowett crash dumps are uploaded, and symbols are available in the artifacts consumed by the CI/CD test workflow.  Is there anything remaining before closing this issue?

**Comment by Alan-Jowett** [comment]
Nope. We can close this.
