### ISSUE TITLE
Add support for BPF_MAP_TYPE_LPM_TRIE map type

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#560]
Add support for BPF_MAP_TYPE_LPM_TRIE map type.

Behavior is as follows:
1) Key is a composite of uint32_t length + bytes of the key.
2) Find matches the entry with the longest number of matching bits.
3) Minimum key length is 8 bits, maximum key length is 8192 bits.

**Comment by dthaler** [comment]
According to https://github.com/iovisor/bcc/blob/master/tests/python/test_lpm_trie.py (Apache licensed), the key struct be a struct containing a 32-bit prefix length, followed by the actual prefix, padded to the maximum key size.

Other docs:
- https://www.ferrisellis.com/content/ebpf_syscall_and_maps/#bpf_map_type_lpm_trie
- https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#9-bpf_lpm_trie
- https://blog.apnic.net/2020/10/23/journeying-into-xdp-augmenting-the-dns/

**Comment by dthaler** [comment]
Initial version done in #565
