### ISSUE TITLE
eBPF for Windows project logo

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#561]
Projects at https://ebpf.io/projects are shown with their logo.  The eBPF for Windows project doesn't have a logo yet.

**Comment by dahavey** [comment]
I drew a concept version of the logo and reached out to legal to determine what permissions are needed to use the logo. Thank you Matteo for the beautifully colorized version of the eBPF bee!

**Comment by dahavey** [comment]
We are currently working to understand whether or not the original eBPF bee is public domain or if we need permission to use it in our own logo.

**Comment by dahavey** [comment]
Narrowed down to three choices. Also need to check with (Justin) CELA.

**Comment by dthaler** [comment]
https://www.canva.com/learn/what-makes-a-good-logo/

See design tip 5 in particular, for what I was talking about on the call.

**Comment by dahavey** [comment]
We have chosen a logo! By popular vote our new logo is:
SVG:
![eBPF logo svg 800px](https://user-images.githubusercontent.com/22178676/158223145-b0fd4151-41e9-4fc3-8b0d-0bf3c37fc772.svg)
PNG:
![eBPF logo png 800px](https://user-images.githubusercontent.com/22178676/158223273-77b2f68f-1a40-4f53-82bc-21ec4e2a6944.png)
PDF:
[eBPF logo pdf 800px.pdf](https://github.com/microsoft/ebpf-for-windows/files/8247018/eBPF.logo.pdf.800px.pdf)

**Comment by dthaler** [comment]
Please open a pull request that adds the logo files into the repo and uses the logo on the main page.
