### ISSUE TITLE
Workflow to run CICD Tests in a VM on a selfhost runner

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#621]
### Discussed in https://github.com/microsoft/ebpf-for-windows/discussions/448

<div type='discussions-op-text'>

<sup>Originally posted by **Alan-Jowett** August 27, 2021</sup>
We need some mechanism to be able to validate the kernel-mode eBPF core in the CI/CD pipeline.

Proposed workflow:
1) Existing MSBuild workflow runs and uploads build output artifact.
2) Only code owner can then trigger new workflows "Kernel_CICD".
3) Kernel_CICD is marked as [requiring a self-host runner](https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow).

eBPF for Windows team will then maintain a pool of VMs with the [self-host runner](https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners), with driver verifer enabled and test signing enabled. 

Kernel_CICD will perform the following steps:
1) [actions/download-artifact@v2](https://github.com/actions/download-artifact)
2) install-ebpf.bat.
3) Run netsh tests.
4) Run port_quota.exe tests (load, limit, stats, unload).
</div>

**Comment by dthaler** [comment]
@shankarseal Please update title

**Comment by dthaler** [comment]
Moving to 2111 since #622 says it was only part of the fix.

**Comment by shankarseal** [comment]
Closing issue as workflows targeting selfhosted runners is live.
