### ISSUE TITLE
netsh ebpf show disassembly should also show the corresponding C code (if available)

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#630]
llvm-objdump when used with "-S" option dumps the original C code along with the disassembly. That makes it easier to find out the corresponding C code when verification fails.

netsh ebpf show disassembly can also possibly have similar feature to dump this info, if the .o is compiled using "-g" flag, and the source file is available.

**Comment by dthaler** [comment]
The disasm.c file mentioned above does not deal with source line information.  Source line information is encoded in the ".debug_line" section using a sequence of operations viewable via "readelf -wl <filename>".

**Comment by dthaler** [comment]
bpftool and libbpf also have BTF parsing functionality and so it may be possible to use libbpf APIs?

**Comment by Alan-Jowett** [comment]
I think the right solution here is to do this in the verifer. It decodes the instructions into a vector of LabeledInstruction, which we can augment with line info that it came from.

Netsh uses the prevail function [print](https://github.com/vbpf/ebpf-verifier/blob/222214bef0eec4a56ff5b9fd8ed668cd3fb42e0d/src/asm_ostream.cpp#L360) to generate the disassembly, so I think it makes more sense to put it into prevail. 

https://github.com/vbpf/ebpf-verifier/issues/301

**Comment by dthaler** [comment]
Agree with Alan's comment above.  So updating this to be blocked on https://github.com/vbpf/ebpf-verifier/issues/301 and once that is done, then we can update tutorial.md accordingly.  This issue is now the documentation issue for doing that once the functionality is there.
