### ISSUE TITLE
CI/CD pipeline broken by failure to upload build output

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#691]
Container for artifact "Build x64 Debug" successfully created. Starting upload of file(s)
Error: Unexpected response. Unable to upload chunk to https://pipelines.actions.githubusercontent.com/eYokHsiyUgkTvpuaVsIXahob1lqD1Q84LS3b9LsFqZB2ZffrLc/_apis/resources/Containers/6765156?itemPath=Build+x64+Debug%5Capi.lib.lastcodeanalysissucceeded
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "transfer-encoding": "chunked",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "0eecd9d0-df41-4552-934c-7e380ec77176",
  "activityid": "6c51a320-e142-4989-91bb-4a2edaa67706",
  "x-tfs-session": "6c51a320-e142-4989-91bb-4a2edaa67706",
  "x-vss-e2eid": "6c51a320-e142-4989-91bb-4a2edaa67706",
  "x-vss-senderdeploymentid": "ac98198d-4d34-0364-420d-bafa6e51dce2",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: 8C48BEE1024746568F55280C360EF33F Ref B: STBEDGE0119 Ref C: 2021-12-13T16:27:44Z",
  "date": "Mon, 13 Dec 2021 16:27:43 GMT"
}
###### End Diagnostic HTTP information ######
Warning: Aborting upload for D:\a\ebpf-for-windows\ebpf-for-windows\x64\Debug\api.lib.lastcodeanalysissucceeded due to failure
Error: aborting artifact upload
Total size of all the files uploaded is 1098982 bytes

**Comment by dahavey** [comment]
https://github.com/actions/upload-artifact/issues/281

The workaround is to switch to v2.2.4:

- uses: actions/upload-artifact@v2
+ uses: actions/upload-artifact@v2.2.4

**Comment by dthaler** [comment]
Fixed by PR #694
