### ISSUE TITLE
Catchorg.catch framework is incompatible with Visual Studio AddressSanitizer

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#696]
https://github.com/catchorg/Catch2/issues/2332

Summary:
Catch2 incorrectly marks tests as failed when a test raises and handles a 0xC0000005 exception.

```
#define CATCH_CONFIG_MAIN

#include <iostream>
#include <Windows.h>
#include "catch2\catch.hpp"

void throw_and_catch()
{
    __try {
        RaiseException(0xC0000005, 0, 0, NULL);
    }
    __except (1)
    {

    }
}


TEST_CASE("foo", "[bar]")
{
    throw_and_catch();
}
```
The problem is that Visual Studio's Address Sanitizer logic uses 0xC0000005 exceptions as part of it's logic to test for when address are written / read.

**Comment by dthaler** [comment]
@Alan-Jowett now that https://github.com/catchorg/Catch2/pull/2334 has been merged, what do we need to do now to resolve this issue?  Do we need to wait until some future catch2 nuget release?

**Comment by Alan-Jowett** [comment]
We are currently consuming Catch2 via a NuGet package that contains version 2.8.0, but the change was made in the version 3.0 preview branch. 

We can do one of the following:
1) Get this fix back-ported to the v2.x branch and get a new NuGet package published.
2) Wait for v3.0 to be released as a NuGet package.
2) Switch to consuming v3.0 preview via a git submodule.

**Comment by Alan-Jowett** [comment]
Note: Once this is complete we should add a AddressSanitizer pass to the CI/CD pipeline.

**Comment by Alan-Jowett** [comment]
To add Catch2 as a git submodule, we need to get this PR merged:
https://github.com/catchorg/Catch2/pull/2389

**Comment by dthaler** [comment]
Might there be some projects that use two different catch2 projects that thus need different GUIDs?
Should that be disallowed or should there be some way to override the constant guid with another constant guid?

**Comment by Alan-Jowett** [comment]
Added address sanitizer workflow.
