### ISSUE TITLE
fatal error C1083

### ISSUE THREAD

**Issue by kouzhudong** [microsoft/ebpf-for-windows#703]
ebpf-for-windows\tools\elfhelper\ElfHelper.cpp(10,10): fatal error C1083: 无法打开包括文件: “CLI11.hpp”: No such file or directory

**Comment by dthaler** [comment]
@kouzhudong That error would typically show up if you failed to specify `--recurse-submodules` as shown in https://github.com/microsoft/ebpf-for-windows/blob/master/docs/GettingStarted.md#cloning-the-project

Can you check?

**Comment by dahavey** [comment]
We think this question has been answered. Please reopen if you have further questions.
