### ISSUE TITLE
Does not build on Windows Server 2016

### ISSUE THREAD

**Issue by jayhoughton** [microsoft/ebpf-for-windows#704]
Turned up a fresh EC2 on AWS with Windows Server 2016, followed the [Getting Started](https://github.com/microsoft/ebpf-for-windows/blob/master/docs/GettingStarted.md) procedure verbatim. Everything looked good until the `msbuild` step. First issue was a dialog that said:
```
The procedure entry point VirtualAlloc2 could not be located in the dynamic link library C:\Users\Administrator\git\ebpf-for-windows\x64\Debug\encode_program_info.exe
```
Then the build failed after dismissing the dialog with:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found. To build using the WindowsKernelModeDriver10.0 build tools, please install WindowsKernelModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\Administrator\git\ebpf-for-windows\libs\ubpf\kernel\ubpf_kernel.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found. To build using the WindowsKernelModeDriver10.0 build tools, please install WindowsKernelModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\Administrator\git\ebpf-for-windows\libs\execution_context\kernel\execution_context_kernel.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(286,5): error MSB3073: The command "cd /d C:\Users\Administrator\git\ebpf-for-windows\x64\Debug\ [C:\Users\Administrator\git\ebpf-for-windows\tools\encode_program_info\encode_program_info.vcxproj]C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(286,5): error MSB3073: C:\Users\Administrator\git\ebpf-for-windows\x64\Debug\encode_program_info.exe [C:\Users\Administrator\git\ebpf-for-windows\tools\encode_program_info\encode_program_info.vcxproj] C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(286,5): error MSB3073: :VCEnd" exited with code -1073741511. [C:\Users\Administrator\git\ebpf-for-windows\tools\encode_program_info\encode_program_info.vcxproj]
```
Maybe Windows Server 2016 isn't supported with this procedure?

Visual Studio details:
```
Microsoft Visual Studio Community 2019
Version 16.11.8
VisualStudio.16.Release/16.11.8+32002.261
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA081
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.94.52318
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.11.94.52318
Azure App Service Tools v3.0.0

C# Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Debugging Tools for Windows   10.0.19030.1000
Integrates the Windows Debugger functionality (http://go.microsoft.com/fwlink/?linkid=223405) in Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Windows Driver Kit   10.0.19030.1000
Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)
```

**Comment by Alan-Jowett** [comment]
Will take a look. Bear in mind that Server 2016 reaches the end of mainstream support on 1/11/2022, so you might want to consider switching to Server 2019 or Windows 11.

https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2016

**Comment by Alan-Jowett** [comment]
Can you provide more details on how you managed to install this? I am unable to install VS 2019 on Server 2016 at all.

Install of .NET redistributable fails with:
```x800f081e | -2146498530 | CBS_E_NOT_APPLICABLE | the package is not applicable```

**Comment by Alan-Jowett** [comment]
Building it on a Windows 11 machine and attempting to deploy it on Server 2016 also fails due to missing entry points. Looks like Server 2016 is not supported. We should update the docs to reflect this.

**Comment by jayhoughton** [comment]
> Server 2016 reaches the end of mainstream support on 1/11/2022

Right, I was going for the earliest supported version that was documented here, with the idea that I'd eventually be able to produce apps for clients/customers that ran old servers.

> provide more details on how you managed to install this

I clicked through to the "older downloads" ending up [on this page](https://visualstudio.microsoft.com/vs/older-downloads/), then downloading the product entitled "Visual Studio Professional 2019 (version 16.11)" as indicated by the [getting started guide](https://github.com/microsoft/ebpf-for-windows/blob/master/docs/GettingStarted.md#prerequisites).

> Server 2016 is not supported. We should update the docs to reflect this.

Probably, might not be worth fixing. I'm not stuck on 2016 since folks should upgrade anyways, and by the time I'm ready things may have changed. I wonder how this was working on 2016 at all, maybe a long time ago.

**Comment by Alan-Jowett** [comment]
As the project evolved, we have switched to newer versions of the Windows SDK and are currently on the 22000 version of the Windows SDK. It's been a while since we tested Server 2016 and apparently, it broke after one of the SDK version updates. 

The one thing that doesn't make sense though is the message about not finding [VirtualAlloc2](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc2). According to the docs that should be supported on Server 2016. 

encode_program_info.exe is a command-line tool that generates the RPC serialized version of the program information descriptors for the bind and XDP attach points. It runs as part of the build process to produce "ebpf_bind_program_data.h" and "ebpf_xdp_program_data.h" header files containing the serialized program info.

It appears to run fine when copied to my Server 2016, version:
```
reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v BuildLabEx

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    BuildLabEx    REG_SZ    14393.4886.amd64fre.rs1_release.220104-1735
``` 

Can you double-check the OS version you are running on?

**Comment by jayhoughton** [comment]
Makes sense. I did try reinstalling WDK a few times, to no effect. I did see the `encode_program_info.exe` part and tried to dive deeper into the build process. I'm guessing I'm probably the only one doing this on 2016. My version is below.

```
C:\Users\Administrator>reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v BuildLabEx

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    BuildLabEx    REG_SZ    14393.4825.amd64fre.rs1_release.211202-1611

```

**Comment by dthaler** [comment]
See https://github.com/MicrosoftDocs/feedback/issues/1129 for more details

**Comment by Alan-Jowett** [comment]
Looks like the VirtualAlloc2 call is from this change https://github.com/microsoft/ebpf-for-windows/pull/606 where I added support for ring-buffers.

**Comment by dthaler** [comment]
While we could deal with the lack of VirtualAlloc2 since it's only used in the test pass running using usermode emulation, not for real ebpf kernel mode functionality, we propose to drop Server 2016 from the list of supported platforms now since:

1) Server 2016 ended mainstream support on Jan. 11, 2022 as Alan noted earlier and documented at https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2016
2) We use github for CI/CD and the Server 2016 github environment uses VS 2017 not VS 2019 (https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md) and this project already requires VS 2019.   This means we cannot easily test new PRs on an ongoing basis on Server 2016.
3) Github will remove its existing Server 2016 support on March 15, 2022 (https://github.com/actions/virtual-environments/issues/4312)
4) eBPF for Windows isn't used in production yet since the drivers aren't production signed, so we don't need to worry about breaking any production uses on Server 2016

I will create a PR to update the docs.
