### ISSUE TITLE
Support for BPF_PROG_TEST_RUN

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#715]
Documentation:
* https://www.kernel.org/doc/html/latest/userspace-api/ebpf/syscall.html
* https://lwn.net/Articles/718784/
* https://www.mankier.com/8/bpftool-prog ("prog run" command)

**Comment by dthaler** [comment]
@qmonnet Any insights you can provide here about how Linux prevents invalid pointers in the context?

**Comment by dthaler** [comment]
@song-jiang Any thoughts on how important/urgent this need is?

**Comment by qmonnet** [comment]
The feature is not available to all program types. It's available for most networking-related types, and has been enabled more recently for a few tracing program types. I haven't looked at the details for tracing-related test runs.

For networking, you can pass an input context (typically representing the `struct __sk_buff` for most types) and set some fields in this context.

Currently (bpf-next), the fields from `struct __sk_buff` that are allowed to be set as part of the input context are: `mark`, `priority`, `ingress`, `ifindex`, `cb` (array), `tstamp`, `wire_len`, `gso_segs`, `gso_size`, `hwtstamp`. I found them by looking at the code and I don't think the list is documented. Pointers such as `data` and `data_end`, or all other fields not mentioned above, _cannot_ be set, and must remain at zero. Those pointers are automatically computed by the kernel to point to the user-provided data before running the program.

**Comment by dthaler** [comment]
Discussion: add as part of extension contract for a hook/program type to allow them to register a checker function.  If not registered, TEST_RUN will fail for that program type.  If registered, then TEST_RUN will call the extension's checker for that program type before invoking program.

**Comment by song-jiang** [comment]
> Any thoughts on how important/urgent this need is?
Calico uses it for test only, so we can live without it for now. @dthaler
