### ISSUE TITLE
Write a package installer to make it easy for folks to install the eBPF driver, service and the extension 

### ISSUE THREAD

**Issue by poornagmsft** [microsoft/ebpf-for-windows#717]
The goal is to make it easy for folks to play with the infrastructure where they only need to write the ebpf programs at the xdp or the bind hooks for example. 
They set the testsigning mode on, double click the installer and get going as a result of this work.

**Comment by dthaler** [comment]
Two parts to this issue:
- [ ] Generate MSIX as part of the build
- [ ] Make the KM tests actually install the MSIX (instead of zip + scripts today)

**Comment by rob-scheepens** [comment]
Perhaps use MSIX since MSI is deprecated by now? See https://docs.microsoft.com/en-us/windows/msix/overview.

Also, having it packaged in Chocolatey would be useful.

**Comment by dthaler** [comment]
> Perhaps use MSIX since MSI is deprecated by now? See https://docs.microsoft.com/en-us/windows/msix/overview.

https://docs.microsoft.com/en-us/windows/msix/packaging-tool/tool-known-issues explains "MSIX currently does not support driver installation." so MSIX is not an option.

**Comment by dthaler** [comment]
@dthaler reassign to [alessandrogario](https://github.com/alessandrogario) to work on, thanks Alessandro!

**Comment by dthaler** [comment]
Initial installer is done, issue #1037 covers the remainder of this work.
