### ISSUE TITLE
ELF files passed from low-trust processes to eBPF service should be validated using EverParse

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#756]
EverParse team created a [.3d specification for the ELF format,](https://github.com/project-everest/everparse/blob/master/src/3d/tests/ELF.3d) which can be used to securely verify the eBPF ELF file being passed to the eBPF service.

**Comment by dthaler** [comment]
This is related to #709 which is about user-to-kernel calls, where this issue is about app-to-service calls.

**Comment by aseemr** [comment]
Thanks for starting the discussion Alan. We also have some [documentation](https://project-everest.github.io/everparse/3d-lang.html#fully-worked-examples-elf-files) on the EverParse ELF specification, and how to integrate it in existing applications.

**Comment by Alan-Jowett** [comment]
This is implemented as part of https://github.com/microsoft/ebpf-for-windows/pull/1219.
