### ISSUE TITLE
Kernel mode components should be compiled with appropriate flags to reduce spectre attacks

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#758]
Flags include:
 /Qspectre 
 /Qspectre-load 
 /Qspectre-load-cf 
 /guard:cf

**Comment by dthaler** [comment]
These are MSVC options for our drivers.

**Comment by Alan-Jowett** [comment]
This is blocked on: https://github.com/microsoft/ebpf-for-windows/issues/594

To be able to make an accurate assessment of the performance impact we need more realistic workloads to test this against.

**Comment by dthaler** [comment]
@Alan-Jowett it looks like netebpfext.vcxproj, EbpfCore.vcxproj, execution_context_kernel.vcxproj, platform_kernel.vcxproj, ubpf_kernel.vcxproj, sample_ext.vcxproj, and kernel_mode_bpf2c.vcxproj currently all have
```
<Driver_SpectreMitigation>Spectre</Driver_SpectreMitigation>
```

Is that sufficient for this issue? or what is missing still?
