### ISSUE TITLE
Apply access check when opening a previously pinned program

### ISSUE THREAD

**Issue by poornagmsft** [microsoft/ebpf-for-windows#76]
@shankarseal fyi

**Comment by Alan-Jowett** [comment]
Looks like the functions to convert SDDL -> SECURITY_DESCRIPTOR aren't in the DDK. Are we ok with passing a self-relative SECURITY_DESCIPTOR instead of an SDDL?

**Comment by Alan-Jowett** [comment]
The EbpfIoDevice device object is restricted to:
```
//
// SDDL_DEVOBJ_SYS_ALL_ADM_ALL allows the kernel, system, and admin complete
// control over the device. No other users may access the device
//
```

So adding an additional access check here is redundant.

**Comment by Alan-Jowett** [comment]
Closing this as an additional access check is pointless given that this API can only be called by admin, kernel or local system.

If we ever loosen the restrictions on the device object, revisit this.
