### ISSUE TITLE
bpf2c should invoke prevail verifier prior to emitting code

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#768]
The bpf2c tool should invoke the prevail verifier and only emit C code if the BPF code is provably safe.

**Comment by dthaler** [comment]
This issue to me sounds like an optimization, since for safety a signing mechanism will want to re-run verification as part of the signing process and not simply trust code submitted for signing.   So running it before may help catch things earlier in the development cycle but isn't a substitute for the other.

**Comment by Alan-Jowett** [comment]
The execution context needs a collection of metadata from the verifier to determine if the program is safe to run.

Information includes:
1) Verifier version 
2) Hook function data
3) Helper function data

Note: This is implicitly shared today because the verifier queries it from the execution context. 

In the future it might in include the control flow graph from the verifier or possibly verification certificate that Elazar mentioned. 

In addition the code gen flow is:
Verification -> Code Gen -> Compiler -> Linker -> Signing.

I think by combining verification, code gen, and the skeleton we can simplify it.

Bpf2c -> Compile + Link (single c file) -> sign.

**Comment by saxena-anurag** [comment]
For program load to work, there are 2 pieces of information still missing from what is generated by bpf2c tool.
- [ ] program and attach type for each section
- [ ] program type for each helper ID

Regarding first information above, bpf2c can itself parse the section names and figure out the corresponding program type and attach type. But we should ideally emit the program type which was actually used by the verifier for verification.
Similarly for the second information above, bpf2c can either parse the section name to get the program type or use the one determined by the verifier step.

**Comment by saxena-anurag** [comment]
Closing this issue as this is fixed by PR #961
