### ISSUE TITLE
Add tests for bpf2c_driver.c and bpf2c_dll.c

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#775]
There should be tests for [bpf2c_driver.c](https://github.com/microsoft/ebpf-for-windows/blob/master/tools/bpf2c/bpf2c_driver.c) and [bpf2c_dll.c](https://github.com/microsoft/ebpf-for-windows/blob/master/tools/bpf2c/bpf2c_dll.c).

**Comment by dthaler** [comment]
Blocked on issue to be filed by @saxena-anurag

**Comment by saxena-anurag** [comment]
This issue has 2 parts:

- [ ] Tests for driver stub - covered by adding tests in PR #811
- [ ] Tests for DLL stub - covered by tests added in PR #953
