### ISSUE TITLE
ebpfclient : API surface for prog load, attach, maps, pinning, query

### ISSUE THREAD

**Issue by poornagmsft** [microsoft/ebpf-for-windows#81]
@saxena-anurag

**Comment by dthaler** [comment]
Still missing APIs for:
* Detach without unloading (blocks #191)
* Unpin without unloading or detaching (blocks #190)
* ...

**Comment by saxena-anurag** [comment]
Actually many more APIs are remaining as per the API doc.

**Comment by dthaler** [comment]
The main items were done, moving the remaining items to a separate (smaller in scope) issue to track
