### ISSUE TITLE
Program information returned from extensions should be strongly typed

### ISSUE THREAD

**Issue by poornagmsft** [microsoft/ebpf-for-windows#82]
@shankarseal

**Comment by dthaler** [comment]
@Alan-Jowett please add description as discussed in triage meeting

**Comment by Alan-Jowett** [comment]
The contract between extension and EbpfCore.sys is to pass the program type information as an opaque blob that is interpreted by the eBPF service. 

The ask is to pass this as a strongly typed pointer and have EbpfCore.sys serialize the program type information.
