### ISSUE TITLE
netsh tool: swap netsh helpers to call into ebpfapi.dll

### ISSUE THREAD

**Issue by poornagmsft** [microsoft/ebpf-for-windows#83]
@saxena-anurag

**Comment by dthaler** [comment]
Currently netsh helpers call directly into "internal" APIs exposed by static libs loaded in proc, rather than across the public API surface area that would have libbpf API compat.  This issue is to address that.,

**Comment by dthaler** [comment]
This was already done, but apparently wasn't closed at the time, so closing it now.
