### ISSUE TITLE
README FAQ is out of date - Interpreter mode is now disabled

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#831]
https://github.com/microsoft/ebpf-for-windows/blob/main/README.md

FAQ says we support HVCI with interpreter mode, but interpreter mode is now disabled on release builds.

**Comment by dahavey** [comment]
We support interpreter only in debug mode

**Comment by dahavey** [comment]
#794 Add EC to docs

**Comment by dahavey** [comment]
PR not linked. Manually closing.
