### ISSUE TITLE
Need documentation for all program types and attach types implemented by netebpfext

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#860]
A MD document should be written for each program type and attach type supported by net ebpf extension. The document should list for each program type:
- What is this program type used for.
- How are they attached and the relevant attach types.
- When are the programs invoked.
- Any delta from Linux.

**Comment by dthaler** [comment]
I disagree that it should be in MD.   We already have doxygen markup in https://github.com/microsoft/ebpf-for-windows/blob/main/include/ebpf_program_attach_type_guids.h from which https://microsoft.github.io/ebpf-for-windows/ebpf__program__attach__type__guids_8h.html is automatically generated.

So I think the docs should just be done in doxygen not MD

**Comment by dthaler** [comment]
https://microsoft.github.io/ebpf-for-windows/ebpf__structs_8h.html#a0f8242763b15ec665eaa47c6add861a0a2af8d41961c186b1a62fcc54a29446d2 is missing documentation on `BPF_PROG_TYPE_XDP` etc.
