### ISSUE TITLE
Remove dependency on Linux build for bpf2c-tests

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#870]
### Describe the bug

Currently bpf2-tests is built on Linux, as it uses Python, and that is not working on Windows. This issue to track removing dependency on Linux build once Python issue is resolved.

### Affected OS

- [ ] Windows Server 2022
- [ ] Windows Server 2019
- [ ] Windows 11
- [ ] Windows 10
- [ ] Windows Insider Preview (specify affected build below)
- [ ] Other (specify below)

### Steps taken to reproduce bug

NA

### Expected behavior

NA

### Actual outcome

NA

**Comment by Alan-Jowett** [comment]
When generating byte code from jeq-imm.data there is a difference in behavior between Python on Windows vs Python on Linux:

Input assembly
```
alanjo@alanjo-dev:/mnt/e/ebpf-for-windows/x64/Debug$ cat jeq-imm.data.asm
mov32 r0, 0
mov32 r1, 0xa
jeq r1, 0xb, +4
mov32 r0, 1
mov32 r1, 0xb
jeq r1, 0xb, +1
mov32 r0, 2
exit
```

Linux generated byte code:
```
alanjo@alanjo-dev:/mnt/e/ebpf-for-windows/x64/Debug$ hexdump jeq-imm.data.bc.linux
0000000 00b4 0000 0000 0000 01b4 0000 000a 0000
0000010 0115 0004 000b 0000 00b4 0000 0001 0000
0000020 01b4 0000 000b 0000 0115 0001 000b 0000
0000030 00b4 0000 0002 0000 0095 0000 0000 0000
0000040
```

Windows generated byte code:
```
alanjo@alanjo-dev:/mnt/e/ebpf-for-windows/x64/Debug$ hexdump jeq-imm.data.bc.windows
0000000 00b4 0000 0000 0000 01b4 0000 0a0d 0000
0000010 1500 0401 0b00 0000 b400 0000 0100 0000
0000020 b400 0001 0b00 0000 1500 0101 0b00 0000
0000030 b400 0000 0200 0000 9500 0000 0000 0000
*
0000041
```

**Comment by dthaler** [comment]
Linux has LF (0a) in first line and WIndows has LFCR (0a0d) so this is a line ending issue.

**Comment by Alan-Jowett** [comment]
Python automatically converts LF --> CRLF on Windows.

The net result is that:
```
mov32 r1, 0xa
```
Gets correctly encoded, but then Python converts the immediate value of '0xa' into 2 bytes.
