### ISSUE TITLE
Code coverage excludes sub-modules on codecov.io

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#885]
Code coverage numbers generated by OpenCppCoverage include git sub-modules, but the numbers shown on codecov.io exclude submodules.

**Comment by dthaler** [comment]
Oddly issue #927 is related in that simply updating a submodule causes a codecov failure today.  So it's "mostly" excluded in a bad way.

**Comment by Alan-Jowett** [comment]
Not clear what the issue here is. Code coverage is excluded for catch2, which is by design.
