### ISSUE TITLE
bpf2c: make maps parser match verifier's maps parser

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#900]
### Describe the feature you'd like supported

As noted in https://github.com/microsoft/ebpf-for-windows/pull/883

In https://github.com/vbpf/ebpf-verifier/pull/295 I put a more intelligent algorithm for determining the map definition size in the file in https://github.com/vbpf/ebpf-verifier/blob/master/src/asm_files.cpp#L79 which is the algorithm already used by libbpf.

### Proposed solution

bpf2c should change to use that algorithm, which supports older (smaller) structures by 0-padding the rest of the fields, for example by having a common implementation rather than reimplementing the parsing logic.

**Comment by Alan-Jowett** [comment]
We should consider refactoring the code that parses ELF files into a form that can be used by both ebpf-verifier and bpf2c.
