### ISSUE TITLE
Codecov checks are too restrictive today

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#927]
### Describe the bug

Example: https://github.com/microsoft/ebpf-for-windows/pull/925 simply bumped the commit on codecov itself, and codecov entered a failing check saying:
```
codecov/project — 82.86% (-0.07%) compared to 9218004
```

Failing this PR seems silly.

### Affected OS

- [ ] Windows Server 2022
- [ ] Windows Server 2019
- [ ] Windows 11
- [ ] Windows 10
- [ ] Windows Insider Preview (specify affected build below)
- [ ] Other (specify below)

### Steps taken to reproduce bug

Repro happens automatically whenever a PR is filed.

### Expected behavior

Codecov should treat such things as passing even if the percentage goes down slightly.

### Actual outcome

PR is marked as failing CI/CD (though the check is not marked as required so doesn't block merging).

**Comment by Alan-Jowett** [comment]
Fixed as part of #933
