### ISSUE TITLE
Support native program load with bpf_object__open_file() / bpf_object__load()

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#951]
### Describe the feature you'd like supported

Currently native programs are loaded using `ebpf_program_load` / `bpf_prog_load` API.

We should also support loading native programs using `bpf_object__open_file()` / `bpf_object__load()` APIs

### Proposed solution

support loading native programs using `bpf_object__open_file()` / `bpf_object__load()` APIs

**Comment by dthaler** [comment]
Blocked on issue #1073

**Comment by dthaler** [comment]
Tasks:
- [ ] Make bpf_object__open_file() work on a .sys file, based on the logic in #1070
- [ ] Add support for bpf_object__open()
- [ ] Make bpf_object__load() work with a native object
