### ISSUE TITLE
LLVM version

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#962]
@Alan-Jowett in https://github.com/microsoft/ebpf-for-windows/issues/959#issuecomment-1100162015_:
> There are bug fixes between LLVM 10 and LLVM 13 where LLVM 10 generates incorrect debug info with wrong line numbers.

However, currently we use LLVM 10 in multiple places, including at least:
* docs/GettingStarted.md:  5. [Clang for Windows 64-bit version 10.0.0](https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe) or [The latest release of Clang for Windows 64-bit](https://github.com/llvm/llvm-project/releases/latest)
* scripts/format-code:    local required_cfver='10.0.0'
* scripts/format-code.ps1:    $required_cfver='10.0.01'

**Comment by Alan-Jowett** [comment]
Should we switch the CI/CD pipeline to use 10.0.0 instead and add an issue to move to LLVM 13.0.0?

**Comment by dthaler** [comment]
https://github.com/microsoft/ebpf-for-windows/pull/959#issuecomment-1100195870 @saxena-anurag wrote:
> Cilium XDP program verification fails with LLVM 12 (not tried with LLVM 13)

So it would be good to use a version known to work with the Cilium XDP program verification, whether that is 10 or 13.

**Comment by dthaler** [comment]
Blocked on #832

**Comment by saxena-anurag** [comment]
Cilium XDP program verification is failing with LLVM v13.

**Comment by dthaler** [comment]
Tested with LLVM 10, 11, 12, 13, 14. 
Verification succeeds for the ebpf-for-windows-demo project with LLVM 10 and 11, but fails with 12, 13, and 14.
It does not look like a bug in the verifier, it's either unsafe code, or the fact that the PREVAIL verifier doesn't track correlated branches.   Changing that is difficult at best, and Linux only deals with it by walking all possible branches, making it not scale well, whereas PREVAIL doesn't and thus has this limitation.   So we should upgrade to LLVM 11 and stick there for now at least.
