### ISSUE TITLE
Assertion failed: ebpf_hash_table_key_count(_ebpf_async_tracker_table) == 0

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#977]
### Describe the bug

The below assert is intermittently hit when stopping ebpfCore driver at the end of kernel CICD tests. Likely some leaked async handle when running the ring buffer tests in api_test suite.

*** Assertion failed: ebpf_hash_table_key_count(_ebpf_async_tracker_table) == 0
***   Source File: f:\ebpf-for-windows\my\libs\platform\ebpf_async.c, line 37

### OS information

Server 2019.

### Steps taken to reproduce bug

1. run api_test.exe
2. net stop ebpfcore

### Expected behavior

Driver stops successfully.

### Actual outcome

System breaks into KD due to this assert.

**Comment by dahavey** [comment]
Related to issue #897

**Comment by Alan-Jowett** [comment]
Doesn't reproduce anymore.
