### ISSUE TITLE
API's missing test coverage

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#980]
From looking at the code coverage for [ebpf_api.cpp](https://app.codecov.io/gh/microsoft/ebpf-for-windows/blob/main/libs/api/ebpf_api.cpp), it looks like we are missing coverage for the following APIs
- [ ] bpf_map_lookup_and_delete_elem
- [ ] ebpf_api_link_program
- [ ] ebpf_map_get_fd

**Comment by saxena-anurag** [comment]
Few points:

1. `ebpf_api_link_program` -- this API should be deprecated as this uses handles. Instead, we should use `bpf_program__attach` / `ebpf_program_attach`. This API is currently being used in test helpers `attach` function.
2. `ebpf_map_get_fd` -- this should also be deprecated. Not used anywhere currently. Instead, we should use `bpf_map__fd`

**Comment by Alan-Jowett** [comment]
If they are not used anywhere can we remove them?

**Comment by saxena-anurag** [comment]
Agree, we should remove the deprecated ones.

**Comment by dthaler** [comment]
I am adding a test for bpf_map_lookup_and_delete_elem
