### ISSUE TITLE
libs/service/api_service.cpp / ebpf_verify_program

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#981]
[api_service.cpp](https://app.codecov.io/gh/microsoft/ebpf-for-windows/blob/main/libs/service/api_service.cpp) shows that ebpf_verify_program isn't covered by the tests.

**Comment by saxena-anurag** [comment]
I think we can completely remove this API. This was added earlier with thought that verification will also happen in ebpfsvc, but that has changed now.

**Comment by dthaler** [comment]
Agree with removal.
