### ISSUE TITLE
Update NativeCodeGeneration.md with latest info

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#984]
### Describe the bug

Information present in `NativeCodeGeneration.md` is old. Need to update it with latest info.

### Steps taken to reproduce bug

NA

### Expected behavior

NA

### Actual outcome

NA

**Comment by dahavey** [comment]
Need to enable script execution in Powershell.

**Comment by dthaler** [comment]
> Need to enable script execution in Powershell.

I think PR #1013 fixes that without requiring a doc change.

**Comment by Alan-Jowett** [comment]
> > Need to enable script execution in Powershell.
> 
> I think PR #1013 fixes that without requirin

**Comment by Alan-Jowett** [comment]
My bad, wrong button.

**Comment by dthaler** [comment]
Blocked in #2085 which must be done first or at the same time.
